CREATE SEQUENCE SSI_CONTEST_CLAIM_FIELD_PK_SQ INCREMENT BY 1 START WITH 7000
/
CREATE TABLE SSI_CONTEST_CLAIM_FIELD
(
	SSI_CONTEST_CLAIM_FIELD_ID         NUMBER(18)    NOT NULL,
	SSI_CONTEST_ID           	       NUMBER(18)    NOT NULL,
	SSI_CLAIM_FORM_STEP_ELEMENT_ID	   NUMBER(18)    NOT NULL,
	IS_REQUIRED                        NUMBER(1) DEFAULT 0,
    SEQUENCE_NUMBER 			       NUMBER(5, 0),
    CREATED_BY        			       NUMBER(18)   NOT NULL,
    DATE_CREATED      			       DATE         NOT NULL,
    MODIFIED_BY       			       NUMBER(18),
    DATE_MODIFIED     			       DATE,
    VERSION				               NUMBER(18)   NOT NULL
)
/
ALTER TABLE SSI_CONTEST_CLAIM_FIELD
ADD CONSTRAINT SSI_CONTEST_CLAIM_FIELD_ID_PK PRIMARY KEY (SSI_CONTEST_CLAIM_FIELD_ID)
USING INDEX
/
ALTER TABLE SSI_CONTEST_CLAIM_FIELD ADD CONSTRAINT CONTEST_FIELD_CONTEST_FK
  FOREIGN KEY (SSI_CONTEST_ID) REFERENCES SSI_CONTEST (SSI_CONTEST_ID)
/
ALTER TABLE SSI_CONTEST_CLAIM_FIELD ADD CONSTRAINT CONTEST_FIELD_STEP_ELEMENT_FK
  FOREIGN KEY (SSI_CLAIM_FORM_STEP_ELEMENT_ID) REFERENCES CLAIM_FORM_STEP_ELEMENT (CLAIM_FORM_STEP_ELEMENT_ID) 
/