ALTER TABLE SSI_CONTEST_PAX_PAYOUT ADD (STACK_RANK_POSITION NUMBER(18), ACTIVITY_AMOUNT NUMBER(18), BADGE_RULE_ID NUMBER(18), PAYOUT_DESCRIPTION VARCHAR2(100))
/
ALTER TABLE SSI_CONTEST_PAX_PAYOUT ADD CONSTRAINT PARTICIPANT_FK
  FOREIGN KEY (USER_ID) REFERENCES PARTICIPANT (USER_ID)
/
ALTER TABLE SSI_CONTEST_PAX_PAYOUT ADD CONSTRAINT SSI_CONTEST_PAX_BADGE_RULE_FK
  FOREIGN KEY (BADGE_RULE_ID) REFERENCES BADGE_RULE (BADGE_RULE_ID)
/
