ALTER TABLE SSI_CONTEST ADD (CONTEST_OWNER_ID			   NUMBER(18),
    IS_SAME_OBJ_DESCRIPTION        NUMBER(1),
    UPDATE_IN_PROGRESS             NUMBER(1) DEFAULT 0,
    CLAIM_SUBMISSION_LAST_DATE     DATE,
    IS_CLAIM_APPROVAL_NEEDED	   NUMBER(1),
    DATA_COLLECTION_TYPE           VARCHAR2(50),
    IS_LAUNCH_NOTIFICATION_SENT    NUMBER(1) DEFAULT 0,
    DATE_LAUNCHED 		   DATE)
/
ALTER TABLE SSI_CONTEST ADD CONSTRAINT SSI_CONTEST_OWNER_FK
  FOREIGN KEY (CONTEST_OWNER_ID) REFERENCES PARTICIPANT (USER_ID)
/