DELETE FROM user_type_role WHERE ROLE_ID = (SELECT role_id FROM role WHERE CODE = 'CLIENT_ADMIN_PAX')
/
DELETE FROM user_role WHERE ROLE_ID = (SELECT role_id FROM role WHERE CODE = 'CLIENT_ADMIN_PAX')
/
DELETE FROM role WHERE CODE = 'CLIENT_ADMIN_PAX'
/
DELETE FROM user_type_role WHERE ROLE_ID = (SELECT role_id FROM role WHERE CODE = 'CLIENT_ADMIN_PROMO')
/
DELETE FROM user_role WHERE ROLE_ID = (SELECT role_id FROM role WHERE CODE = 'CLIENT_ADMIN_PROMO')
/
DELETE FROM role WHERE CODE = 'CLIENT_ADMIN_PROMO'
/
DELETE FROM user_type_role WHERE ROLE_ID = (SELECT role_id FROM role WHERE CODE = 'CLIENT_ADMIN_RPT')
/
DELETE FROM user_role WHERE ROLE_ID = (SELECT role_id FROM role WHERE CODE = 'CLIENT_ADMIN_RPT')
/
DELETE FROM role WHERE CODE = 'CLIENT_ADMIN_RPT'
/
DELETE FROM user_type_role WHERE ROLE_ID = (SELECT role_id FROM role WHERE CODE = 'CLIENT_ADMIN_COMM')
/
DELETE FROM user_role WHERE ROLE_ID = (SELECT role_id FROM role WHERE CODE = 'CLIENT_ADMIN_COMM')
/
DELETE FROM role WHERE CODE = 'CLIENT_ADMIN_COMM'
/