INSERT INTO MODULE_APP
   (MODULE_APP_ID,NAME,DESCRIPTION,IS_MOBILE_ENABLED,AVAILABLE_SIZES,AUDIENCE_TYPE, APP_AUDIENCE_TYPE, TILE_MAPPING_TYPE,  UI_APP_NAME,ADMIN_AUDIENCE_SETUP, CREATED_BY, DATE_CREATED,VERSION)
VALUES
   (3043, 'Instant Poll', 'Desc - Instant Poll',0, '4X4,4X2,2X2','allactivepaxaudience','instantPollModule','instantPollModule', 'instantpoll',0,5662, sysdate, 1)
/
INSERT INTO FILTER_MODULE_APP
   (FILTER_MODULE_APP_ID,MODULE_APP_ID,FILTER_SETUP_TYPE,PRIORITY,ORDER_NUMBER,CREATED_BY, DATE_CREATED,VERSION)
VALUES
   (FILTER_MODULE_APP_PK_SQ.nextval, 3043, 'social', 2, 7, 5662, sysdate, 1)
/
