INSERT INTO FILTER_MODULE_APP
   (FILTER_MODULE_APP_ID,MODULE_APP_ID,FILTER_SETUP_TYPE,PRIORITY,ORDER_NUMBER,CREATED_BY, DATE_CREATED,VERSION)
VALUES
   (FILTER_MODULE_APP_PK_SQ.nextval, 3040, 'throwdown', 1, 0, 5662, sysdate, 1)
/
INSERT INTO FILTER_MODULE_APP
   (FILTER_MODULE_APP_ID,MODULE_APP_ID,FILTER_SETUP_TYPE,PRIORITY,ORDER_NUMBER,CREATED_BY, DATE_CREATED,VERSION)
VALUES
   (FILTER_MODULE_APP_PK_SQ.nextval, 3038, 'throwdown', 1, 1, 5662, sysdate, 1)
/
INSERT INTO FILTER_MODULE_APP
   (FILTER_MODULE_APP_ID,MODULE_APP_ID,FILTER_SETUP_TYPE,PRIORITY,ORDER_NUMBER,CREATED_BY, DATE_CREATED,VERSION)
VALUES
   (FILTER_MODULE_APP_PK_SQ.nextval, 3034, 'throwdown', 1, 2, 5662, sysdate, 1)
/
INSERT INTO FILTER_MODULE_APP
   (FILTER_MODULE_APP_ID,MODULE_APP_ID,FILTER_SETUP_TYPE,PRIORITY,ORDER_NUMBER,CREATED_BY, DATE_CREATED,VERSION)
VALUES
   (FILTER_MODULE_APP_PK_SQ.nextval, 3039, 'throwdown', 2, 3, 5662, sysdate, 1)
/
INSERT INTO FILTER_MODULE_APP
   (FILTER_MODULE_APP_ID,MODULE_APP_ID,FILTER_SETUP_TYPE,PRIORITY,ORDER_NUMBER,CREATED_BY, DATE_CREATED,VERSION)
VALUES
   (FILTER_MODULE_APP_PK_SQ.nextval, 3041, 'throwdown', 2, 4, 5662, sysdate, 1)
/
INSERT INTO FILTER_MODULE_APP
   (FILTER_MODULE_APP_ID,MODULE_APP_ID,FILTER_SETUP_TYPE,PRIORITY,ORDER_NUMBER,CREATED_BY, DATE_CREATED,VERSION)
VALUES
   (FILTER_MODULE_APP_PK_SQ.nextval, 3036, 'throwdown', 2, 5, 5662, sysdate, 1)
/
INSERT INTO FILTER_MODULE_APP
   (FILTER_MODULE_APP_ID,MODULE_APP_ID,FILTER_SETUP_TYPE,PRIORITY,ORDER_NUMBER,CREATED_BY, DATE_CREATED,VERSION)
VALUES
   (FILTER_MODULE_APP_PK_SQ.nextval, 3035, 'throwdown', 2, 6, 5662, sysdate, 1)
/
INSERT INTO FILTER_MODULE_APP
   (FILTER_MODULE_APP_ID,MODULE_APP_ID,FILTER_SETUP_TYPE,PRIORITY,ORDER_NUMBER,CREATED_BY, DATE_CREATED,VERSION)
VALUES
   (FILTER_MODULE_APP_PK_SQ.nextval, 3037, 'throwdown', 2, 7, 5662, sysdate, 1)
/