DROP TABLE PARTICIPANT_EVENT CASCADE CONSTRAINTS
/
DROP TABLE EVENT CASCADE CONSTRAINTS
/
DROP TABLE GAME_ATTEMPT CASCADE CONSTRAINTS
/
DROP TABLE GAME_AWARD_LEVEL CASCADE CONSTRAINTS
/
DROP TABLE GAME_AWARD CASCADE CONSTRAINTS
/
DROP TABLE GAME_PAYOUT CASCADE CONSTRAINTS
/
DROP TABLE GAME CASCADE CONSTRAINTS
/
DROP TABLE HOMEPAGE_LAYOUT CASCADE CONSTRAINTS
/
DROP TABLE STAGE_SURVEY_IMPORT_RECORD CASCADE CONSTRAINTS
/
DROP TABLE SWEEPSTAKES_PARTICIPANT CASCADE CONSTRAINTS
/
DROP PROCEDURE PRC_LOAD_PAYOUT
/
DROP PROCEDURE PRC_SURVEY_LOAD
/
DROP PROCEDURE PRC_INSERT_STG_SURVEY
/
DROP SEQUENCE game_attempt_pk_sq
/
DROP SEQUENCE event_pk_sq
/
DROP SEQUENCE EVENT_ID_PK_SQ
/
DROP SEQUENCE HOMEPAGE_LAYOUT_PK_SQ
/
DROP SEQUENCE GAME_AWARD_LEVEL_PK_SQ
/
DROP SEQUENCE GAME_AWARD_PK_SQ
/
DROP SEQUENCE GAME_PAYOUT_PK_SQ
/
DROP SEQUENCE GAME_PK_SQ
/
DROP SEQUENCE sweepstakes_participant_pk_sq
/