INSERT INTO MODULE_APP
   (MODULE_APP_ID,NAME,DESCRIPTION,IS_MOBILE_ENABLED,AVAILABLE_SIZES,AUDIENCE_TYPE, APP_AUDIENCE_TYPE, TILE_MAPPING_TYPE,  UI_APP_NAME,ADMIN_AUDIENCE_SETUP, CREATED_BY, DATE_CREATED,VERSION)
VALUES
   (3034, 'Throwdown Smack Talk', 'Desc - Throwdown Smack Talk ',0, '4X4,4X2,2X2,2X1,1X1','allactivepaxaudience','throwdownModule','smackTalkModule', 'throwdown',1,5662, sysdate, 1)
/
INSERT INTO MODULE_APP
   (MODULE_APP_ID,NAME,DESCRIPTION,IS_MOBILE_ENABLED,AVAILABLE_SIZES,AUDIENCE_TYPE, APP_AUDIENCE_TYPE, TILE_MAPPING_TYPE,  UI_APP_NAME,ADMIN_AUDIENCE_SETUP, CREATED_BY, DATE_CREATED,VERSION)
VALUES
   (3035, 'Throwdown Training Camp', 'Desc - Throwdown Training Camp',0, '2X1,1X1','allactivepaxaudience','throwdownModule','throwdownTrainingCampModule', 'throwdown',1,5662, sysdate, 1)
/
INSERT INTO MODULE_APP
   (MODULE_APP_ID,NAME,DESCRIPTION,IS_MOBILE_ENABLED,AVAILABLE_SIZES,AUDIENCE_TYPE, APP_AUDIENCE_TYPE, TILE_MAPPING_TYPE,  UI_APP_NAME,ADMIN_AUDIENCE_SETUP, CREATED_BY, DATE_CREATED,VERSION)
VALUES
   (3036, 'Throwdown News', 'Desc - Throwdown News ',0, '2X1,1X1','allactivepaxaudience','throwdownModule','throwdownNewsModule', 'throwdown',1,5662, sysdate, 1)
/
INSERT INTO MODULE_APP
   (MODULE_APP_ID,NAME,DESCRIPTION,IS_MOBILE_ENABLED,AVAILABLE_SIZES,AUDIENCE_TYPE, APP_AUDIENCE_TYPE, TILE_MAPPING_TYPE,  UI_APP_NAME,ADMIN_AUDIENCE_SETUP, CREATED_BY, DATE_CREATED,VERSION)
VALUES
   (3037, 'Throwdown Standings', 'Desc - Throwdown Standings',0, '4X4,4X2,2X2,2X1,1X1','allactivepaxaudience','throwdownModule','throwdownStandingsModule', 'throwdown',1,5662, sysdate, 1)
/
INSERT INTO MODULE_APP
   (MODULE_APP_ID,NAME,DESCRIPTION,IS_MOBILE_ENABLED,AVAILABLE_SIZES,AUDIENCE_TYPE, APP_AUDIENCE_TYPE, TILE_MAPPING_TYPE,  UI_APP_NAME,ADMIN_AUDIENCE_SETUP, CREATED_BY, DATE_CREATED,VERSION)
VALUES
   (3038, 'Throwdown Match List', 'Desc - Throwdown Match List',0, '4X4,4X2,2X2,2X1,1X1','allactivepaxaudience','throwdownMatchListModule','throwdownAllMatchesModule', 'throwdown',1,5662, sysdate, 1)
/
INSERT INTO MODULE_APP
   (MODULE_APP_ID,NAME,DESCRIPTION,IS_MOBILE_ENABLED,AVAILABLE_SIZES,AUDIENCE_TYPE, APP_AUDIENCE_TYPE, TILE_MAPPING_TYPE,  UI_APP_NAME,ADMIN_AUDIENCE_SETUP, CREATED_BY, DATE_CREATED,VERSION)
VALUES
   (3039, 'Throwdown PromoName Selector', 'Desc - Throwdown PromoName Selector',0, '2X1,1X1','allactivepaxaudience','throwdownModule','throwdownPromoSelectModule', 'throwdown',1,5662, sysdate, 1)
/
INSERT INTO MODULE_APP
   (MODULE_APP_ID,NAME,DESCRIPTION,IS_MOBILE_ENABLED,AVAILABLE_SIZES,AUDIENCE_TYPE, APP_AUDIENCE_TYPE, TILE_MAPPING_TYPE,  UI_APP_NAME,ADMIN_AUDIENCE_SETUP, CREATED_BY, DATE_CREATED,VERSION)
VALUES
   (3040, 'Throwdown Match Summary', 'Desc - Throwdown Match Summary',0, '4X4,4X2,2X2,2X1,1X1','allactivepaxaudience','throwdownModule','throwdownMatchModule', 'throwdown',1,5662, sysdate, 1)
/
INSERT INTO MODULE_APP
   (MODULE_APP_ID,NAME,DESCRIPTION,IS_MOBILE_ENABLED,AVAILABLE_SIZES,AUDIENCE_TYPE, APP_AUDIENCE_TYPE, TILE_MAPPING_TYPE,  UI_APP_NAME,ADMIN_AUDIENCE_SETUP, CREATED_BY, DATE_CREATED,VERSION)
VALUES
   (3041, 'Throwdown Rankings', 'Desc - Throwdown Rankings',0, '2X2,2X1,1X1','allactivepaxaudience','throwdownModule','throwdownRankingsModule', 'throwdown',1,5662, sysdate, 1)
/
INSERT INTO MODULE_APP
   (MODULE_APP_ID,NAME,DESCRIPTION,IS_MOBILE_ENABLED,AVAILABLE_SIZES,AUDIENCE_TYPE, APP_AUDIENCE_TYPE, TILE_MAPPING_TYPE,  UI_APP_NAME,ADMIN_AUDIENCE_SETUP, CREATED_BY, DATE_CREATED,VERSION)
VALUES
   (3042, 'Throwdown Rules', 'Desc - Throwdown Rules',0, '2X1,1X1','allactivepaxaudience','throwdownModule','throwdownRulesModule', 'throwdown',1,5662, sysdate, 1)
/