Insert into REPORT (REPORT_ID,REPORT_CODE, CM_ASSET_CODE, REPORT_NAME_CM_KEY, REPORT_CATEGORY_TYPE, MODULE, REPORT_DESCRIPTION_CM_KEY, REPORT_URL, IS_ACTIVE, CREATED_BY, DATE_CREATED, VERSION, FORCE_PARAMETERS, EXPORT_ONLY)
values (4038,'surveyAnalysis','report.survey.surveyanalysis','REPORT_NAME', 'survey','install.survey', 'REPORT_DESCRIPTION', '/reports/displaySurveyAnalysisReport.do?method=displaySummaryReport', 1, 0, sysdate, 0, 1, 0)
/
Insert into REPORT_CHART (REPORT_CHART_ID, CAPTION_CM_KEY, SUBCAPTION_CM_KEY, CHART_DATA_URL, REPORT_ID, SHOW_LABELS, SHOW_LEGEND, ENABLE_SMART_LABELS, X_AXIS_NAME_CM_KEY, Y_AXIS_NAME_CM_KEY, SEQUENCE_NUM, DISPLAY_LIMIT, CREATED_BY, DATE_CREATED, VERSION, CHART_TYPE)
values (3122, 'STD_DEV_CHART_CAPTION', 'STD_DEV_CHART_SUBCAPTION', '/reports/displaySurveyAnalysisReport.do?method=displayStandardDeviationBarchart', 4038, 1, 1, 0, 'SURVEY_QUESTION_XAXIS', 'SURVEY_QUESTION_YAXIS', 0, 20, 0, sysdate, 0, 'MSColumn3D')
/
Insert into REPORT_CHART (REPORT_CHART_ID, CAPTION_CM_KEY, SUBCAPTION_CM_KEY, CHART_DATA_URL, REPORT_ID, SHOW_LABELS, SHOW_LEGEND, ENABLE_SMART_LABELS, X_AXIS_NAME_CM_KEY, Y_AXIS_NAME_CM_KEY, SEQUENCE_NUM, DISPLAY_LIMIT, CREATED_BY, DATE_CREATED, VERSION, CHART_TYPE)
values (3123, 'TOTAL_RESP_PER_CHART_CAPTION', 'TOTAL_RESP_PER_CHART_SUBCAPTION', '/reports/displaySurveyAnalysisReport.do?method=displayTotalResponsePercentBarchart', 4038, 1, 1, 0, 'SURVEY_ATTEMPT_XAXIS', 'SURVEY_ATTEMPT_YAXIS', 1, 20, 0, sysdate, 0, 'StackedColumn3D')
/
Insert into REPORT_PARAMETER (REPORT_PARAMETER_ID, REPORT_ID, PARAMETER_NAME, PARAMETER_CM_KEY, DATABASE_COLUMN, PARAMETER_TYPE, LIST_DEFINITION, PARAMETER_GROUP, SEQUENCE_NUM, CREATED_BY, DATE_CREATED, MODIFIED_BY, DATE_MODIFIED, VERSION, COLLECTION_NAME, DEFAULT_VALUE) 
values (3155,4038,'promotionStatus','PROMOTION_STATUS_FIELD','reportPromotionStatusTypeList','selectPicklist','picklist.reportpromotion.statustype','BASICS',0,5661,to_date('20-AUG-12','DD-MON-RR'),5661,to_date('20-AUG-12','DD-MON-RR'),0,'reportPromotionStatusTypeList','live')
/
Insert into REPORT_PARAMETER (REPORT_PARAMETER_ID, REPORT_ID, PARAMETER_NAME, PARAMETER_CM_KEY, DATABASE_COLUMN, PARAMETER_TYPE, LIST_DEFINITION, PARAMETER_GROUP, SEQUENCE_NUM, CREATED_BY, DATE_CREATED, MODIFIED_BY, DATE_MODIFIED, VERSION, COLLECTION_NAME, DEFAULT_VALUE, DISPLAY_ON_DASHBOARD) 
values (3156,4038,'promotionId','PROMOTION_FIELD','promotionTypeList','selectQuery','com.biperf.core.domain.node.reportParameterValueChoices.allLiveSurveyPromotions','BASICS',1,5661,to_date('20-AUG-12','DD-MON-RR'),5661,to_date('20-AUG-12','DD-MON-RR'),0,'promotionTypeList','show_all', 1)
/
Insert into REPORT_PARAMETER (REPORT_PARAMETER_ID, REPORT_ID, PARAMETER_NAME, PARAMETER_CM_KEY, DATABASE_COLUMN, PARAMETER_TYPE, LIST_DEFINITION, PARAMETER_GROUP, SEQUENCE_NUM, CREATED_BY, DATE_CREATED, MODIFIED_BY, DATE_MODIFIED, VERSION, COLLECTION_NAME, DEFAULT_VALUE, DISPLAY_ON_DASHBOARD) 
values (3157,4038,'parentNodeId','ORG_NAME','organizationList','selectQuery','com.biperf.core.domain.node.processParameterValueChoices.NodesAsHierarchyByUser','PARTICIPANTS',6,5661,sysdate,null,null,0,'organizationList','show_all', 1)
/
Insert into REPORT_PARAMETER (REPORT_PARAMETER_ID, REPORT_ID, PARAMETER_NAME, PARAMETER_CM_KEY, DATABASE_COLUMN, PARAMETER_TYPE, LIST_DEFINITION, PARAMETER_GROUP, SEQUENCE_NUM, CREATED_BY, DATE_CREATED, MODIFIED_BY, DATE_MODIFIED, VERSION, COLLECTION_NAME, DEFAULT_VALUE) 
values (3158,4038,'participantStatus','PARTICIPANT_STATUS_FIELD','participantStatusList','selectPicklist','picklist.participantstatus','PARTICIPANTS',3,5661,to_date('20-AUG-12','DD-MON-RR'),5661,to_date('20-AUG-12','DD-MON-RR'),0,'participantStatusList','active')
/
