Insert into REPORT (REPORT_ID,REPORT_CODE, CM_ASSET_CODE,REPORT_NAME_CM_KEY,REPORT_CATEGORY_TYPE,MODULE,REPORT_DESCRIPTION_CM_KEY,REPORT_URL,IS_ACTIVE,CREATED_BY,DATE_CREATED,MODIFIED_BY,DATE_MODIFIED,VERSION, FORCE_PARAMETERS, EXPORT_ONLY) 
values (4037,'throwdownActivityByPax','report.throwdownactivity.bypax','REPORT_NAME','throwdown','install.throwdown','REPORT_DESCRIPTION','/reports/displayThrowdownActivityByPaxSummaryReport.do?method=displaySummaryReport',1,0,sysdate,null,null,0, 0, 0)
/
Insert into REPORT_CHART (REPORT_CHART_ID, CAPTION_CM_KEY, SUBCAPTION_CM_KEY, CHART_DATA_URL, REPORT_ID, SHOW_LABELS, SHOW_LEGEND, ENABLE_SMART_LABELS, X_AXIS_NAME_CM_KEY, Y_AXIS_NAME_CM_KEY, SEQUENCE_NUM, DISPLAY_LIMIT, CREATED_BY, DATE_CREATED, VERSION, CHART_TYPE)
values (3119, 'TOTAL_ACTIVITY_CHART_CAPTION', 'TOTAL_ACTIVITY_CHART_SUBCAPTION', '/reports/displayThrowdownActivityByPaxSummaryReport.do?method=displayThrowdownTotalActivityChart', 4037, 1, 1, 0, 'TOTAL_ACTIVITY_X_AXIS', 'TOTAL_ACTIVITY_Y_AXIS', 0, 20, 0, sysdate, 0, 'Column3D')
/
Insert into REPORT_CHART (REPORT_CHART_ID, CAPTION_CM_KEY, SUBCAPTION_CM_KEY, CHART_DATA_URL, REPORT_ID, SHOW_LABELS, SHOW_LEGEND, ENABLE_SMART_LABELS, X_AXIS_NAME_CM_KEY, Y_AXIS_NAME_CM_KEY, SEQUENCE_NUM, DISPLAY_LIMIT, CREATED_BY, DATE_CREATED, VERSION, CHART_TYPE)
values (3120, 'ACITIVITY_BY_ROUND_CHART_CAPTION', 'ACITIVITY_BY_ROUND_CHART_SUBCAPTION', '/reports/displayThrowdownActivityByPaxSummaryReport.do?method=displayThrowdownActivityByRoundChart', 4037, 1, 1, 0, 'ACITIVITY_BY_ROUND_X_AXIS', 'ACITIVITY_BY_ROUND_Y_AXIS', 1, 20, 0, sysdate, 0, 'Column3D')
/
Insert into REPORT_CHART (REPORT_CHART_ID, CAPTION_CM_KEY, SUBCAPTION_CM_KEY, CHART_DATA_URL, REPORT_ID, SHOW_LABELS, SHOW_LEGEND, ENABLE_SMART_LABELS, X_AXIS_NAME_CM_KEY, Y_AXIS_NAME_CM_KEY, SEQUENCE_NUM, DISPLAY_LIMIT, CREATED_BY, DATE_CREATED, VERSION, CHART_TYPE)
values (3121, 'ACTIVITY_POINTS_CHART_CAPTION', 'ACTIVITY_POINTS_CHART_SUBCAPTION', '/reports/displayThrowdownActivityByPaxSummaryReport.do?method=displayThrowdownPointsEarnedChart', 4037, 1, 1, 0, 'ACTIVITY_POINTS_X_AXIS', 'ACTIVITY_POINTS_Y_AXIS', 2, 20, 0, sysdate, 0, 'Column3D')
/
Insert into REPORT_PARAMETER (REPORT_PARAMETER_ID, REPORT_ID, PARAMETER_NAME, PARAMETER_CM_KEY, DATABASE_COLUMN, PARAMETER_TYPE, LIST_DEFINITION, PARAMETER_GROUP, SEQUENCE_NUM, CREATED_BY, DATE_CREATED, MODIFIED_BY, DATE_MODIFIED, VERSION, COLLECTION_NAME, DEFAULT_VALUE) 
values (2262,4037,'promotionStatus','PROMOTION_STATUS_FIELD','reportPromotionStatusTypeList','selectPicklist','picklist.reportpromotion.statustype','BASICS',0,5661,to_date('20-AUG-12','DD-MON-RR'),5661,to_date('20-AUG-12','DD-MON-RR'),0,'reportPromotionStatusTypeList','live')
/
Insert into REPORT_PARAMETER (REPORT_PARAMETER_ID, REPORT_ID, PARAMETER_NAME, PARAMETER_CM_KEY, DATABASE_COLUMN, PARAMETER_TYPE, LIST_DEFINITION, PARAMETER_GROUP, SEQUENCE_NUM, CREATED_BY, DATE_CREATED, MODIFIED_BY, DATE_MODIFIED, VERSION, COLLECTION_NAME, DEFAULT_VALUE, DISPLAY_ON_DASHBOARD) 
values (2263,4037,'promotionId','PROMOTION_FIELD','promotionTypeList','multiSelectQuery','com.biperf.core.domain.node.reportParameterValueChoices.allLiveThrowdownPromotions','BASICS',1,5661,to_date('20-AUG-12','DD-MON-RR'),5661,to_date('20-AUG-12','DD-MON-RR'),0,'promotionTypeList','show_all', 1)
/
Insert into REPORT_PARAMETER (REPORT_PARAMETER_ID, REPORT_ID, PARAMETER_NAME, PARAMETER_CM_KEY, DATABASE_COLUMN, PARAMETER_TYPE, LIST_DEFINITION, PARAMETER_GROUP, SEQUENCE_NUM, CREATED_BY, DATE_CREATED, MODIFIED_BY, DATE_MODIFIED, VERSION, COLLECTION_NAME, DEFAULT_VALUE, DISPLAY_ON_DASHBOARD) 
values (2264,4037,'roundNumber','ROUND_FIELD','roundNumberTypeList','selectQuery','com.biperf.core.domain.reportParameter.reportParameterValueChoices.allThrowdownRoundNumbers','BASICS',2,5661,to_date('20-AUG-12','DD-MON-RR'),5661,to_date('20-AUG-12','DD-MON-RR'),0,'roundNumberTypeList','show_all', 1)
/
Insert into REPORT_PARAMETER (REPORT_PARAMETER_ID, REPORT_ID, PARAMETER_NAME, PARAMETER_CM_KEY, DATABASE_COLUMN, PARAMETER_TYPE, LIST_DEFINITION, PARAMETER_GROUP, SEQUENCE_NUM, CREATED_BY, DATE_CREATED, MODIFIED_BY, DATE_MODIFIED, VERSION, COLLECTION_NAME, DEFAULT_VALUE) 
values (2265,4037,'participantStatus','PARTICIPANT_STATUS_FIELD','participantStatusList','selectPicklist','picklist.participantstatus','PARTICIPANTS',3,5661,to_date('20-AUG-12','DD-MON-RR'),5661,to_date('20-AUG-12','DD-MON-RR'),0,'participantStatusList','active')
/
Insert into REPORT_PARAMETER (REPORT_PARAMETER_ID, REPORT_ID, PARAMETER_NAME, PARAMETER_CM_KEY, DATABASE_COLUMN, PARAMETER_TYPE, LIST_DEFINITION, PARAMETER_GROUP, SEQUENCE_NUM, CREATED_BY, DATE_CREATED, MODIFIED_BY, DATE_MODIFIED, VERSION, COLLECTION_NAME, DEFAULT_VALUE) 
values (2266,4037,'jobPosition','JOB_POSITION_FIELD','positionTypeList','selectPicklist','picklist.positiontype','PARTICIPANTS',4,5661,to_date('20-AUG-12','DD-MON-RR'),5661,to_date('20-AUG-12','DD-MON-RR'),0,'jobPositionTypeList','show_all')
/
Insert into REPORT_PARAMETER (REPORT_PARAMETER_ID, REPORT_ID, PARAMETER_NAME, PARAMETER_CM_KEY, DATABASE_COLUMN, PARAMETER_TYPE, LIST_DEFINITION, PARAMETER_GROUP, SEQUENCE_NUM, CREATED_BY, DATE_CREATED, MODIFIED_BY, DATE_MODIFIED, VERSION, COLLECTION_NAME, DEFAULT_VALUE) 
values (2267,4037,'department','DEPARTMENT_FIELD','departmentTypeList','multiSelectPick','picklist.department.type','PARTICIPANTS',5,5661,to_date('20-AUG-12','DD-MON-RR'),5661,to_date('20-AUG-12','DD-MON-RR'),0,'departmentTypeList','show_all')
/