<%@ include file="/include/taglib.jspf"%>

<!-- ======== ADVANCED SEARCH PAGE ======== -->

<div id="advancedSearchPageView" class="profilePage-liner page-content">

    <!-- Page Body -->
    <div class="row-fluid">
        <div class="span12">


                <!-- End Code generated by customFormElements.jsp" -->

                <fieldset class="formSection participantSearchSection" id="addTeamMemberSearch">
                    <h3><cms:contentText key="TITLE" code="participant.search" />

                        <span class="validateme hiddenValidationInput" data-validate-flags="nonempty" data-validate-fail-msgs='{"nonempty" : "You must add at least one team member."}'>
                            <input type="text" class="hiddenValidationInput hidden" id="teamMembersCount" name="teamMembersCount" value="" readonly>
                        </span>
                    </h3>
                    <!--
                        Participant search view Element
                        - data-search-types: defines the dropdowns and autocompletes
                        - data-search-params: defines extra static parameters to send with autocomp and participant requests
                        - data-autocomp-delay: how long to wait after key entry to query server
                        - data-autocomp-min-chars: min num chars before querying server
                        - data-search-url: override search json provider (usually needed)
                        - data-select-mode: 'single' OR 'multiple' select behavior
                        - data-msg-select-txt: link to select (optional)
                        - data-msg-selected-txt: text to show something is selected (optional)
                    -->

                    <div id="addTeamMembersWrap">

                        <div id="participantSearchView"
                            data-search-types='[{"id":"lastName","name":"<cms:contentText key="SEARCHBY_LAST_NAME" code="recognition.select.recipients"/>"},{"id":"firstName","name":"<cms:contentText key="SEARCHBY_FIRST_NAME" code="recognition.select.recipients"/>"},{"id":"location","name":"<cms:contentText key="SEARCHBY_LOCATION" code="recognition.select.recipients"/>"},{"id":"jobTitle","name":"<cms:contentText key="SEARCHBY_JOB_TITLE" code="recognition.select.recipients"/>"},{"id":"department","name":"<cms:contentText key="SEARCHBY_DEPARTMENT" code="recognition.select.recipients"/>"},{"id":"country","name":"<cms:contentText key="COUNTRY" code="recognition.select.recipients"/>"}]'
                            data-search-params='{}'
                            data-autocomp-delay="500"
                            data-autocomp-min-chars="2"
                            data-autocomp-url="${pageContext.request.contextPath}/findOthersSearch.do?method=doAutoComplete"
                            data-search-url="${pageContext.request.contextPath}/findOthersSearch.do?method=generatePaxSearchView&searchType=advanced"
                            data-select-mode="single"
                            data-msg-select-txt='<cms:contentText key="VIEW_PROFILE" code="participant.profile"/>'
                            data-msg-selected-txt="<i class='icon icon-check'></i>">

                            <!-- added by view -->
                        </div>
                    </div><!-- /#addTeamMembersWrap -->
                </fieldset><!-- /#addTeamMemberSearch -->

        </div>
    </div><!-- /.row-fluid -->
</div><!-- /#advancedSearchPageView -->

<%@include file="/submitrecognition/easy/flipSide.jsp" %>

<script id="teamMemberRowTpl" type="text/x-handlebars-template">
    <tr class="participant-item"
    data-participant-cid="{{cid}}"
    data-participant-id="{{id}}">

        <td class="participant">
        	<input type="hidden" name="pax[{{autoIndex}}].userId" value="{{id}}" />

         	<a class="participant-popover" href="#" data-participant-ids="[{{id}}]">
        		{{lastName}}, {{firstName}}
         	</a>
        </td>

        <td class="remove">
            <a class="remParticipantControl" title='<cms:contentText key="REMOVE_PARTICIPANT" code="participant.search" />' ><i class="icon-close"></i></a>
        </td>
    </tr><!-- /.participant-item -->
</script>
<script type="text/template" id="recipientListTtl">
    <ul id="ezRecipListWrapper">
    {{#each this}}
        <li class="moduleRecipWrapper" data-tabindex="{{this.index}}" data-recipientId="{{this.id}}" data-recipientNodeId="{{this.nodeId}}">
            <h1>{{this.firstName}} {{this.lastName}}</h1>
            <h2>{{this.orgName}}</h2>
            <h3>{{#if this.departmentName}}{{this.departmentName}}, {{/if}}{{this.jobName}}</h3>
        </li>
    {{else}}
        <li>
             <cms:contentText key="NO_RESULTS" code="participant.search" />
        </li>
    {{/each}}
    </ul>
</script>

<!-- Instantiate the PageView - this goes here as it expresses the DOM element the PageView is getting attached to -->
<script>
    $(document).ready(function() {
          var gpsv;

        //attach the view to an existing DOM element
        window.gpsv = new ParticipantProfileSearchPageView ({
            el: $('#advancedSearchPageView'),

            pageTitle: '<cms:contentText key="TITLE_HEADER" code="participant.search" />'
        });

    });
</script>
<script>
  $(document).ready(function() {
    G5.props.URL_JSON_PARTICIPANT_INFO = "${pageContext.request.contextPath}/participantPublicProfile.do?method=populatePax";

    //Mini Profile PopUp Follow Unfollow Pax JSON
    G5.props.URL_JSON_PARTICIPANT_FOLLOW = G5.props.URL_ROOT+'publicRecognitionFollowUnFollowPax.do?method=followUnFollowPax';

  });
</script>
<script type="text/template" id="participantSearchViewTpl">
  <%@include file="/profileutil/participantSearchView.jsp" %>
</script>
<script type="text/template" id="participantSearchTableRowTpl">
  <%@include file="/profileutil/participantSearchTableRow.jsp" %>
</script>
