CREATE USER beacon IDENTIFIED BY beacon;

GRANT EXECUTE ON DBMS_CRYPTO TO beacon;

create or replace directory beacon_external as '/u01/app/oracle/product/11.2.0/xe/working';

GRANT READ ON DIRECTORY beacon_external TO beacon;
GRANT WRITE ON DIRECTORY beacon_external TO beacon;

GRANT execute ON ORACLE_LOADER TO beacon;
GRANT EXECUTE ON  UTL_FILE TO beacon;
GRANT EXECUTE ON "SYS"."UTL_TCP" TO beacon;
GRANT EXECUTE ON  UTL_SMTP TO beacon;

grant CREATE SESSION, ALTER SESSION, CREATE DATABASE LINK, CREATE MATERIALIZED VIEW, CREATE PROCEDURE, CREATE PUBLIC SYNONYM, CREATE ROLE, CREATE SEQUENCE, CREATE SYNONYM, CREATE TABLE, CREATE TRIGGER, CREATE TYPE, CREATE VIEW, UNLIMITED TABLESPACE to beacon;

GRANT CREATE ANY CONTEXT to beacon;

EXIT;