CREATE SEQUENCE WORKHAPPIER_ID_PK_SQ INCREMENT BY 1 START WITH 1000
/
CREATE TABLE WORKHAPPIER
(WORKHAPPIER_ID     NUMBER(18) NOT NULL,
 IMAGE_NAME         VARCHAR2(300),
 MIN_VALUE          NUMBER (10),
 MAX_VALUE          NUMBER (10),
 WH_CM_ASSET_CODE    VARCHAR2(100),
 DATE_CREATED       DATE        NOT NULL,
 CREATED_BY         NUMBER(18)  NOT NULL,
 DATE_MODIFIED      DATE,
 MODIFIED_BY        NUMBER(18),
 VERSION            NUMBER(18),
 CONSTRAINT WORKHAPPIER_ID_PK PRIMARY KEY (WORKHAPPIER_ID)
 )
/
CREATE SEQUENCE WORKHAPPIER_FEEDBACK_ID_PK_SQ INCREMENT BY 1 START WITH 1000
/
CREATE TABLE WORKHAPPIER_FEEDBACK
(WORKHAPPIER_FEEDBACK_ID        NUMBER(18)  NOT NULL,
 NODE_ID                        NUMBER(10),
 COMMENTS                       VARCHAR2(4000),
 DATE_CREATED                   DATE        NOT NULL,
 CREATED_BY                     NUMBER(18)  NOT NULL,
 DATE_MODIFIED                  DATE,
 MODIFIED_BY                    NUMBER(18),
 VERSION                        NUMBER(18),
  CONSTRAINT WORKHAPPIER_FEEDBACK_ID_PK PRIMARY KEY (WORKHAPPIER_FEEDBACK_ID)
 )
/
CREATE SEQUENCE WORKHAPPIER_SCORE_ID_PK_SQ INCREMENT BY 1 START WITH 1000
/
CREATE TABLE WORKHAPPIER_SCORE
(WORKHAPPIER_SCORE_ID           NUMBER(18)  NOT NULL,
 WORKHAPPIER_ID                 NUMBER(18)  NOT NULL,
 USER_ID                        NUMBER(10),
 NODE_ID                        NUMBER(10),
 SCORE                          NUMBER (10),
 DATE_CREATED                   DATE        NOT NULL,
 CREATED_BY                     NUMBER(18)  NOT NULL,
 DATE_MODIFIED                  DATE,
 MODIFIED_BY                    NUMBER(18),
 VERSION                        NUMBER(18),
 CONSTRAINT WORKHAPPIER_SCORE_ID_PK PRIMARY KEY (WORKHAPPIER_SCORE_ID),
 CONSTRAINT WORKHAPPIER_ID_SC_FK
  FOREIGN KEY (WORKHAPPIER_ID) REFERENCES WORKHAPPIER (WORKHAPPIER_ID) 
 )
/
CREATE TABLE WORKHAPPIER_EXTRACT
(EMAIL_ADDRESS           VARCHAR2(75)  NOT NULL
 )
/