CREATE GLOBAL TEMPORARY TABLE gtt_recog_elg_pax_count
(
  ELIGIBLE_COUNT  NUMBER,
  NODE_ID         NUMBER,
  PARTICIPANT_ID NUMBER,
  RECORD_TYPE     VARCHAR2(10 CHAR)
)
ON COMMIT PRESERVE ROWS
RESULT_CACHE (MODE DEFAULT)
NOCACHE
/