INSERT INTO MODULE_APP
   (MODULE_APP_ID,NAME,DESCRIPTION,IS_MOBILE_ENABLED,AVAILABLE_SIZES,AUDIENCE_TYPE, APP_AUDIENCE_TYPE, TILE_MAPPING_TYPE,  UI_APP_NAME,ADMIN_AUDIENCE_SETUP, CREATED_BY, DATE_CREATED,VERSION)
VALUES
   (3054, 'Work Happier', 'Desc - Work Happier',0, '4X4,4X2,2X2,1X1','allactivepaxaudience','workHappierPaxModule','workHappierPaxModule', 'workHappier',1,5662, sysdate, 1)
/