INSERT INTO card (CARD_ID,CARD_NAME,SMALL_IMAGE_NAME,LARGE_IMAGE_NAME,IS_ACTIVE,IS_MOBILE,CREATED_BY,DATE_CREATED, VERSION)
    VALUES (4000, 'Thank You 1', '01-Thank-you-144.jpg', '01-Thank-you-432.jpg', 1, 0, 0, sysdate, 1)
/
INSERT INTO card (CARD_ID,CARD_NAME,SMALL_IMAGE_NAME,LARGE_IMAGE_NAME,IS_ACTIVE,IS_MOBILE,CREATED_BY,DATE_CREATED, VERSION)
    VALUES (4001, 'Congratulations 1', '02-Congratulations-144.jpg', '02-Congratulations-432.jpg', 1, 0, 0, sysdate, 1)
/
INSERT INTO card (CARD_ID,CARD_NAME,SMALL_IMAGE_NAME,LARGE_IMAGE_NAME,IS_ACTIVE,IS_MOBILE,CREATED_BY,DATE_CREATED, VERSION)
    VALUES (4002, 'Rock Star 1', '03-You-are-a-Rock-Star-144.jpg', '03-You-are-a-Rock-Star-432.jpg', 1, 0, 0, sysdate, 1)
/
INSERT INTO card (CARD_ID,CARD_NAME,SMALL_IMAGE_NAME,LARGE_IMAGE_NAME,IS_ACTIVE,IS_MOBILE,CREATED_BY,DATE_CREATED, VERSION)
    VALUES (4003, 'Above and Beyond 1', '04-Above-and-Beyond-144.jpg', '04-Above-and-Beyond-432.jpg', 1, 0, 0, sysdate, 1)
/
INSERT INTO card (CARD_ID,CARD_NAME,SMALL_IMAGE_NAME,LARGE_IMAGE_NAME,IS_ACTIVE,IS_MOBILE,CREATED_BY,DATE_CREATED, VERSION)
    VALUES (4004, 'Teamwork 1', '05-Teamwork-144.jpg', '05-Teamwork-432.jpg', 1, 0, 0, sysdate, 1)
/
INSERT INTO card (CARD_ID,CARD_NAME,SMALL_IMAGE_NAME,LARGE_IMAGE_NAME,IS_ACTIVE,IS_MOBILE,CREATED_BY,DATE_CREATED, VERSION)
    VALUES (4005, 'Extra Effort 1', '06-Extra-Effort-144.jpg', '06-Extra-Effort-432.jpg', 1, 0, 0, sysdate, 1)
/
INSERT INTO card (CARD_ID,CARD_NAME,SMALL_IMAGE_NAME,LARGE_IMAGE_NAME,IS_ACTIVE,IS_MOBILE,CREATED_BY,DATE_CREATED, VERSION)
    VALUES (4006, 'You''re My Hero 1', '07-Youre-My-Hero-144.jpg', '07-Youre-My-Hero-432.jpg', 1, 0, 0, sysdate, 1)
/
INSERT INTO card (CARD_ID,CARD_NAME,SMALL_IMAGE_NAME,LARGE_IMAGE_NAME,IS_ACTIVE,IS_MOBILE,CREATED_BY,DATE_CREATED, VERSION)
    VALUES (4007, 'Innovation 1', '08-Innovation-144.jpg', '08-Innovation-432.jpg', 1, 0, 0, sysdate, 1)
/
INSERT INTO card (CARD_ID,CARD_NAME,SMALL_IMAGE_NAME,LARGE_IMAGE_NAME,IS_ACTIVE,IS_MOBILE,CREATED_BY,DATE_CREATED, VERSION)
    VALUES (4008, 'Leadership 1', '09-Leadership-144.jpg', '09-Leadership-432.jpg', 1, 0, 0, sysdate, 1)
/
INSERT INTO card (CARD_ID,CARD_NAME,SMALL_IMAGE_NAME,LARGE_IMAGE_NAME,IS_ACTIVE,IS_MOBILE,CREATED_BY,DATE_CREATED, VERSION)
    VALUES (4009, 'You are Awesome 1', '10-You-are-Awesome-144.jpg', '10-You-are-Awesome-432.jpg', 1, 0, 0, sysdate, 1)
/