CREATE INDEX SSI_CONTEST_ACT_CONTEST_FK_IDX ON SSI_CONTEST_ACTIVITY (SSI_CONTEST_ID)
/
CREATE INDEX SSI_CONTEST_APP_CONTEST_FK_IDX ON SSI_CONTEST_APPROVER (SSI_CONTEST_ID)
/
CREATE INDEX SSI_CONTEST_APPROV_USER_FK_IDX ON SSI_CONTEST_APPROVER (USER_ID)
/
CREATE INDEX SSI_CONTEST_FK_IDX ON SSI_CONTEST_ATN (SSI_CONTEST_ID)
/
CREATE INDEX CONTEST_FIELD_CONTEST_FK_IDX ON SSI_CONTEST_CLAIM_FIELD (SSI_CONTEST_ID)
/
CREATE INDEX CONTEST_FIELD_STEP_ELEM_FK_IDX ON SSI_CONTEST_CLAIM_FIELD (SSI_CLAIM_FORM_STEP_ELEMENT_ID)
/
CREATE INDEX SSI_CONTEST_DOC_CONTEST_FK_IDX ON SSI_CONTEST_DOCUMENT (SSI_CONTEST_ID)
/
CREATE INDEX SSI_CONTEST_LVL_CONTEST_FK_IDX ON SSI_CONTEST_LEVEL (SSI_CONTEST_ID)
/
CREATE INDEX SSI_CONTEST_LVL_BA_RULE_FK_IDX ON SSI_CONTEST_LEVEL (BADGE_RULE_ID)
/
CREATE INDEX SSI_CONTEST_MGR_CONTEST_FK_IDX ON SSI_CONTEST_MANAGER (SSI_CONTEST_ID)
/
CREATE INDEX SSI_CONTEST_MANAGE_USER_FK_IDX ON SSI_CONTEST_MANAGER (USER_ID)
/
CREATE INDEX SSI_CONTEST_PAX_CONTEST_FK_IDX ON SSI_CONTEST_PARTICIPANT (SSI_CONTEST_ID)
/
CREATE INDEX SSI_CONTEST_PAX_USER_FK_IDX ON SSI_CONTEST_PARTICIPANT (USER_ID)
/
CREATE INDEX SSI_CONTEST_PAX_CLAIM_FK_IDX ON SSI_CONTEST_PAX_CLAIM_FIELD (SSI_CONTEST_PAX_CLAIM_ID)
/
CREATE INDEX SSI_CONTEST_CLAIM_FIELD_FK_IDX ON SSI_CONTEST_PAX_CLAIM_FIELD (SSI_CONTEST_CLAIM_FIELD_ID)
/
CREATE INDEX SSI_CONTEST_CLAIM_FK_IDX ON SSI_CONTEST_PAX_CLAIM (SSI_CONTEST_ID)
/
CREATE INDEX SSI_CONTEST_CLAIM_SUBMI_FK_IDX ON SSI_CONTEST_PAX_CLAIM (SUBMITTER_ID)
/
CREATE INDEX SSI_CONTEST_CLAIM_APPRO_FK_IDX ON SSI_CONTEST_PAX_CLAIM (APPROVER_ID)
/
CREATE INDEX PARTICIPANT_FK_IDX ON SSI_CONTEST_PAX_PAYOUT (USER_ID)
/
CREATE INDEX SSI_CONTEST_PAX_BA_RULE_FK_IDX ON SSI_CONTEST_PAX_PAYOUT (BADGE_RULE_ID)
/
CREATE INDEX FK_CONTEST_PROGRESS_IDX ON SSI_CONTEST_PAX_PROGRESS (SSI_CONTEST_ACTIVITY_ID)
/
CREATE INDEX SSI_PAX_STACK_RANK_CONT_FK_IDX ON SSI_CONTEST_PAX_STACK_RANK (SSI_CONTEST_ID)
/
CREATE INDEX SSI_PAX_STACK_RANK_USER_FK_IDX ON SSI_CONTEST_PAX_STACK_RANK (USER_ID)
/
CREATE INDEX SSI_CONTEST_PAX_ACTIVIT_FK_IDX ON SSI_CONTEST_PAX_STACK_RANK (SSI_CONTEST_ACTIVITY_ID)
/
CREATE INDEX SSI_CONTEST_SR_PAY_CNST_FK_IDX ON SSI_CONTEST_SR_PAYOUT (SSI_CONTEST_ID)
/
CREATE INDEX SSI_CONTEST_SR_BAD_RULE_FK_IDX ON SSI_CONTEST_SR_PAYOUT (BADGE_RULE_ID)
/
CREATE INDEX SSI_CONTEST_PROMOTION_FK_IDX ON SSI_CONTEST (PROMOTION_ID)
/
CREATE INDEX SSI_CONTEST_BADGE_RULE_FK_IDX ON SSI_CONTEST (BADGE_RULE_ID)
/
CREATE INDEX SSI_CONTEST_OWNER_FK_IDX ON SSI_CONTEST (CONTEST_OWNER_ID)
/

