INSERT INTO MESSAGE (MESSAGE_ID, MESSAGE_NAME, CM_ASSET_CODE, MODULE_CODE, MESSAGE_TYPE_CODE, STATUS_CODE, CREATED_BY, DATE_CREATED, VERSION)
VALUES
(MESSAGE_PK_SQ.nextVal, 'Opt Out Of Awards Notify Pax', 'message_data.message.10000301', 'general', 'general', 'act', 0, sysdate, 0)
/
INSERT INTO MESSAGE (MESSAGE_ID, MESSAGE_NAME, CM_ASSET_CODE, MODULE_CODE, MESSAGE_TYPE_CODE, STATUS_CODE, CREATED_BY, DATE_CREATED, VERSION)
VALUES
(MESSAGE_PK_SQ.nextVal, 'Opt Out Of Awards Notify Manager', 'message_data.message.10000302', 'general', 'general', 'act', 0, sysdate, 0)
/