DROP SEQUENCE RPT_RECOG_BEHAVIOR_SUMM_PK_SQ
/
DROP SEQUENCE PRD_CLAIM_IMP_PRD_RECORD_PK_SQ
/
DROP SEQUENCE RPT_Q_ANALYSIS_SQ_PK
/
DROP SEQUENCE RPT_QUIZ_ACTIVITY_SUMMRY_SQ_PK
/
DROP SEQUENCE PARTICIPANT_AUDIENCE_PK_SQ
/
DROP SEQUENCE PARTICIPANT_EMPLOYER_PK_SQ
/
DROP SEQUENCE MODULE_APP_PK_SQ
/