DROP TABLE challengepoint_award CASCADE CONSTRAINTS
/
DROP TABLE challengepoint_progress CASCADE CONSTRAINTS
/
DROP TABLE promo_challengepoint CASCADE CONSTRAINTS
/
DROP TABLE RPT_CP_SELECTION_SUMMARY CASCADE CONSTRAINTS
/
DROP TABLE RPT_CP_PRODUCTION CASCADE CONSTRAINTS
/
DROP SEQUENCE challengepoint_award_pk_sq
/
DROP SEQUENCE challengepoint_progress_pk_sq
/
DROP SEQUENCE RPT_CP_SELECTION_SUMMARY_SQ
/
DROP SEQUENCE RPT_CP_PRODUCTION_SQ
/
