DROP TABLE promo_survey CASCADE CONSTRAINTS
/
DROP SEQUENCE RPT_SURVEY_DETAIL_SEQ
/
DROP TABLE RPT_SURVEY_DETAIL
/
DROP SEQUENCE RPT_SURVEY_RESPONSE_DETAIL_SEQ
/
DROP TABLE RPT_SURVEY_RESPONSE_DETAIL
/
DROP SEQUENCE RPT_SURVEY_RESPONSE_SUMMARY_SQ
/
DROP TABLE RPT_SURVEY_RESPONSE_SUMMARY
/
DROP SEQUENCE RPT_SURVEY_SUMMARY_SQ
/
DROP TABLE RPT_SURVEY_SUMMARY
/
DROP SEQUENCE rpt_survey_openend_resp_seq
/
DROP TABLE rpt_survey_openend_response
/
DROP TABLE RPT_SURVEY_MINIMUM_RESPONSE
/

