--tables
DROP TABLE LEADERBOARD CASCADE CONSTRAINTS
/
DROP TABLE LEADERBOARD_PARTICIPANT CASCADE CONSTRAINTS
/
DROP TABLE LEADERBOARD_PAX_ACTIVITY CASCADE CONSTRAINTS
/
DROP TABLE STAGE_LEADERBOARD_LOAD CASCADE CONSTRAINTS
/

--sequences
DROP SEQUENCE LEADERBOARD_PK_SQ 
/
DROP SEQUENCE LEADERBOARD_PARTICIPANT_PK_SQ 
/
DROP SEQUENCE LEADERBOARD_PAX_ACTIVITY_PK_SQ
/
