DROP TABLE odd_cast_card CASCADE CONSTRAINTS
/
DROP TABLE ecard_locale CASCADE CONSTRAINTS
/
DROP TABLE ecard CASCADE CONSTRAINTS
/
DROP TABLE card CASCADE CONSTRAINTS
/
DROP TABLE odd_cast_category CASCADE CONSTRAINTS
/
DROP TABLE promo_behavior CASCADE CONSTRAINTS
/
DROP TABLE promo_card cascade constraints
/

-- SEQUENCES
DROP SEQUENCE promo_card_pk_sq
/
DROP SEQUENCE odd_cast_category_pk_sq
/
DROP SEQUENCE card_pk_sq
/
