<%@ include file="/include/taglib.jspf" %>
<%@ page import="com.biperf.core.ui.utils.RequestUtils" %>
<%@ page import="java.time.LocalDateTime"%>

<% pageContext.setAttribute("year",LocalDateTime.now().getYear()); %>

<DIV class="footer">
	<table border="0" cellpadding="0" cellspacing="0" width="100%">
		<tr>
			<td class="footerlinks" align="center">
			<br>
			<a href="<%=RequestUtils.getBaseURI(request)%>/privacy.do" class="footerlinks">
					<cms:contentText key="PRIVACY_POLICY" code="system.general"/>
				</a>			
				 |
				<a href="<%=RequestUtils.getBaseURI(request)%>/contactUs.do?method=view" class="footerlinks">
					<cms:contentText key="CONTACT_US" code="system.general"/>					
				</a>
			</td>
		</tr>
		<tr class="footerlinks" align="center">
			<td>
				&copy&nbsp;<cms:contentTemplateText key="COPYRIGHT_TEXT" code="system.general" args="${year}" delimiter=","/>&nbsp;&reg;
			</td>
		</tr>
	</table>
</DIV>

<script type="text/javascript">
	var requestBaseURI = '<%=RequestUtils.getBaseURI(request)%>';

    <%-- TODO: make this only run when environment mode is dev--%>
    for (i = 0; i < document.forms.length; i++) {
      formId = document.forms[i].id;
      if (formId == null || formId == "")
      {
        /* Ignore forms generated by Opinio surveys, which are shown in Instant Poll widgets. */
        formName = document.forms[i].getAttribute("name");
        if (formName.substring(0, 8) != "pollForm" )
        {
          alert("BEACON DEVELOPER WARNING: an html:form tag (or regular html form tag) should have its id set " +
          "to the word contentForm to distinguish it from the quicksearch form, and so that commonFunctions.js works correctly.");
        }
      }
    }
</script>
