import java.util.List

/**
 * This file is used by the DatabaseScriptTaskPlugin to convert the database versions.
 * It's a groovy script that gets applied to the project, so the Gradle script syntax is available.
 * Explanation of the format:
 * <pre>
 * name: [
 *   task: true|false                           // True means create a task, false means it'll just be an internal method>
 *   description: "describe task"               // Only needed when task is true. Description for the task
 *   group: project.ext.databaseConvertGroup    // "database-convert". Only needed when task is true. Groups the task based on the functionality
 *   condition: {closure}                       // Optional. If defined, the closure's return value determines if the method runs or not.
 *                                                 Uses groovy-truth. If false, the actions will not happen.
 *   actions: [
 *     dbScript("path/to/script.sql"),          // Execute a SQL script
 *     dbScript("script", "extra_task"),        // Execute a SQL script. Also adds this action to a separate task. May list multiple extra tasks.
 *     dbJava("script"),                        // Same as dbScript, but intended to compile Java source on the database
 *     dbSql("select sysdate from dual")        // Execute a SQL statement
 *     dbSublist("name"),                       // Calls an internal method. So you can run the actions of a different list.
 *     dbClosure({closure})                     // Executes an arbitrary closure.
 *   ]
 * ]
 * </pre>
 */

String dbPath = config.dbResourceDir

project.ext.dbTaskConfigList << [
  // "Utility method" for confirmation before each convert task
  convert_confirmation: [
    task: false,
    actions: [
      dbClosure({
        if(!promptForConfirmation("Are you sure you want to convert the $db.environment database?"))
        {
          throw new RuntimeException("Database convert cancelled by user")
        }
      })
    ]
  ]
]

project.ext.dbTaskConfigList << [

  convert_50_to_51: [
    task: true,
    description: "Converts database from 5.0 to 5.1 Release",
    group: project.ext.databaseConvertGroup,
    actions: [
      // Confirmation
      dbSublist("convert_confirmation"),
      // Schema changes
      dbScript("$dbPath/convert/5.1.RELEASE/20130426_add_index_core_usernode_tbl.sql"),
      dbScript("$dbPath/convert/5.1.RELEASE/20130426_alter_core_budget_tbl.sql"),
      dbScript("$dbPath/convert/5.1.RELEASE/20130426_alter_core_comm_log_tbl.sql"),
      dbScript("$dbPath/convert/5.1.RELEASE/20130426_alter_core_message_tbl.sql"),
      dbScript("$dbPath/convert/5.1.RELEASE/20130426_alter_core_participant_tbl.sql"),
      dbScript("$dbPath/convert/5.1.RELEASE/20130426_alter_core_promotion_tbl.sql"),
      dbScript("$dbPath/convert/5.1.RELEASE/20130426_alter_core_proxy_tbl.sql"),
      dbScript("$dbPath/convert/5.1.RELEASE/20130426_alter_core_rpt_badge_detail_tbl.sql"),
      dbScript("$dbPath/convert/5.1.RELEASE/20130426_alter_core_rpt_badge_summary_tbl.sql"),
      dbScript("$dbPath/convert/5.1.RELEASE/20130426_alter_core_stage_pax_import_record_tbl.sql"),
      dbScript("$dbPath/convert/5.1.RELEASE/20130426_alter_lb_leaderboard_participant_tbl.sql"),
      dbScript("$dbPath/convert/5.1.RELEASE/20130426_alter_rec_rpt_award_earnings_tbl.sql"),
      dbScript("$dbPath/convert/5.1.RELEASE/20130426_alter_rec_rpt_award_item_activity_tbl.sql"),
      dbScript("$dbPath/convert/5.1.RELEASE/20130426_create_core_file_store_tbl.sql"),
      dbScript("$dbPath/convert/5.1.RELEASE/20130426_create_core_strongmail_user_tbl.sql"),
      dbScript("$dbPath/convert/5.1.RELEASE/20130607_create_table_rpt_hierarchy_rollup.sql"),
      dbScript("$dbPath/convert/5.1.RELEASE/20130426_insert_message_data.sql"),
      dbScript("$dbPath/convert/5.1.RELEASE/20130607_update_message_data.sql"),
      dbScript("$dbPath/convert/5.1.RELEASE/20130426_insert_node_type_data.sql"),
      dbScript("$dbPath/convert/5.1.RELEASE/20130429_delete_os_propertyset.sql"),
      dbScript("$dbPath/convert/5.1.RELEASE/20130429_insert_os_propertyset.sql"),
      dbScript("$dbPath/convert/5.1.RELEASE/20130429_update_os_propertyset.sql"),
      dbScript("$dbPath/convert/5.1.RELEASE/20130520_core_report_dashboard_alter.sql"),
      dbScript("$dbPath/convert/5.1.RELEASE/20130607_update_module_app_data.sql"),
      dbScript("$dbPath/convert/5.1.RELEASE/20130607_update_supplier_data.sql"),
      dbScript("$dbPath/convert/5.1.RELEASE/20130607_add_index_application_user_tbl.sql"),
      dbScript("$dbPath/convert/5.1.RELEASE/20130607_add_index_particiapnt_audience_tbl.sql"),
      dbScript("$dbPath/convert/5.1.RELEASE/20130607_add_index_user_characteristic_tbl.sql"),
      dbScript("$dbPath/convert/5.1.RELEASE/20130607_alter_rpt_nomination_detail_tbl.sql"),
      dbScript("$dbPath/convert/5.1.RELEASE/20130614_alter_rpt_award_earnings_tbl.sql"),
      dbScript("$dbPath/convert/5.1.RELEASE/20130614_update_report_tables.sql"),
      // PL/SQL Changes
      dbScript("$dbPath/plsql/fnc_create_array.sql"),
      dbScript("$dbPath/plsql/fnc_random_password.sql"),
      dbScript("$dbPath/plsql/pkg_badge_verify_import.sql"),
      dbScript("$dbPath/plsql/pkg_build_audience.sql"),
      dbScript("$dbPath/plsql/pkg_extracts.sql"),
      dbScript("$dbPath/plsql/pkg_hierarchy_verify_import.sql"),
      dbScript("$dbPath/plsql/pkg_participant_verify_import.sql"),
      dbScript("$dbPath/plsql/pkg_populate_promo_elig.sql"),
      dbScript("$dbPath/plsql/pkg_quiz_analysis_reports.sql"),
      dbScript("$dbPath/plsql/pkg_quiz_reports.sql"),
      dbScript("$dbPath/plsql/pkg_report_awardmedia.sql"),
      dbScript("$dbPath/plsql/pkg_report_badge.sql"),
      dbScript("$dbPath/plsql/pkg_report_budget.sql"),
      dbScript("$dbPath/plsql/pkg_report_common.sql"),
      dbScript("$dbPath/plsql/pkg_report_enrollment.sql"),
      dbScript("$dbPath/plsql/pkg_report_login_activity.sql"),
      dbScript("$dbPath/plsql/pkg_report_nomination.sql"),
      dbScript("$dbPath/plsql/pkg_report_product_claim.sql"),
      dbScript("$dbPath/plsql/pkg_report_recognition.sql"),
      dbScript("$dbPath/plsql/prc_report_refresh.sql"),
      dbScript("$dbPath/plsql/prc_rpt_qcard_refresh.sql"),
      dbScript("$dbPath/plsql/prc_stage_award_level_load.sql"),
      dbScript("$dbPath/plsql/prc_stg_pax_record_insert.sql"),
      dbScript("$dbPath/plsql/prc_welcome_email_prep.sql")
    ]
  ],

  convert_51_to_52: [
    task: true,
    description: "Converts database from 5.1 to 5.2 Release",
    group: project.ext.databaseConvertGroup,
    actions: [
      // Confirmation
      dbSublist("convert_confirmation"),
      // Schema changes
      dbScript("$dbPath/convert/5.2.RELEASE/20131023_reports_cleanup.sql"),
      dbScript("$dbPath/convert/5.2.RELEASE/20131003_drop_goalquest.sql"),
      dbScript("$dbPath/convert/5.2.RELEASE/20130930_alter_core_node.sql"),
      dbScript("$dbPath/convert/5.2.RELEASE/20130930_alter_core_promotion.sql"),
      dbScript("$dbPath/convert/5.2.RELEASE/20130930_alter_core_promo_notification.sql"),
      dbScript("$dbPath/convert/5.2.RELEASE/201310030844_create_GQ_stage_gq_base_data_import.tbl"),
      dbScript("$dbPath/convert/5.2.RELEASE/201310030844_create_GQ_stage_gq_goal_data_import.tbl"),
      dbScript("$dbPath/convert/5.2.RELEASE/201310030844_create_GQ_stage_gq_progress_data_import.tbl"),
      dbScript("$dbPath/convert/5.2.RELEASE/201310030844_create_GQ_stage_gq_vin_nbr_import.tbl"),
      dbScript("$dbPath/convert/5.2.RELEASE/20130930_alter_core_badge.sql"),
      dbScript("$dbPath/convert/5.2.RELEASE/20130930_alter_core_badge_rule.sql"),
      dbScript("$dbPath/convert/5.2.RELEASE/20130930_alter_core_strongmail_user.sql"),
      dbScript("$dbPath/convert/5.2.RELEASE/20130930_create_core_forum_topic.sql"),
      dbScript("$dbPath/convert/5.2.RELEASE/20130930_create_core_forum_topic_audience.sql"),
      dbScript("$dbPath/convert/5.2.RELEASE/20130930_create_core_forum_discussion.sql"),
      dbScript("$dbPath/convert/5.2.RELEASE/20130930_create_core_forum_discussion_like.sql"),
      dbScript("$dbPath/convert/5.2.RELEASE/20130930_create_core_awardgenerator.sql"),
      dbScript("$dbPath/convert/5.2.RELEASE/20130930_create_core_awardgen_award.sql"),
      dbScript("$dbPath/convert/5.2.RELEASE/20130930_create_core_awardgen_batch.sql"),
      dbScript("$dbPath/convert/5.2.RELEASE/20130930_create_core_awardgen_participant.sql"),
      dbScript("$dbPath/convert/5.2.RELEASE/20130930_create_core_awardgen_manager.sql"),
      dbScript("$dbPath/convert/5.2.RELEASE/20130930_alter_core_report_chart.sql"),
      dbScript("$dbPath/convert/5.2.RELEASE/20130930_alter_core_rpt_pax_promo_eligibility.sql"),
      dbScript("$dbPath/convert/5.2.RELEASE/20130930_create_core_rpt_pax_promo_elig_stage.sql"),
      dbScript("$dbPath/convert/5.2.RELEASE/20130930_add_index_rpt_awardmedia_summary.sql"),
      dbScript("$dbPath/convert/5.2.RELEASE/20130930_create_extract_characteristic_cms.sql"),
      dbScript("$dbPath/convert/5.2.RELEASE/201310030844_create_GQ_rpt_goal_selection_detail.tbl"),
      dbScript("$dbPath/convert/5.2.RELEASE/201310030849_create_cp_rpt_cp_selection_detail.tbl"),
      dbScript("$dbPath/convert/5.2.RELEASE/201310030849_create_cp_rpt_cp_manager_override.tbl"),
      dbScript("$dbPath/convert/5.2.RELEASE/201310030844_create_gq_rpt_goal_manager_override.tbl"),
      dbScript("$dbPath/convert/5.2.RELEASE/201310030849_create_cp_stage_cp_base_data_import.tbl"),
      dbScript("$dbPath/convert/5.2.RELEASE/201310030849_create_cp_stage_cp_data_import.tbl"),
      dbScript("$dbPath/convert/5.2.RELEASE/201310030849_create_cp_stage_cp_progress_data_import.tbl"),
      dbScript("$dbPath/convert/5.2.RELEASE/20130930_alter_core_rpt_claim_detail.sql"),
      dbScript("$dbPath/convert/5.2.RELEASE/20130930_alter_rec_rpt_recognition_summary.sql"),
      dbScript("$dbPath/convert/5.2.RELEASE/20131029_set_sequences.sql"),
      dbScript("$dbPath/convert/5.2.RELEASE/20131003_update_insert_os_property_set.sql"),
      dbScript("$dbPath/convert/5.2.RELEASE/20131003_update_cms_asset_pax_or_admin_P.sql"),
      dbScript("$dbPath/convert/5.2.RELEASE/20131003_update_insert_message.sql"),
      dbScript("$dbPath/convert/5.2.RELEASE/20131003_update_insert_module_app.sql"),
      dbScript("$dbPath/convert/5.2.RELEASE/20131003_update_filter_module_app.sql"),
      dbScript("$dbPath/convert/5.2.RELEASE/20131003_update_insert_rec_ecard.sql"),
      dbScript("$dbPath/convert/5.2.RELEASE/20131003_update_insert_report.sql"),
      dbScript("$dbPath/convert/5.2.RELEASE/20131007_update_module_app.sql"),
      dbScript("$dbPath/convert/5.2.RELEASE/20131008_update_generic_banners_cm.sql"),
      dbScript("$dbPath/convert/5.2.RELEASE/20131016_update_promo_notification.sql"),
      dbScript("$dbPath/convert/5.2.RELEASE/20131101_update_tile_mapping_picklist_cm.sql"),
      dbScript("$dbPath/convert/5.2.RELEASE/20131001_misc_cleanup.sql"),
      dbScript("$dbPath/convert/5.2.RELEASE/201310030844_create_GQ_rpt_goal_selection_summary.tbl"),
      dbScript("$dbPath/convert/5.2.RELEASE/201310030844_create_gq_promo_goalquest.tbl"),
      dbScript("$dbPath/convert/5.2.RELEASE/201310030844_create_gq_goalquest_goallevel.tbl"),
      dbScript("$dbPath/convert/5.2.RELEASE/201310030844_create_gq_paxgoal.tbl"),
      dbScript("$dbPath/convert/5.2.RELEASE/201310030844_create_gq_goalquest_participant_activity.tbl"),
      dbScript("$dbPath/convert/5.2.RELEASE/201310030844_create_gq_participant_partner.tbl"),
      dbScript("$dbPath/convert/5.2.RELEASE/201310030844_create_GQ_rpt_goal_ROI.tbl"),
      dbScript("$dbPath/convert/5.2.RELEASE/201310030844_create_gq_rpt_goal_partner.tbl"),
      dbScript("$dbPath/convert/5.2.RELEASE/201310030912_sm_gq_participant_progress_updated_email_vw.sql"),
      dbScript("$dbPath/convert/5.2.RELEASE/201310030912_sm_gq_partner_goal_achieved_email_vw.sql"),
      dbScript("$dbPath/convert/5.2.RELEASE/201310030912_sm_gq_partner_goal_achieved_no_payout_email_vw.sql"),
      dbScript("$dbPath/convert/5.2.RELEASE/201310030912_sm_gq_partner_not_achieved_email_vw.sql"),
      dbScript("$dbPath/convert/5.2.RELEASE/201310030912_sm_gq_partner_progress_updated_email_vw.sql"),
      dbScript("$dbPath/convert/5.2.RELEASE/201310030912_sm_gq_participant_goal_achieved_email_vw.sql"),
      dbScript("$dbPath/convert/5.2.RELEASE/201310030912_sm_gq_participant_goal_not_achieved_email_vw.sql"),
      dbScript("$dbPath/convert/5.2.RELEASE/201310030912_sm_gq_participant_goal_not_selected_email_vw.sql"),
      dbScript("$dbPath/convert/5.2.RELEASE/201310030912_sm_gq_promo_launch_notification_email_vw.sql"),
      dbScript("$dbPath/convert/5.2.RELEASE/201310030912_sm_cp_interim_payout_email_vw.sql"),
      dbScript("$dbPath/convert/5.2.RELEASE/201310030912_sm_cp_participant_achieved_vw.sql"),
      dbScript("$dbPath/convert/5.2.RELEASE/201310030912_sm_cp_participant_not_achieved_vw.sql"),
      dbScript("$dbPath/convert/5.2.RELEASE/201310030912_sm_cp_progress_updated_vw.sql"),
      dbScript("$dbPath/convert/5.2.RELEASE/201310030912_sm_cp_promo_launch_notification_email_vw.sql"),
      dbScript("$dbPath/convert/5.2.RELEASE/201310030912_sm_cp_welcome_login_and_password_vw.sql"),
      dbScript("$dbPath/convert/5.2.RELEASE/201310030912_sm_cp_goal_not_selected_email_vw.sql"),
      dbScript("$dbPath/convert/5.2.RELEASE/201310030849_create_cp_promo_challengepoint.tbl"),
      dbScript("$dbPath/convert/5.2.RELEASE/201310030849_create_cp_challengepoint_award.tbl"),
      dbScript("$dbPath/convert/5.2.RELEASE/201310030849_create_cp_challengepoint_progress.tbl"),
      dbScript("$dbPath/convert/5.2.RELEASE/201310030849_create_cp_rpt_cp_selection_summary.tbl"),
      dbScript("$dbPath/convert/5.2.RELEASE/201310030849_create_cp_rpt_cp_production.tbl"),
      dbScript("$dbPath/convert/5.2.RELEASE/201310030912_sm_cp_partner_goal_achieved_email_vw.sql"),
      dbScript("$dbPath/convert/5.2.RELEASE/201310030912_sm_cp_partner_goal_achieved_no_payout_email_vw.sql"),
      dbScript("$dbPath/convert/5.2.RELEASE/201310030912_sm_cp_partner_not_achieved_email_vw.sql"),
      dbScript("$dbPath/convert/5.2.RELEASE/201310030912_sm_cp_partner_progress_updated_email_vw.sql"),
      dbScript("$dbPath/convert/5.2.RELEASE/201309280245_create_survey.sql"),
      dbScript("$dbPath/convert/5.2.RELEASE/201309280246_create_survey_question.sql"),
      dbScript("$dbPath/convert/5.2.RELEASE/201309280247_create_survey_question_response.sql"),
      dbScript("$dbPath/convert/5.2.RELEASE/201309280232_create_promo_goalquest_survey.sql"),
      dbScript("$dbPath/convert/5.2.RELEASE/201309280243_create_participant_survey.sql"),
      dbScript("$dbPath/convert/5.2.RELEASE/201309280242_create_participant_survey_response.sql"),
      dbScript("$dbPath/convert/5.2.RELEASE/20130930_alter_rec_rpt_award_earnings.sql"),
      dbScript("$dbPath/convert/5.2.RELEASE/20130930_alter_rec_tmp_award_activity_rpt.sql"),
      dbScript("$dbPath/convert/5.2.RELEASE/20130930_alter_rec_tmp_award_item_selection_rpt.sql"),
      dbScript("$dbPath/convert/5.2.RELEASE/20130930_alter_rpt_award_item_selection.sql"),
      dbScript("$dbPath/convert/5.2.RELEASE/201309280253_alter_merch_order.sql"),
      dbScript("$dbPath/convert/5.2.RELEASE/20130930_alter_core_merch_order.sql"),
      dbScript("$dbPath/convert/5.2.RELEASE/20130930_create_diy_quiz.sql"),
      dbScript("$dbPath/convert/5.2.RELEASE/20130930_create_diy_quiz_participant.sql"),
      dbScript("$dbPath/convert/5.2.RELEASE/20130930_alter_quiz_claim.sql"),
      dbScript("$dbPath/convert/5.2.RELEASE/20130930_alter_quiz_promo_quiz.sql"),
      dbScript("$dbPath/convert/5.2.RELEASE/20131016_update_promo_quiz.sql"),
      // PL/SQL Changes
      dbScript("$dbPath/plsql/pkg_quiz_reports.sql"),
      dbScript("$dbPath/plsql/prc_remove_all_reporting_data.sql"),
      dbScript("$dbPath/plsql/fnc_check_promo_eligibility.sql"),
      dbScript("$dbPath/plsql/fnc_get_system_var_boolean.sql"),
      dbScript("$dbPath/plsql/fnc_is_date.sql"),
      dbScript("$dbPath/plsql/fnc_is_number.sql"),
      dbScript("$dbPath/plsql/fnc_get_osp_bool.sql"),
      dbScript("$dbPath/plsql/prc_hierarchy_load.sql"),
      dbScript("$dbPath/plsql/pkg_report_common.sql"),
      dbScript("$dbPath/plsql/pkg_report_enrollment.sql"),
      dbScript("$dbPath/plsql/pkg_report_awardmedia.sql"),
      dbScript("$dbPath/plsql/pkg_populate_promo_elig.sql"),
      dbScript("$dbPath/plsql/pkg_report_recognition.sql"),
      dbScript("$dbPath/plsql/pkg_bulk_pax_stage.sql"),
      dbScript("$dbPath/plsql/pkg_participant_verify_import.sql"),
      dbScript("$dbPath/plsql/prc_report_refresh.sql"),
      dbScript("$dbPath/plsql/pkg_badge_verify_import.sql"),
      dbScript("$dbPath/plsql/prc_rpt_promo_node_inactive.sql"),
      dbScript("$dbPath/plsql/prc_report_promo_node_activity.sql"),
      dbScript("$dbPath/plsql/prc_rpt_qcard_refresh.sql"),
      dbScript("$dbPath/plsql/pkg_report_characteristic.sql"),
      dbScript("$dbPath/plsql/fnc_get_badge_count_by_user.sql"),
      dbScript("$dbPath/plsql/pkg_extracts.sql"),
      dbScript("$dbPath/plsql/fnc_get_badge_count_by_param.sql"),
      dbScript("$dbPath/plsql/fnc_random_password.sql"),
      dbScript("$dbPath/plsql/prc_welcome_email_prep.sql"),
      dbScript("$dbPath/plsql/pkg_report_client_reports.sql"),
      dbScript("$dbPath/plsql/pkg_report_goalquest.sql"),
      dbScript("$dbPath/plsql/prc_insert_stg_gq_base_data.sql"),
      dbScript("$dbPath/plsql/prc_insert_stg_gq_goal_data.sql"),
      dbScript("$dbPath/plsql/prc_insert_stg_gq_progress_dat.sql"),
      dbScript("$dbPath/plsql/prc_insert_stg_gq_vin_nbr.sql"),
      dbScript("$dbPath/plsql/prc_gq_base_data_load.sql"),
      dbScript("$dbPath/plsql/prc_gq_goal_data_load.sql"),
      dbScript("$dbPath/plsql/prc_gq_progress_data_load.sql"),
      dbScript("$dbPath/plsql/prc_gq_vin_nbr_import.sql"),
      dbScript("$dbPath/plsql/prc_rpt_repository_extract.sql"),
      dbScript("$dbPath/plsql/prc_insert_stg_cp_base_data.sql"),
      dbScript("$dbPath/plsql/prc_insert_stg_cp_data.sql"),
      dbScript("$dbPath/plsql/prc_insert_stg_cp_progress_dat.sql"),
      dbScript("$dbPath/plsql/prc_cp_base_data_load.sql"),
      dbScript("$dbPath/plsql/prc_cp_progress_data_load.sql"),
      dbScript("$dbPath/plsql/prc_cp_data_load.sql"),
      dbScript("$dbPath/plsql/pkg_report_challangepoint.sql"),
      dbScript("$dbPath/plsql/pkg_report_nomination.sql"),
      dbScript("$dbPath/plsql/pkg_report_claim.sql")
    ]
  ],

  convert_52_to_522: [
    task: true,
    description: "Converts database from 5.2 to 5.2.2 Release",
    group: project.ext.databaseConvertGroup,
    actions: [
      // Confirmation
      dbSublist("convert_confirmation"),
      // PL/SQL Changes
      dbScript("$dbPath/plsql/pkg_report_claim.sql"),
      dbScript("$dbPath/plsql/pkg_extracts.sql")
    ]
  ],

  convert_522_to_53: [
    task: true,
    description: "Converts database from 5.2.2 to 5.3 Release",
    group: project.ext.databaseConvertGroup,
    actions: [
      // Confirmation
      dbSublist("convert_confirmation"),
      // Schema changes
      dbScript("$dbPath/convert/5.3.RELEASE/201311010917_insert_system_variable_report_start_date.sql"),
      dbScript("$dbPath/convert/5.3.RELEASE/201312030700_machine_language_translation.sql"),
      dbScript("$dbPath/convert/5.3.RELEASE/201312121115_alter_badge_rule.sql"),
      dbScript("$dbPath/convert/5.3.RELEASE/201312121120_alter_activity.sql"),
      dbScript("$dbPath/convert/5.3.RELEASE/201312121131_alter_import_file.sql"),
      dbScript("$dbPath/convert/5.3.RELEASE/201312130411_alter_message_recipient_data.sql"),
      dbScript("$dbPath/convert/5.3.RELEASE/201312170745_alter_country.sql"),
      dbScript("$dbPath/convert/5.3.RELEASE/201312170745_drop_tables.sql"),
      dbScript("$dbPath/convert/5.3.RELEASE/201312261200_update_module_app_data.sql"),
      dbScript("$dbPath/convert/5.3.RELEASE/201312261700_drop_columns.sql"),
      dbScript("$dbPath/convert/5.3.RELEASE/201312261200_alter_os_property_set.sql"),
      dbScript("$dbPath/convert/5.3.RELEASE/201312261220_update_role_data.sql"),
      dbScript("$dbPath/convert/5.3.RELEASE/201312261240_update_message_data.sql"),
      dbScript("$dbPath/convert/5.3.RELEASE/201312271730_insert_chatter_os_property_set.sql"),
      dbScript("$dbPath/convert/5.3.RELEASE/201312271731_alter_audience_criteria.sql"),
      dbScript("$dbPath/convert/5.3.RELEASE/201312271755_alter_rpt_hierarchy.sql"),
      dbScript("$dbPath/convert/5.3.RELEASE/201312271755_alter_rpt_nomination_behavior.sql"),
      dbScript("$dbPath/convert/5.3.RELEASE/201312271800_alter_participant_survey.sql"),
      dbScript("$dbPath/convert/5.3.RELEASE/201312271805_alter_survey.sql"),
      dbScript("$dbPath/convert/5.3.RELEASE/201312271845_create_core_rpt_locale_date_pattern.tbl"),
      dbScript("$dbPath/convert/5.3.RELEASE/20140123_alter_claim.sql"),
      dbScript("$dbPath/convert/5.3.RELEASE/20140122_create_svy_promo_survey.sql"),
      dbScript("$dbPath/convert/5.3.RELEASE/201312271715_insert_survey_message.sql"),
      dbScript("$dbPath/convert/5.3.RELEASE/201312271730_insert_survey_report.sql"),
      dbScript("$dbPath/convert/5.3.RELEASE/201312271845_create_instant_poll.tbl"),
      dbScript("$dbPath/convert/5.3.RELEASE/201312271845_create_instant_poll_audience.tbl"),
      dbScript("$dbPath/convert/5.3.RELEASE/201312271845_create_svy_rpt.tbl"),
      dbScript("$dbPath/convert/5.3.RELEASE/201312261300_insert_instant_poll_module_app_data.sql"),
      dbScript("$dbPath/convert/5.3.RELEASE/20142101_alter_participant_survey.sql"),
      dbScript("$dbPath/convert/5.3.RELEASE/201312271800_alter_promo_product_claim.sql"),
      dbScript("$dbPath/convert/5.3.RELEASE/201312271700_drop_quiz_columns.sql"),
      dbScript("$dbPath/convert/5.3.RELEASE/201312261915_insert_throwdown_message.sql"),
      dbScript("$dbPath/convert/5.3.RELEASE/201312271323_insert_throwdown_module_app.sql"),
      dbScript("$dbPath/convert/5.3.RELEASE/201312271326_insert_throwdown_filter_module_app.sql"),
      dbScript("$dbPath/convert/5.3.RELEASE/201312271730_insert_throwdown_report.sql"),
      dbScript("$dbPath/convert/5.3.RELEASE/201312271845_create_td_division.tbl"),
      dbScript("$dbPath/convert/5.3.RELEASE/201312271845_create_td_division_audience.tbl"),
      dbScript("$dbPath/convert/5.3.RELEASE/201312271845_create_td_division_payout.tbl"),
      dbScript("$dbPath/convert/5.3.RELEASE/201312271845_create_td_round.tbl"),
      dbScript("$dbPath/convert/5.3.RELEASE/201312271845_create_td_match.tbl"),
      dbScript("$dbPath/convert/5.3.RELEASE/201312271845_create_td_team.tbl"),
      dbScript("$dbPath/convert/5.3.RELEASE/201312271845_create_td_matchteam_outcome.tbl"),
      dbScript("$dbPath/convert/5.3.RELEASE/201312271845_create_td_matchteam_outcome_progress.tbl"),
      dbScript("$dbPath/convert/5.3.RELEASE/201312271845_create_td_promo_throwdown.tbl"),
      dbScript("$dbPath/convert/5.3.RELEASE/201312271845_create_td_promo_stack_rank_payout_group.tbl"),
      dbScript("$dbPath/convert/5.3.RELEASE/201312271845_create_td_promo_stack_rank_payout.tbl"),
      dbScript("$dbPath/convert/5.3.RELEASE/201312271845_create_td_rpt_throwdown_activity.tbl"),
      dbScript("$dbPath/convert/5.3.RELEASE/201312271845_create_td_smacktalk_comment.tbl"),
      dbScript("$dbPath/convert/5.3.RELEASE/201312271845_create_td_smacktalk_like.tbl"),
      dbScript("$dbPath/convert/5.3.RELEASE/201312271845_create_td_stack_rank.tbl"),
      dbScript("$dbPath/convert/5.3.RELEASE/201312271845_create_td_stack_rank_node.tbl"),
      dbScript("$dbPath/convert/5.3.RELEASE/201312271845_create_td_stack_rank_participant.tbl"),
      dbScript("$dbPath/convert/5.3.RELEASE/201312271845_create_td_stage_td_progress_data_import.tbl"),
      dbScript("$dbPath/convert/5.3.RELEASE/201312271315_insert_throwdown_os_property_set.sql"),
      // PL/SQL Changes
      dbScript("$dbPath/plsql/pkg_report_throwdown.sql"),
      dbScript("$dbPath/plsql/prc_td_progress_data_load.sql"),
      dbScript("$dbPath/plsql/fnc_badge_eligibility.sql"),
      dbScript("$dbPath/plsql/fnc_cms_picklist_value.sql"),
      dbScript("$dbPath/plsql/pkg_badge_verify_import.sql"),
      dbScript("$dbPath/plsql/pkg_build_audience.sql"),
      dbScript("$dbPath/plsql/pkg_bulk_pax_stage.sql"),
      dbScript("$dbPath/plsql/pkg_extracts.sql"),
      dbScript("$dbPath/plsql/pkg_hierarchy_verify_import.sql"),
      dbScript("$dbPath/plsql/pkg_participant_verify_import.sql"),
      dbScript("$dbPath/plsql/pkg_populate_promo_elig.sql"),
      dbScript("$dbPath/plsql/pkg_report_awardmedia.sql"),
      dbScript("$dbPath/plsql/pkg_report_badge.sql"),
      dbScript("$dbPath/plsql/pkg_report_budget.sql"),
      dbScript("$dbPath/plsql/pkg_report_claim.sql"),
      dbScript("$dbPath/plsql/prc_delete_audience.sql"),
      dbScript("$dbPath/plsql/prc_hierarchy_load.sql"),
      dbScript("$dbPath/plsql/prc_report_refresh.sql"),
      dbScript("$dbPath/plsql/prc_rpt_repository_extract.sql"),
      dbScript("$dbPath/plsql/prc_stage_award_level_load.sql"),
      dbScript("$dbPath/plsql/pkg_report_client_reports.sql"),
      dbScript("$dbPath/plsql/prc_stg_award_record_insert.sql"),
      dbScript("$dbPath/plsql/pkg_report_recognition.sql"),
      dbScript("$dbPath/plsql/pkg_report_goalquest.sql"),
      dbScript("$dbPath/plsql/pkg_report_survey.sql"),
      dbScript("$dbPath/plsql/pkg_quiz_reports.sql"),
      dbScript("$dbPath/plsql/prc_quiz_load.sql")
    ]
  ],

  convert_53_to_532: [
    task: true,
    description: "Converts database from 5.3 to 5.3.2 Release",
    group: project.ext.databaseConvertGroup,
    actions: [
      // Confirmation
      dbSublist("convert_confirmation"),
      // Schema changes
      dbScript("$dbPath/convert/5.3.2.RELEASE/20140306_alter_survey_question.sql"),
      dbScript("$dbPath/convert/5.3.2.RELEASE/20140313_alter_rec_scheduled_recognition_tbl.sql"),
      // PL/SQL Changes
      dbScript("$dbPath/plsql/pkg_report_recognition.sql"),
      dbScript("$dbPath/plsql/pkg_report_survey.sql")
    ]
  ]
]

project.ext.dbTaskConfigList << [
  convert_533_to_534: [
    task: true,
    description: "Converts database from 5.3.3 to 5.3.4 Release",
    group: project.ext.databaseConvertGroup,
    actions: [
      // Confirmation
      dbSublist("convert_confirmation"),
      // Schema changes
      dbScript("$dbPath/schema/create_core_rpt_participant_employer.tbl"),
      dbScript("$dbPath/convert/5.3.4.RELEASE/20140625_release_5_3_3_to_5_3_4.sql"),
      dbScript("$dbPath/convert/5.3.4.RELEASE/20140628_public_recognition_alter.sql"),
      // PL/SQL Changes
      dbScript("$dbPath/plsql/pkg_quiz_analysis_reports.sql"),
      dbScript("$dbPath/plsql/pkg_quiz_reports.sql"),
      dbScript("$dbPath/plsql/pkg_report_awardmedia.sql"),
      dbScript("$dbPath/plsql/pkg_report_badge.sql"),
      dbScript("$dbPath/plsql/pkg_report_challangepoint.sql"),
      dbScript("$dbPath/plsql/pkg_report_characteristic.sql"),
      dbScript("$dbPath/plsql/pkg_report_claim.sql"),
      dbScript("$dbPath/plsql/pkg_report_common.sql"),
      dbScript("$dbPath/plsql/pkg_report_enrollment.sql"),
      dbScript("$dbPath/plsql/pkg_report_goalquest.sql"),
      dbScript("$dbPath/plsql/pkg_report_nomination.sql"),
      dbScript("$dbPath/plsql/pkg_report_product_claim.sql"),
      dbScript("$dbPath/plsql/pkg_report_recognition.sql"),
      dbScript("$dbPath/plsql/pkg_report_survey.sql"),
      dbScript("$dbPath/plsql/prc_rpt_qcard_refresh.sql"),
      dbScript("$dbPath/plsql/prc_rpt_repository_extract.sql"),
      dbScript("$dbPath/plsql/prc_report_refresh.sql"),
      dbScript("$dbPath/plsql/pkg_extracts.sql"),
      dbScript("$dbPath/plsql/prc_welcome_email_prep.sql"),
      dbScript("$dbPath/plsql/fnc_get_user_name.sql"),
      dbScript("$dbPath/plsql/pkg_participant_verify_import.sql"),
      dbScript("$dbPath/plsql/fnc_getsubcategory_id.sql"),
      dbScript("$dbPath/plsql/prc_stage_product_load.sql")

      // TODO cm import diff
      // db/convert/cmDiff_533_to_report_fixes.xml
      // db/convert/cmDiff_533_to_534.xml
    ]
  ],

  convert_534_to_5341: [
    task: true,
    description: "Converts database from 5.3.4 to 5.3.4.1 Release",
    group: project.ext.databaseConvertGroup,
    actions: [
      // Confirmation
      dbSublist("convert_confirmation"),
      // PL/SQL Changes
      dbScript("$dbPath/plsql/pkg_report_challangepoint.sql"),
      dbScript("$dbPath/plsql/pkg_report_goalquest.sql")
    ]
  ],

  convert_5342_to_54: [
    task: true,
    description: "Converts database from 5.3.4.2 to 5.4 Release",
    group: project.ext.databaseConvertGroup,
    actions: [
      // Confirmation
      dbSublist("convert_confirmation"),
      // Schema changes
      dbScript("$dbPath/schema/node_type_name.sql"),
      dbScript("$dbPath/convert/5.4.RELEASE/201409230615_alter_awardgen_award.sql"),
      dbScript("$dbPath/convert/5.4.RELEASE/201409230616_alter_awardgen.sql"),
      dbScript("$dbPath/convert/5.4.RELEASE/201409230617_alter_awardgen_participant.sql"),
      dbScript("$dbPath/convert/5.4.RELEASE/201409230720_alter_rpt_pax_promo_elig_stage.sql"),
      dbScript("$dbPath/convert/5.4.RELEASE/201409230726_alter_global_temp_characteristic_cms.sql"),
      dbScript("$dbPath/convert/5.4.RELEASE/201409230729_alter_module_app.sql"),
      dbScript("$dbPath/convert/5.4.RELEASE/201409230744_alter_stg_award_level_import.sql"),
      dbScript("$dbPath/convert/5.4.RELEASE/201409230759_update_country.sql"),
      dbScript("$dbPath/convert/5.4.RELEASE/201409230816_insert_update_filter_module_app.sql"),
      dbScript("$dbPath/convert/5.4.RELEASE/201409230833_insert_update_module_app.sql"),
      dbScript("$dbPath/convert/5.4.RELEASE/201409230605_alter_participant.sql"),
      dbScript("$dbPath/convert/5.4.RELEASE/201409230605_alter_application_user.sql"),
      dbScript("$dbPath/convert/5.4.RELEASE/201406041353_create_celebration_manager_message.sql"),
      dbScript("$dbPath/convert/5.4.RELEASE/201406051100_create_diy_communications.sql"),
      dbScript("$dbPath/convert/5.4.RELEASE/201406051115_alter_audience.sql"),
      dbScript("$dbPath/convert/5.4.RELEASE/201406051150_alter_participant_badge.sql"),
      dbScript("$dbPath/convert/5.4.RELEASE/201406051140_alter_badge.sql"),
      dbScript("$dbPath/convert/5.4.RELEASE/201406051205_alter_rpt_badge_detail.sql"),
      dbScript("$dbPath/convert/5.4.RELEASE/201406051348_drop_tables.sql"),
      dbScript("$dbPath/convert/5.4.RELEASE/201406051530_create_audience_role.sql"),
      dbScript("$dbPath/convert/5.4.RELEASE/201406051350_alter_import_file.sql"),
      dbScript("$dbPath/convert/5.4.RELEASE/201406051540_alter_promo_sweepstake_winners.sql"),
      dbScript("$dbPath/convert/5.4.RELEASE/201409230722_alter_stage_deposit_import_record.sql"),
      dbScript("$dbPath/convert/5.4.RELEASE/201402071230_alter_journal.sql"),
      dbScript("$dbPath/convert/5.4.RELEASE/201402061525_alter_os_property_set.sql"),
      dbScript("$dbPath/convert/5.4.RELEASE/201408261130_create_gtt_recog_report_count.tbl"),
      dbScript("$dbPath/convert/5.4.RELEASE/201408261130_create_rpt_promo_elig_counts.tbl"),
      dbScript("$dbPath/convert/5.4.RELEASE/201409111708_budget_table_redesign_1.sql"),
      dbScript("$dbPath/convert/5.4.RELEASE/201409261221_create_promo_budget_sweep_table.sql"),
      dbScript("$dbPath/convert/5.4.RELEASE/201409111716_budget_table_redesign_2.sql"),
      dbScript("$dbPath/convert/5.4.RELEASE/201406051525_insert_role.sql"),
      dbScript("$dbPath/convert/5.4.RELEASE/201406051550_update_os_propertyset.sql"),
      dbScript("$dbPath/convert/5.4.RELEASE/201406051600_insert_message.sql"),
      dbScript("$dbPath/convert/5.4.RELEASE/201406051605_update_report_chart.sql"),
      dbScript("$dbPath/convert/5.4.RELEASE/201407281232_insert_os_propertyset.sql"),
      dbScript("$dbPath/convert/5.4.RELEASE/201407281233_insert_ecard_locale.sql"),
      dbScript("$dbPath/convert/5.4.RELEASE/201409240708_update_delete_insert_report.sql"),
      dbScript("$dbPath/convert/5.4.RELEASE/201409240541_update_cms_asset_pax_or_admin_P.sql"),
      dbScript("$dbPath/data/common/insert_survey.sql"),
      dbScript("$dbPath/data/common/insert_survey_question.sql"),
      dbScript("$dbPath/data/common/insert_survey_question_response.sql"),
      dbScript("$dbPath/convert/5.4.RELEASE/20140925_report_indexes.sql"),
      dbScript("$dbPath/convert/5.4.RELEASE/201406051545_alter_promo_recognition.sql"),
      dbScript("$dbPath/convert/5.4.RELEASE/201406290605_rec_source_column.sql"),
      dbScript("$dbPath/convert/5.4.RELEASE/201409230740_alter_purl_recipient.sql"),
      dbScript("$dbPath/convert/5.4.RELEASE/201406290605_nom_source_column.sql"),
      dbScript("$dbPath/convert/5.4.RELEASE/201408261130_create_eng_promo_engagement_promotions.tbl"),
      dbScript("$dbPath/convert/5.4.RELEASE/201408261130_create_eng_promo_engagement.tbl"),
      dbScript("$dbPath/convert/5.4.RELEASE/201408261130_create_eng_engagement_log.tbl"),
      dbScript("$dbPath/convert/5.4.RELEASE/201408261130_create_eng_promo_engagement_rules.tbl"),
      dbScript("$dbPath/convert/5.4.RELEASE/201408261130_create_eng_promo_engagement_rules_audience.tbl"),
      dbScript("$dbPath/convert/5.4.RELEASE/201408261130_create_eng_engagement_score_summary.tbl"),
      dbScript("$dbPath/convert/5.4.RELEASE/201408261130_create_eng_engagement_score_detail.tbl"),
      dbScript("$dbPath/convert/5.4.RELEASE/201408261130_create_eng_engagement_behavior_summary.tbl"),
      dbScript("$dbPath/convert/5.4.RELEASE/201408261130_create_eng_engagement_chart.tbl"),
      dbScript("$dbPath/convert/5.4.RELEASE/201409081804_update_report_parameter.sql"),
      dbScript("$dbPath/convert/5.4.RELEASE/201409230748_alter_create_td_stack_rank_pax_index.sql"),
      // PL/SQL Changes
      dbScript("$dbPath/plsql/prc_promo_name_insert_cms.sql"),
      dbScript("$dbPath/plsql/prc_budget_convert_G54.sql"),
      dbScript("$dbPath/plsql/fnc_check_promo_aud.sql"),
      dbScript("$dbPath/plsql/fnc_badge_eligibility.sql"),
      dbScript("$dbPath/plsql/fnc_get_badge_count_by_user.sql"),
      dbScript("$dbPath/plsql/fnc_get_badge_date_count.sql"),
      dbScript("$dbPath/plsql/fnc_get_user_name.sql"),
      dbScript("$dbPath/plsql/fnc_java_get_date_time_pattern.sql"),
      dbScript("$dbPath/plsql/fnc_promo_budget_meter.sql"),
      dbScript("$dbPath/plsql/pkg_badge_verify_import.sql"),
      dbScript("$dbPath/plsql/pkg_build_audience.sql"),
      dbScript("$dbPath/plsql/pkg_bulk_pax_stage.sql"),
      dbScript("$dbPath/plsql/pkg_extracts.sql"),
      dbScript("$dbPath/plsql/pkg_hierarchy_verify_import.sql"),
      dbScript("$dbPath/plsql/pkg_participant_verify_import.sql"),
      dbScript("$dbPath/plsql/pkg_populate_promo_elig.sql"),
      dbScript("$dbPath/plsql/pkg_report_badge.sql"),
      dbScript("$dbPath/plsql/pkg_report_budget.sql"),
      dbScript("$dbPath/plsql/pkg_report_enrollment.sql"),
      dbScript("$dbPath/plsql/pkg_report_recognition.sql"),
      dbScript("$dbPath/plsql/prc_delete_audience.sql"),
      dbScript("$dbPath/plsql/prc_deposit_load.sql"),
      dbScript("$dbPath/plsql/prc_insert_stg_deposit.sql"),
      dbScript("$dbPath/plsql/prc_report_refresh.sql"),
      dbScript("$dbPath/plsql/pkg_query_awards_received.sql"),
      dbScript("$dbPath/plsql/pkg_query_badge_activity.sql"),
      dbScript("$dbPath/plsql/pkg_query_budget_balance.sql"),
      dbScript("$dbPath/plsql/pkg_query_challengepoint.sql"),
      dbScript("$dbPath/plsql/pkg_query_claims_activity.sql"),
      dbScript("$dbPath/plsql/pkg_query_enroll_reports.sql"),
      dbScript("$dbPath/plsql/pkg_query_goalquest.sql"),
      dbScript("$dbPath/plsql/pkg_query_individual_activity.sql"),
      dbScript("$dbPath/plsql/pkg_query_login_activity.sql"),
      dbScript("$dbPath/plsql/pkg_query_nomi_given.sql"),
      dbScript("$dbPath/plsql/pkg_query_nomi_receive.sql"),
      dbScript("$dbPath/plsql/pkg_query_plateau_item_select.sql"),
      dbScript("$dbPath/plsql/pkg_query_plateau_levels.sql"),
      dbScript("$dbPath/plsql/pkg_query_quiz_activity.sql"),
      dbScript("$dbPath/plsql/pkg_query_quiz_analysis.sql"),
      dbScript("$dbPath/plsql/pkg_query_recog_given.sql"),
      dbScript("$dbPath/plsql/pkg_query_recog_list_of_givers.sql"),
      dbScript("$dbPath/plsql/pkg_query_recog_purl_activity.sql"),
      dbScript("$dbPath/plsql/pkg_query_recog_received.sql"),
      dbScript("$dbPath/plsql/pkg_query_recog_recipients.sql"),
      dbScript("$dbPath/plsql/pkg_query_survey_reports.sql"),
      dbScript("$dbPath/plsql/pkg_query_throwdown_activity.sql"),
      dbScript("$dbPath/plsql/pkg_list_recognition_wall.sql"),
      dbScript("$dbPath/plsql/prc_stage_award_level_load.sql"),
      dbScript("$dbPath/plsql/prc_stg_award_record_insert.sql"),
      dbScript("$dbPath/plsql/pkg_report_challangepoint.sql"),
      dbScript("$dbPath/plsql/prc_rpt_repository_extract.sql"),
      dbScript("$dbPath/plsql/pkg_report_goalquest.sql"),
      dbScript("$dbPath/plsql/pkg_report_nomination.sql"),
      dbScript("$dbPath/plsql/pkg_engagement.sql"),
      dbScript("$dbPath/plsql/pkg_engagement_extract.sql"),
      dbScript("$dbPath/plsql/prc_engagement_manager_score.sql"),
      dbScript("$dbPath/plsql/prc_engagement_user_details.sql"),
      dbScript("$dbPath/plsql/prc_stage_product_load.sql"),
      dbScript("$dbPath/plsql/fnc_getsubcategory_id.sql"),
      dbScript("$dbPath/plsql/pkg_report_survey.sql"),
      dbScript("$dbPath/plsql/script_compile_all_objects.sql")
    ]
  ],

  convert_54_to_541: [
    task: true,
    description: "Converts database from 5.4 to 5.4.1 Release",
    group: project.ext.databaseConvertGroup,
    actions: [
      // Confirmation
      dbSublist("convert_confirmation"),
      // Schema changes
      dbScript("$dbPath/convert/5.4.1.RELEASE/20141215_alter_rec_rpt_recognition_summary.sql"),
      dbScript("$dbPath/convert/5.4.1.RELEASE/201412021829_alter_core_process_invocation_parameter.sql"),
      dbScript("$dbPath/convert/5.4.1.RELEASE/20141215_fix_message_cm_asset_code.sql"),
      dbScript("$dbPath/convert/5.4.1.RELEASE/201412021829_insert_module_app.sql"),
      dbScript("$dbPath/convert/5.4.1.RELEASE/201412021829_insert_os_propertyset.sql"),
      dbScript("$dbPath/convert/5.4.1.RELEASE/201412021829_insert_report.sql"),
      dbScript("$dbPath/G4toG5/Step2_G5/prc_set_sequences.sql"),
      dbScript("$dbPath/convert/5.4.1.RELEASE/201412021829_alter_promo_recognition.sql"),
      dbScript("$dbPath/convert/5.4.1.RELEASE/201412021829_alter_recognition_claim.sql"),
      dbScript("$dbPath/convert/5.4.1.RELEASE/201412021829_drop_challenge_point_views.sql"),
      dbScript("$dbPath/convert/5.4.1.RELEASE/201412021829_drop_goal_quest_views.sql"),
      dbScript("$dbPath/convert/5.4.1.RELEASE/201412021829_alter_promo_nomination.sql"),
      dbScript("$dbPath/convert/5.4.1.RELEASE/201412021829_alter_eng_engagement_chart.sql"),
      dbScript("$dbPath/convert/5.4.1.RELEASE/201412021829_create_eng_user_connected_to_from.sql"),
      dbScript("$dbPath/convert/5.4.1.RELEASE/201412021829_alter_eng_engagement_score_summary.sql"),
      // PL/SQL Changes
      dbScript("$dbPath/plsql/fnc_get_manager_id.sql"),
      dbScript("$dbPath/plsql/fnc_lock_control_audience.sql"),
      dbScript("$dbPath/plsql/pkg_budget_verify_import.sql"),
      dbScript("$dbPath/plsql/pkg_build_audience.sql"),
      dbScript("$dbPath/plsql/pkg_bulk_pax_stage.sql"),
      dbScript("$dbPath/plsql/pkg_engagement_extract.sql"),
      dbScript("$dbPath/plsql/pkg_engagement.sql"),
      dbScript("$dbPath/plsql/pkg_extracts.sql"),
      dbScript("$dbPath/plsql/pkg_list_recognition_wall.sql"),
      dbScript("$dbPath/plsql/pkg_participant_verify_import.sql"),
      dbScript("$dbPath/plsql/pkg_populate_promo_elig.sql"),
      dbScript("$dbPath/plsql/pkg_query_awards_received.sql"),
      dbScript("$dbPath/plsql/pkg_query_challengepoint.sql"),
      dbScript("$dbPath/plsql/pkg_query_claims_activity.sql"),
      dbScript("$dbPath/plsql/pkg_query_goalquest.sql"),
      dbScript("$dbPath/plsql/pkg_query_individual_activity.sql"),
      dbScript("$dbPath/plsql/pkg_query_nomi_given.sql"),
      dbScript("$dbPath/plsql/pkg_query_nomi_receive.sql"),
      dbScript("$dbPath/plsql/pkg_query_quiz_activity.sql"),
      dbScript("$dbPath/plsql/pkg_query_recog_given.sql"),
      dbScript("$dbPath/plsql/pkg_query_recog_list_of_givers.sql"),
      dbScript("$dbPath/plsql/pkg_query_recog_purl_activity.sql"),
      dbScript("$dbPath/plsql/pkg_query_recog_received.sql"),
      dbScript("$dbPath/plsql/pkg_query_recog_recipients.sql"),
      dbScript("$dbPath/plsql/pkg_report_recognition.sql"),
      dbScript("$dbPath/plsql/prc_budget_load.sql"),
      dbScript("$dbPath/plsql/pkg_hierarchy_verify_import.sql"),
      dbScript("$dbPath/plsql/prc_welcome_email_prep.sql"),
      dbScript("$dbPath/plsql/pkg_engagement_extract.sql"),
      dbScript("$dbPath/plsql/pkg_report_throwdown.sql"),
      dbScript("$dbPath/plsql/pkg_query_throwdown_activity.sql")
    ]
  ],

  convert_541_to_55: [
    task: true,
    description: "Converts database from 5.4.1 to 5.5 Release",
    group: project.ext.databaseConvertGroup,
    actions: [
      // Confirmation
      dbSublist("convert_confirmation"),
      // Schema changes
      dbScript("$dbPath/convert/5.5.RELEASE/20150304_alter_rpt_promo_elig_counts.sql"),
      dbScript("$dbPath/convert/5.5.RELEASE/20150304_alter_core_alert_message.sql"),
      dbScript("$dbPath/convert/5.5.RELEASE/20150304_alter_core_participant_badge.sql"),
      dbScript("$dbPath/convert/5.5.RELEASE/20150304_alter_core_process_invocation_parameter_value.sql"),
      dbScript("$dbPath/convert/5.5.RELEASE/20150304_create_core_currency.sql"),
      dbScript("$dbPath/convert/5.5.RELEASE/20150304_create_gtt_node_and_below.sql"),
      dbScript("$dbPath/convert/5.5.RELEASE/20150304_create_core_gtt_ex_pax_audience.sql"),
      dbScript("$dbPath/convert/5.5.RELEASE/20150304_alter_core_email_address.sql"),
      dbScript("$dbPath/convert/5.5.RELEASE/20150304_insert_currency.sql"),
      dbScript("$dbPath/convert/5.5.RELEASE/20150304_update_os_propertyset.sql"),
      dbScript("$dbPath/convert/5.5.RELEASE/20150304_update_report.sql"),
      dbScript("$dbPath/convert/5.5.RELEASE/20150304_update_role.sql"),
      dbScript("$dbPath/convert/5.5.RELEASE/20150304_update_user_address.sql"),
      dbScript("$dbPath/convert/5.5.RELEASE/20150304_update_participant.sql"),
      dbScript("$dbPath/convert/5.5.RELEASE/20150304_update_application_user.sql"),
      dbScript("$dbPath/convert/5.5.RELEASE/20150304_update_message.sql"),
      dbScript("$dbPath/convert/5.5.RELEASE/20150304_update_module_app.sql"),
      dbScript("$dbPath/G4toG5/Step2_G5/prc_set_sequences.sql"),
      dbScript("$dbPath/convert/5.5.RELEASE/20150304_alter_rec_promo_recognition.sql"),
      dbScript("$dbPath/convert/5.5.RELEASE/20150304_alter_rec_scheduled_recognition.sql"),
      dbScript("$dbPath/convert/5.5.RELEASE/20150304_update_promo_goalquest.sql"),
      dbScript("$dbPath/convert/5.5.RELEASE/20150304_update_promo_challengepoint.sql"),
      dbScript("$dbPath/convert/5.5.RELEASE/20150403_create_eng_stage_score_detail.sql"),
      dbScript("$dbPath/convert/5.5.RELEASE/20150304_alter_eng_engagement_chart.sql"),
      dbScript("$dbPath/convert/5.5.RELEASE/20150304_update_survey_question_response.sql"),
      dbScript("$dbPath/convert/5.5.RELEASE/20150304_create_ssi_promo_ssi.sql"),
      dbScript("$dbPath/convert/5.5.RELEASE/20150304_create_ssi_contest.sql"),
      dbScript("$dbPath/convert/5.5.RELEASE/20150304_create_ssi_contest_activity.sql"),
      dbScript("$dbPath/convert/5.5.RELEASE/20150304_create_ssi_contest_approver.sql"),
      dbScript("$dbPath/convert/5.5.RELEASE/20150304_create_ssi_contest_atn.sql"),
      dbScript("$dbPath/convert/5.5.RELEASE/20150304_create_ssi_contest_document.sql"),
      dbScript("$dbPath/convert/5.5.RELEASE/20150304_create_ssi_contest_level.sql"),
      dbScript("$dbPath/convert/5.5.RELEASE/20150304_create_ssi_contest_manager.sql"),
      dbScript("$dbPath/convert/5.5.RELEASE/20150304_create_ssi_contest_participant.sql"),
      dbScript("$dbPath/convert/5.5.RELEASE/20150304_create_ssi_contest_pax_payout.sql"),
      dbScript("$dbPath/convert/5.5.RELEASE/20150304_create_ssi_contest_pax_progress.sql"),
      dbScript("$dbPath/convert/5.5.RELEASE/20150304_create_ssi_contest_pax_stack_rank.sql"),
      dbScript("$dbPath/convert/5.5.RELEASE/20150304_create_ssi_contest_sr_payout.sql"),
      dbScript("$dbPath/convert/5.5.RELEASE/20150304_create_ssi_gtt.sql"),
      dbScript("$dbPath/convert/5.5.RELEASE/20150304_create_ssi_stage_pax_progress.sql"),
      // PL/SQL Changes
      dbScript("$dbPath/plsql/pkg_build_audience.sql"),
      dbScript("$dbPath/plsql/pkg_bulk_pax_stage.sql"),
      dbScript("$dbPath/plsql/pkg_extracts.sql"),
      dbScript("$dbPath/plsql/pkg_hierarchy_verify_import.sql"),
      dbScript("$dbPath/plsql/pkg_participant_verify_import.sql"),
      dbScript("$dbPath/plsql/pkg_query_claims_activity.sql"),
      dbScript("$dbPath/plsql/pkg_populate_promo_elig.sql"),
      dbScript("$dbPath/plsql/pkg_query_awards_received.sql"),
      dbScript("$dbPath/plsql/pkg_query_individual_activity.sql"),
      dbScript("$dbPath/plsql/pkg_query_login_activity.sql"),
      dbScript("$dbPath/plsql/pkg_report_budget.sql"),
      dbScript("$dbPath/plsql/pkg_badge_verify_import.sql"),
      dbScript("$dbPath/plsql/pkg_budget_verify_import.sql"),
      dbScript("$dbPath/plsql/prc_welcome_email_prep.sql"),
      dbScript("$dbPath/plsql/pkg_report_badge.sql"),
      dbScript("$dbPath/plsql/prc_budget_load.sql"),
      dbScript("$dbPath/plsql/prc_copy_cms_asset.sql"),
      dbScript("$dbPath/plsql/prc_budget_transfer.sql"),
      dbScript("$dbPath/plsql/prc_deposit_load.sql"),
      dbScript("$dbPath/plsql/prc_report_refresh.sql"),
      dbScript("$dbPath/plsql/prc_rpt_qcard_refresh.sql"),
      dbScript("$dbPath/plsql/fnc_badge_eligibility.sql"),
      dbScript("$dbPath/plsql/pkg_query_budget_balance.sql"),
      dbScript("$dbPath/plsql/pkg_list_recognition_wall.sql"),
      dbScript("$dbPath/plsql/pkg_query_recog_given.sql"),
      dbScript("$dbPath/plsql/pkg_query_recog_list_of_givers.sql"),
      dbScript("$dbPath/plsql/pkg_query_recog_purl_activity.sql"),
      dbScript("$dbPath/plsql/pkg_query_recog_received.sql"),
      dbScript("$dbPath/plsql/pkg_query_recog_recipients.sql"),
      dbScript("$dbPath/plsql/pkg_report_recognition.sql"),
      dbScript("$dbPath/plsql/pkg_query_nomi_given.sql"),
      dbScript("$dbPath/plsql/pkg_query_nomi_receive.sql"),
      dbScript("$dbPath/plsql/pkg_report_nomination.sql"),
      dbScript("$dbPath/plsql/pkg_report_claim.sql"),
      dbScript("$dbPath/plsql/pkg_query_goalquest.sql"),
      dbScript("$dbPath/plsql/pkg_report_goalquest.sql"),
      dbScript("$dbPath/plsql/prc_getGQPaxMiniProfile.sql"),
      dbScript("$dbPath/plsql/pkg_query_challengepoint.sql"),
      dbScript("$dbPath/plsql/pkg_engagement_extract.sql"),
      dbScript("$dbPath/plsql/pkg_engagement.sql"),
      dbScript("$dbPath/plsql/pkg_query_throwdown_activity.sql"),
      dbScript("$dbPath/plsql/pkg_report_throwdown.sql"),
      dbScript("$dbPath/plsql/pkg_query_quiz_activity.sql"),
      dbScript("$dbPath/plsql/pkg_query_quiz_analysis.sql"),
      dbScript("$dbPath/plsql/pkg_quiz_reports.sql"),
      dbScript("$dbPath/plsql/pkg_ssi_contest_data.sql"),
      dbScript("$dbPath/plsql/pkg_ssi_contest.sql"),
      dbScript("$dbPath/plsql/prc_ssi_progress_load.sql")
    ]
  ],

  convert_55_to_551: [
    task: true,
    description: "Converts database from 5.5 to 5.5.1 Release",
    group: project.ext.databaseConvertGroup,
    actions: [
      // Confirmation
      dbSublist("convert_confirmation"),
      // Schema changes
      dbScript("$dbPath/convert/5.5.1.RELEASE/20150612_alter_core_claim_form_step_element.sql"),
      dbScript("$dbPath/convert/5.5.1.RELEASE/20150612_update_message.sql"),
      dbScript("$dbPath/convert/5.5.1.RELEASE/20150612_update_os_propertyset.sql"),
      dbScript("$dbPath/convert/5.5.1.RELEASE/20150612_rpt_purl_contribution_detail.sql"),
      dbScript("$dbPath/convert/5.5.1.RELEASE/20150612_alter_ssi_contest_pax_payout.sql"),
      dbScript("$dbPath/convert/5.5.1.RELEASE/20150612_alter_ssi_contest.sql"),
      dbScript("$dbPath/convert/5.5.1.RELEASE/20150612_alter_ssi_promo_ssi.sql"),
      dbScript("$dbPath/convert/5.5.1.RELEASE/20150612_create_rpt_ssi_contest_detail.sql"),
      dbScript("$dbPath/convert/5.5.1.RELEASE/20150612_create_ssi_contest_pax_claim.sql"),
      dbScript("$dbPath/convert/5.5.1.RELEASE/20150612_create_ssi_contest_claim_field.sql"),
      dbScript("$dbPath/convert/5.5.1.RELEASE/20150612_create_ssi_contest_pax_claim_field.sql"),
      dbScript("$dbPath/convert/5.5.1.RELEASE/20150612_rpt_ssi_award_detail.sql"),
      // PL/SQL Changes
      dbScript("$dbPath/plsql/fnc_get_badge_cms_value.sql"),
      dbScript("$dbPath/plsql/pkg_build_audience.sql"),
      dbScript("$dbPath/plsql/pkg_extracts.sql"),
      dbScript("$dbPath/plsql/pkg_participant_verify_import.sql"),
      dbScript("$dbPath/plsql/pkg_populate_promo_elig.sql"),
      dbScript("$dbPath/plsql/pkg_query_awards_received.sql"),
      dbScript("$dbPath/plsql/pkg_query_budget_balance.sql"),
      dbScript("$dbPath/plsql/pkg_query_claims_activity.sql"),
      dbScript("$dbPath/plsql/pkg_query_individual_activity.sql"),
      dbScript("$dbPath/plsql/pkg_query_plateau_item_select.sql"),
      dbScript("$dbPath/plsql/pkg_query_recog_purl_activity.sql"),
      dbScript("$dbPath/plsql/pkg_report_client_reports.sql"),
      dbScript("$dbPath/plsql/pkg_report_recognition.sql"),
      dbScript("$dbPath/plsql/prc_clear_lob_space.sql"),
      dbScript("$dbPath/plsql/prc_report_refresh.sql"),
      dbScript("$dbPath/plsql/pkg_report_claim.sql"),
      dbScript("$dbPath/plsql/pkg_engagement.sql"),
      dbScript("$dbPath/plsql/pkg_engagement_extract.sql"),
      dbScript("$dbPath/plsql/pkg_ssi_contest_data.sql"),
      dbScript("$dbPath/plsql/pkg_ssi_contest.sql"),
      dbScript("$dbPath/plsql/prc_report_ssi_contest.sql"),
      dbScript("$dbPath/plsql/prc_rpt_ssi_award_detail.sql"),
      dbScript("$dbPath/plsql/prc_ssi_progress_load.sql")
    ]
  ],

  convert_551_to_552: [
    task: true,
    description: "Converts database from 5.5.1 to 5.5.2 Release",
    group: project.ext.databaseConvertGroup,
    actions: [
      // Confirmation
      dbSublist("convert_confirmation"),
      // Schema changes
      dbScript("$dbPath/convert/5.5.2.RELEASE/20152707_alter_budget_history.sql"),
      dbScript("$dbPath/convert/5.5.2.RELEASE/20152707_alter_import_file.sql"),
      dbScript("$dbPath/convert/5.5.2.RELEASE/20152707_alter_rpt_qcard_detail.sql"),
      dbScript("$dbPath/convert/5.5.2.RELEASE/20152707_create_gtt_pax_report.sql"),
      dbScript("$dbPath/convert/5.5.2.RELEASE/20152707_update_message.sql"),
      dbScript("$dbPath/convert/5.5.2.RELEASE/20152707_update_os_property_set.sql"),
      dbScript("$dbPath/convert/5.5.2.RELEASE/20152707_alter_rpt_ssi_award_detail.sql"),
      dbScript("$dbPath/convert/5.5.2.RELEASE/20152707_alter_ssi_contest_sr_payout.sql"),
      dbScript("$dbPath/convert/5.5.2.RELEASE/20152707_alter_ssi_contest.sql"),
      // PL/SQL Changes
      dbScript("$dbPath/plsql/fnc_badge_eligibility.sql"),
      dbScript("$dbPath/plsql/pkg_budget_verify_import.sql"),
      dbScript("$dbPath/plsql/pkg_extracts.sql"),
      dbScript("$dbPath/plsql/pkg_hierarchy_verify_import.sql"),
      dbScript("$dbPath/plsql/pkg_participant_verify_import.sql"),
      dbScript("$dbPath/plsql/pkg_query_awards_received.sql"),
      dbScript("$dbPath/plsql/pkg_query_budget_balance.sql"),
      dbScript("$dbPath/plsql/pkg_query_goalquest.sql"),
      dbScript("$dbPath/plsql/pkg_query_individual_activity.sql"),
      dbScript("$dbPath/plsql/pkg_query_quiz_activity.sql"),
      dbScript("$dbPath/plsql/pkg_report_common.sql"),
      dbScript("$dbPath/plsql/pkg_report_recognition.sql"),
      dbScript("$dbPath/plsql/prc_hierarchy_load.sql"),
      dbScript("$dbPath/plsql/pkg_list_recognition_wall.sql"),
      dbScript("$dbPath/plsql/pkg_engagement_extract.sql"),
      dbScript("$dbPath/plsql/pkg_engagement.sql"),
      dbScript("$dbPath/plsql/prc_rpt_ssi_award_detail.sql"),
      dbScript("$dbPath/plsql/pkg_ssi_contest_data.sql"),
      dbScript("$dbPath/plsql/pkg_ssi_contest.sql")
    ]
  ]
]

project.ext.dbTaskConfigList << [
  convert_552_to_553: [
    task: true,
    description: "Converts database from 5.5.2 to 5.5.3 Release",
    group: project.ext.databaseConvertGroup,
    actions: [
      // Confirmation
      dbSublist("convert_confirmation"),
      // Schema changes
      dbScript("$dbPath/convert/5.5.3.RELEASE/20150209_alter_merch_order.sql"),
      dbScript("$dbPath/convert/5.5.3.RELEASE/20150209_update_message.sql"),
      dbScript("$dbPath/convert/5.5.3.RELEASE/20150209_update_os_propertyset.sql"),
      dbScript("$dbPath/convert/5.5.3.RELEASE/20150209_alter_rec_promo_recognition.sql"),
      // PL/SQL Changes
      dbScript("$dbPath/plsql/fnc_check_promo_aud.sql"),
      dbScript("$dbPath/plsql/pkg_extracts.sql"),
      dbScript("$dbPath/plsql/pkg_hierarchy_verify_import.sql"),
      dbScript("$dbPath/plsql/pkg_participant_verify_import.sql"),
      dbScript("$dbPath/plsql/pkg_query_awards_received.sql"),
      dbScript("$dbPath/plsql/pkg_query_individual_activity.sql"),
      dbScript("$dbPath/plsql/pkg_query_quiz_analysis.sql"),
      dbScript("$dbPath/plsql/prc_award_generator_extract.sql"),
      dbScript("$dbPath/plsql/prc_award_generator.sql"),
      dbScript("$dbPath/plsql/pkg_report_budget.sql"),
      dbScript("$dbPath/plsql/pkg_engagement.sql"),
      dbScript("$dbPath/plsql/pkg_ssi_contest_data.sql"),
      dbScript("$dbPath/plsql/prc_rpt_ssi_award_detail.sql")
    ]
  ],

  convert_553_to_561: [
    task: true,
    description: "Converts database from 5.5.3 to 5.6.1 Release",
    group: project.ext.databaseConvertGroup,
    actions: [
      // Confirmation
      dbSublist("convert_confirmation"),
      // Schema changes
      dbScript("$dbPath/convert/5.6.1.RELEASE/20151015_alter_core_report.sql"),
      dbScript("$dbPath/convert/5.6.1.RELEASE/20151015_alter_core_report_chart.sql"),
      dbScript("$dbPath/convert/5.6.1.RELEASE/20151015_alter_core_node.sql"),
      dbScript("$dbPath/convert/5.6.1.RELEASE/20151015_alter_core_rpt_awardmedia_detail.sql"),
      dbScript("$dbPath/convert/5.6.1.RELEASE/20151015_alter_core_rpt_hierarchy.sql"),
      dbScript("$dbPath/convert/5.6.1.RELEASE/20151015_alter_core_stage_budget_import_record.sql"),
      dbScript("$dbPath/convert/5.6.1.RELEASE/20151015_insert_module_app.sql"),
      dbScript("$dbPath/convert/5.6.1.RELEASE/20151015_update_os_propertyset.sql"),
      dbScript("$dbPath/convert/5.6.1.RELEASE/20151015_update_report.sql"),
      // PL/SQL Changes
      dbScript("$dbPath/plsql/pkg_build_audience.sql"),
      dbScript("$dbPath/plsql/pkg_extracts.sql"),
      dbScript("$dbPath/plsql/pkg_hierarchy_verify_import.sql"),
      dbScript("$dbPath/plsql/pkg_list_recognition_wall.sql"),
      dbScript("$dbPath/plsql/pkg_participant_verify_import.sql"),
      dbScript("$dbPath/plsql/pkg_query_awards_received.sql"),
      dbScript("$dbPath/plsql/pkg_query_quiz_activity.sql"),
      dbScript("$dbPath/plsql/pkg_query_recog_given.sql"),
      dbScript("$dbPath/plsql/pkg_query_recog_list_of_givers.sql"),
      dbScript("$dbPath/plsql/pkg_query_survey_reports.sql"),
      dbScript("$dbPath/plsql/pkg_report_budget.sql"),
      dbScript("$dbPath/plsql/prc_hierarchy_load.sql"),
      dbScript("$dbPath/plsql/pkg_engagement.sql"),
      dbScript("$dbPath/plsql/prc_report_ssi_contest.sql"),
      dbScript("$dbPath/plsql/pkg_ssi_contest_data.sql")
    ]
  ],

  convert_561_to_562: [
    task: true,
    description: "Converts database from 5.6.1 to 5.6.2 Release",
    group: project.ext.databaseConvertGroup,
    actions: [
      // Confirmation
      dbSublist("convert_confirmation"),
      // Schema changes
      dbScript("$dbPath/convert/5.6.2.RELEASE/20162602_alter_import_file.sql"),
      dbScript("$dbPath/convert/5.6.2.RELEASE/20162602_alter_participant_badge.sql"),
      dbScript("$dbPath/convert/5.6.2.RELEASE/20162602_create_core_promo_bill_code.sql"),
      dbScript("$dbPath/convert/5.6.2.RELEASE/20162602_create_core_stage_inactive_budget_rd.sql"),
      dbScript("$dbPath/convert/5.6.2.RELEASE/20162602_alter_stage_pax_import_record.sql"),
      dbScript("$dbPath/convert/5.6.2.RELEASE/20162602_alter_user_country_changes.sql"),
      dbScript("$dbPath/convert/5.6.2.RELEASE/20162602_alter_temp_table_session.sql"),
      dbScript("$dbPath/convert/5.6.2.RELEASE/20162602_alter_gtt_pax_report.sql"),
      dbScript("$dbPath/convert/5.6.2.RELEASE/20162602_create_gtt_recog_elg_pax_count.sql"),
      dbScript("$dbPath/convert/5.6.2.RELEASE/20162602_create_wh_workhappier.sql"),
      dbScript("$dbPath/convert/5.6.2.RELEASE/20162602_create_table_rpt_work_happier_detail.sql"),
      dbScript("$dbPath/convert/5.6.2.RELEASE/20162602_alter_core_rpt_budget.sql"),
      dbScript("$dbPath/convert/5.6.2.RELEASE/20162602_alter_rpt_recognition_detail.sql"),
      dbScript("$dbPath/convert/5.6.2.RELEASE/20162602_alter_stage_inactive_budget_rd.sql"),
      dbScript("$dbPath/convert/5.6.2.RELEASE/20162602_insert_workhappier_extract.sql"),
      dbScript("$dbPath/convert/5.6.2.RELEASE/20162602_insert_workhappier.sql"),
      dbScript("$dbPath/convert/5.6.2.RELEASE/20162602_update_message.sql"),
      dbScript("$dbPath/convert/5.6.2.RELEASE/20162602_update_module_app.sql"),
      dbScript("$dbPath/convert/5.6.2.RELEASE/20162602_update_os_property_set.sql"),
      dbScript("$dbPath/convert/5.6.2.RELEASE/20162602_update_rec_card.sql"),
      dbScript("$dbPath/convert/5.6.2.RELEASE/20162602_update_rec_ecard.sql"),
      dbScript("$dbPath/convert/5.6.2.RELEASE/20162602_update_reports.sql"),
      dbScript("$dbPath/convert/5.6.2.RELEASE/20162602_alter_promo_recognition.sql"),
      dbScript("$dbPath/convert/5.6.2.RELEASE/20162602_alter_scheduled_recognition.sql"),
      dbScript("$dbPath/convert/5.6.2.RELEASE/20162602_create_rec_rpt_purl_recipient.sql"),
      dbScript("$dbPath/convert/5.6.2.RELEASE/20162602_alter_tmp_award_item_activity_rpt.sql"),
      dbScript("$dbPath/convert/5.6.2.RELEASE/20162602_alter_rpt_quiz_activity_summary.sql"),
      dbScript("$dbPath/convert/5.6.2.RELEASE/20162602_alter_ssi_contest_activity.sql"),
      dbScript("$dbPath/convert/5.6.2.RELEASE/20162602_alter_ssi_contest_level.sql"),
      dbScript("$dbPath/convert/5.6.2.RELEASE/20162602_alter_ssi_stage_pax_progress.sql"),
      dbScript("$dbPath/convert/5.6.2.RELEASE/20162602_create_ssi_table_indexes.sql"),
      // PL/SQL Changes
      dbScript("$dbPath/plsql/prc_report_refresh.sql"),
      dbScript("$dbPath/plsql/prc_rpt_qcard_refresh.sql"),
      dbScript("$dbPath/plsql/prc_stage_inactive_budgets_rd.sql"),
      dbScript("$dbPath/plsql/prc_stg_inactive_budget_rd_ins.sql"),
      dbScript("$dbPath/plsql/pkg_report_recognition.sql"),
      dbScript("$dbPath/plsql/pkg_report_work_happier.sql"),
      dbScript("$dbPath/plsql/prc_award_generator.sql"),
      dbScript("$dbPath/plsql/pkg_report_client_reports.sql"),
      dbScript("$dbPath/plsql/pkg_participant_verify_import.sql"),
      dbScript("$dbPath/plsql/pkg_query_awards_received.sql"),
      dbScript("$dbPath/plsql/pkg_query_goalquest.sql"),
      dbScript("$dbPath/plsql/pkg_query_quiz_activity.sql"),
      dbScript("$dbPath/plsql/pkg_query_recog_given.sql"),
      dbScript("$dbPath/plsql/pkg_query_recog_list_of_givers.sql"),
      dbScript("$dbPath/plsql/pkg_query_recog_purl_activity.sql"),
      dbScript("$dbPath/plsql/pkg_query_recog_recipients.sql"),
      dbScript("$dbPath/plsql/pkg_report_budget.sql"),
      dbScript("$dbPath/plsql/pkg_extracts.sql"),
      dbScript("$dbPath/plsql/pkg_hierarchy_verify_import.sql"),
      dbScript("$dbPath/plsql/pkg_inactive_budget_rd.sql"),
      dbScript("$dbPath/plsql/fnc_cms_asset_code_value.sql"),
      dbScript("$dbPath/plsql/fnc_promo_budget_meter.sql"),
      dbScript("$dbPath/plsql/pkg_badge_verify_import.sql"),
      dbScript("$dbPath/plsql/pkg_budget_verify_import.sql"),
      dbScript("$dbPath/plsql/pkg_build_audience.sql"),
      dbScript("$dbPath/plsql/pkg_bulk_pax_stage.sql"),
      dbScript("$dbPath/plsql/pkg_list_recognition_wall.sql"),
      dbScript("$dbPath/plsql/prc_delete_engagement_promo.sql"),
      dbScript("$dbPath/plsql/pkg_engagement_extract.sql"),
      dbScript("$dbPath/plsql/pkg_engagement.sql"),
      dbScript("$dbPath/plsql/pkg_report_goalquest.sql"),
      dbScript("$dbPath/plsql/pkg_report_challangepoint.sql"),
      dbScript("$dbPath/plsql/pkg_report_product_claim.sql"),
      dbScript("$dbPath/plsql/pkg_report_claim.sql")
    ]
  ],

  convert_562_to_5621: [
    task: true,
    description: "Converts database from 5.6.2 to 5.6.2.1 Release",
    group: project.ext.databaseConvertGroup,
    actions: [
      // Confirmation
      dbSublist("convert_confirmation"),
      // Schema changes
      dbScript("$dbPath/convert/5.6.2.1.RELEASE/20160617_alter_promo_bill_code.sql"),
      dbScript("$dbPath/convert/5.6.2.1.RELEASE/20160622_alter_report.sql")
    ]
  ],

  convert_5621_to_563: [
    task: true,
    description: "Converts database from 5.6.2.1 to 5.6.3 Release",
    group: project.ext.databaseConvertGroup,
    actions: [
      // Confirmation
      dbSublist("convert_confirmation"),
      // Schema changes
      dbScript("$dbPath/convert/5.6.3.RELEASE/20160712_alter_module.sql"),
      dbScript("$dbPath/convert/5.6.3.RELEASE/20160712_alter_report.sql"),
      dbScript("$dbPath/convert/5.6.3.RELEASE/20160712_alter_message.sql"),
      dbScript("$dbPath/convert/5.6.3.RELEASE/20160712_alter_rec_card.sql"),
      dbScript("$dbPath/convert/5.6.3.RELEASE/20160712_alter_promotion.sql"),
      dbScript("$dbPath/convert/5.6.3.RELEASE/20160712_create_approver_option.sql"),
      dbScript("$dbPath/convert/5.6.3.RELEASE/20160712_create_approver_criteria.sql"),
      dbScript("$dbPath/convert/5.6.3.RELEASE/20160712_create_approver.sql"),
      dbScript("$dbPath/convert/5.6.3.RELEASE/20160712_create_participant_group.sql"),
      dbScript("$dbPath/convert/5.6.3.RELEASE/20160712_alter_claim.sql"),
      dbScript("$dbPath/convert/5.6.3.RELEASE/20160712_alter_claim_recipient.sql"),
      dbScript("$dbPath/convert/5.6.3.RELEASE/20160712_alter_promo_behavior.sql"),
      dbScript("$dbPath/convert/5.6.3.RELEASE/20160712_alter_promo_card.sql"),
      dbScript("$dbPath/convert/5.6.3.RELEASE/20160712_alter_promo_certificate.sql"),
      dbScript("$dbPath/convert/5.6.3.RELEASE/20160712_alter_activity.sql"),
      dbScript("$dbPath/convert/5.6.3.RELEASE/20160712_alter_budget.sql"),
      dbScript("$dbPath/convert/5.6.3.RELEASE/20160712_alter_claim_approver_snapshot.sql"),
      dbScript("$dbPath/convert/5.6.3.RELEASE/20160712_alter_cfse.sql"),
      dbScript("$dbPath/convert/5.6.3.RELEASE/20160712_alter_claim_group.sql"),
      dbScript("$dbPath/convert/5.6.3.RELEASE/20160712_alter_claim_item_approver.sql"),
      dbScript("$dbPath/convert/5.6.3.RELEASE/20160712_alter_pax_comm_prefs.sql"),
      dbScript("$dbPath/convert/5.6.3.RELEASE/20160712_alter_country.sql"),
      dbScript("$dbPath/convert/5.6.3.RELEASE/20160712_alter_journal.sql"),
      dbScript("$dbPath/convert/5.6.3.RELEASE/20160712_create_journal_bill_code.sql"),
      dbScript("$dbPath/convert/5.6.3.RELEASE/20160712_create_cash_currency_current.sql"),
      dbScript("$dbPath/convert/5.6.3.RELEASE/20160712_create_cash_currency_history.sql"),
      dbScript("$dbPath/convert/5.6.3.RELEASE/20160712_alter_rpt_awardmedia.sql"),
      dbScript("$dbPath/convert/5.6.3.RELEASE/20160712_alter_rpt_badge.sql"),
      dbScript("$dbPath/convert/5.6.3.RELEASE/20160712_alter_rpt_budget.sql"),
      dbScript("$dbPath/convert/5.6.3.RELEASE/20160712_create_rpt_cash_budget.sql"),
      dbScript("$dbPath/convert/5.6.3.RELEASE/20160712_alter_rpt_claim.sql"),
      dbScript("$dbPath/convert/5.6.3.RELEASE/20160712_alter_rpt_enrollment.sql"),
      dbScript("$dbPath/convert/5.6.3.RELEASE/20160712_alter_rpt_hierarchy.sql"),
      dbScript("$dbPath/convert/5.6.3.RELEASE/20160712_alter_rpt_promo_node_activity.sql"),
      dbScript("$dbPath/convert/5.6.3.RELEASE/20160712_alter_rpt_qcard.sql"),
      dbScript("$dbPath/convert/5.6.3.RELEASE/20160712_alter_rpt_cp_details.sql"),
      dbScript("$dbPath/convert/5.6.3.RELEASE/20160712_alter_rpt_gq_details.sql"),
      dbScript("$dbPath/convert/5.6.3.RELEASE/20160712_alter_rpt_cp_summary.sql"),
      dbScript("$dbPath/convert/5.6.3.RELEASE/20160712_alter_rpt_quiz.sql"),
      dbScript("$dbPath/convert/5.6.3.RELEASE/20160712_alter_GQ_rpt_goal_selection_detail.sql"),
      dbScript("$dbPath/convert/5.6.3.RELEASE/20160712_alter_rpt_award_details.sql"),
      dbScript("$dbPath/convert/5.6.3.RELEASE/20160712_alter_rpt_rec_details.sql"),
      dbScript("$dbPath/convert/5.6.3.RELEASE/20160712_create_rpt_behavior_details.sql"),
      dbScript("$dbPath/convert/5.6.3.RELEASE/20160712_alter_rpt_promo_elig_counts.sql"),
      dbScript("$dbPath/convert/5.6.3.RELEASE/20160712_alter_rpt_ssi.sql"),
      dbScript("$dbPath/convert/5.6.3.RELEASE/20160712_alter_rpt_svy.sql"),
      dbScript("$dbPath/convert/5.6.3.RELEASE/20160712_alter_rpt_work_happier.sql"),
      dbScript("$dbPath/convert/5.6.3.RELEASE/20160712_alter_rpt_throwdown.sql"),
      dbScript("$dbPath/convert/5.6.3.RELEASE/20160712_alter_rpt_nomination_details.sql"),
      dbScript("$dbPath/convert/5.6.3.RELEASE/20160712_create_gtt_id_list.sql"),
      dbScript("$dbPath/convert/5.6.3.RELEASE/20160712_create_gtt_manager_id.sql"),
      dbScript("$dbPath/convert/5.6.3.RELEASE/20160712_create_tmp_tables.sql"),
      dbScript("$dbPath/convert/5.6.3.RELEASE/20160720_create_post_process_jobs.sql"),
      dbScript("$dbPath/convert/5.6.3.RELEASE/20160720_create_post_process_payout_calc.sql"),
      dbScript("$dbPath/convert/5.6.3.RELEASE/20160720_alter_recognition_claim.sql"),
      dbScript("$dbPath/convert/5.6.3.RELEASE/20160722_alter_purl_contributor_comment.sql"),
      dbScript("$dbPath/convert/5.6.3.RELEASE/20160908_create_video_upload_detail.sql"),
      dbScript("$dbPath/convert/5.6.3.RELEASE/20160712_alter_promo_nomination.sql"),
      dbScript("$dbPath/convert/5.6.3.RELEASE/20160712_create_promo_nomination_level.sql"),
      dbScript("$dbPath/convert/5.6.3.RELEASE/20160712_create_promo_nomination_timeperiod.sql"),
      dbScript("$dbPath/convert/5.6.3.RELEASE/20160712_create_promo_nomination_wizard.sql"),
      dbScript("$dbPath/convert/5.6.3.RELEASE/20160712_alter_nomination_claim.sql"),
      dbScript("$dbPath/convert/5.6.3.RELEASE/20160712_create_nomination_claim_behaviors.sql"),
      dbScript("$dbPath/convert/5.6.3.RELEASE/20160712_create_stage_nom_approvers_import.sql"),
      dbScript("$dbPath/convert/5.6.3.RELEASE/20161003_alter_rpt_characteristic.sql"),
      dbScript("$dbPath/convert/5.6.3.RELEASE/prc_budget_segment_insert_cms.sql"),
      dbScript("$dbPath/convert/5.6.3.RELEASE/5.6.3.convert_scripts_oracle.sql"),
      dbScript("$dbPath/convert/5.6.3.RELEASE/20160712_alter_os_propertyset.sql"),
      // PL/SQL Changes
      dbScript("$dbPath/plsql/create_fnc_get_dir_name_like.sql"),
      dbScript("$dbPath/plsql/create_pkg_query_behaviors_report.sql"),
      dbScript("$dbPath/plsql/pkg_query_nomi_aging.sql"),
      dbScript("$dbPath/plsql/create_pkg_report_behavior.sql"),
      dbScript("$dbPath/plsql/create_prc_list_nom_inprogress.sql"),
      dbScript("$dbPath/plsql/create_prc_nom_more_info_page.sql"),
      dbScript("$dbPath/plsql/create_prc_nomination_certificate_dtl.sql"),
      dbScript("$dbPath/plsql/create_prc_nomination_modal_window.sql"),
      dbScript("$dbPath/plsql/create_prc_nominations_my_win_list.sql"),
      dbScript("$dbPath/plsql/pkg_badge_verify_import.sql"),
      dbScript("$dbPath/plsql/pkg_budget_verify_import.sql"),
      dbScript("$dbPath/plsql/pkg_build_audience.sql"),
      dbScript("$dbPath/plsql/pkg_bulk_pax_stage.sql"),
      dbScript("$dbPath/plsql/pkg_const.sql"),
      dbScript("$dbPath/plsql/pkg_engagement_extract.sql"),
      dbScript("$dbPath/plsql/pkg_engagement.sql"),
      dbScript("$dbPath/plsql/pkg_extracts.sql"),
      dbScript("$dbPath/plsql/pkg_hierarchy_verify_import.sql"),
      dbScript("$dbPath/plsql/pkg_list_past_win_nominations.sql"),
      dbScript("$dbPath/plsql/pkg_list_pend_nominations.sql"),
      dbScript("$dbPath/plsql/pkg_list_recognition_wall.sql"),
      dbScript("$dbPath/plsql/pkg_nom_approver_verify_import.sql"),
      dbScript("$dbPath/plsql/pkg_participant_verify_import.sql"),
      dbScript("$dbPath/plsql/pkg_populate_promo_elig.sql"),
      dbScript("$dbPath/plsql/pkg_query_awards_received.sql"),
      dbScript("$dbPath/plsql/pkg_query_badge_activity.sql"),
      dbScript("$dbPath/plsql/pkg_query_budget_balance.sql"),
      dbScript("$dbPath/plsql/pkg_query_cash_budget_balance.sql"),
      dbScript("$dbPath/plsql/pkg_query_enroll_reports.sql"),
      dbScript("$dbPath/plsql/pkg_query_individual_activity.sql"),
      dbScript("$dbPath/plsql/pkg_query_nomi_given.sql"),
      dbScript("$dbPath/plsql/pkg_query_nomi_receive.sql"),
      dbScript("$dbPath/plsql/pkg_query_nomination.sql"),
      dbScript("$dbPath/plsql/pkg_query_quiz_activity.sql"),
      dbScript("$dbPath/plsql/pkg_query_recog_given.sql"),
      dbScript("$dbPath/plsql/pkg_query_recog_purl_activity.sql"),
      dbScript("$dbPath/plsql/pkg_query_recog_received.sql"),
      dbScript("$dbPath/plsql/pkg_query_recog_recipients.sql"),
      dbScript("$dbPath/plsql/pkg_quiz_reports.sql"),
      dbScript("$dbPath/plsql/pkg_report_awardmedia.sql"),
      dbScript("$dbPath/plsql/pkg_report_cash_budget.sql"),
      dbScript("$dbPath/plsql/pkg_report_challangepoint.sql"),
      dbScript("$dbPath/plsql/pkg_report_characteristic.sql"),
      dbScript("$dbPath/plsql/pkg_report_common.sql"),
      dbScript("$dbPath/plsql/pkg_report_nomination.sql"),
      dbScript("$dbPath/plsql/pkg_report_recognition.sql"),
      dbScript("$dbPath/plsql/pkg_ssi_contest_data.sql"),
      dbScript("$dbPath/plsql/pkg_ssi_contest.sql"),
      dbScript("$dbPath/plsql/prc_award_generator_extract.sql"),
      dbScript("$dbPath/plsql/prc_award_generator.sql"),
      dbScript("$dbPath/plsql/prc_budget_transfer.sql"),
      dbScript("$dbPath/plsql/prc_ccs_recognition_wall.sql"),
      dbScript("$dbPath/plsql/prc_custom_approver_list_cas.sql"),
      dbScript("$dbPath/plsql/prc_purl_celebration_page.sql"),
      dbScript("$dbPath/plsql/prc_qrtz_post_process_job_del.sql"),
      dbScript("$dbPath/plsql/prc_ref_criteria_aud_inactive.sql"),
      dbScript("$dbPath/plsql/prc_refresh_pend_nom_approver.sql"),
      dbScript("$dbPath/plsql/prc_report_promo_node_activity.sql"),
      dbScript("$dbPath/plsql/prc_report_refresh.sql"),
      dbScript("$dbPath/plsql/prc_ssi_progress_load.sql"),
      dbScript("$dbPath/plsql/prc_stage_nom_approver_load.sql"),
      dbScript("$dbPath/plsql/prc_stg_inactive_budget_rd_ins.sql"),
      dbScript("$dbPath/plsql/prc_stg_nom_approver_insert.sql"),
      dbScript("$dbPath/plsql/prc_welcome_email_prep.sql"),
      // Convert scripts that needs to run at the end
      dbScript("$dbPath/convert/5.6.3.RELEASE/20160712_create_mv_cms.sql"),
      dbScript("$dbPath/convert/5.6.3.RELEASE/20160712_drop.sql")
    ]
  ],

  convert_563_to_5631: [
    task: true,
    description: "Converts database from 5.6.3 to 5.6.3.1 Release",
    group: project.ext.databaseConvertGroup,
    actions: [
      // Confirmation
      dbSublist("convert_confirmation"),
      // Schema changes
      dbScript("$dbPath/convert/5.6.3.1.RELEASE/20161027_alter_approver_option.sql"),
      dbScript("$dbPath/convert/5.6.3.1.RELEASE/20161031_alter_activity.sql"),
      dbScript("$dbPath/convert/5.6.3.1.RELEASE/20161102_alter_tmp_winner_nomination_summary.sql"),
      dbScript("$dbPath/convert/5.6.3.1.RELEASE/20161103_alter_tmp_winner_nomination_detail.sql"),
      dbScript("$dbPath/convert/5.6.3.1.RELEASE/20161104_alter_message.sql"),
      dbScript("$dbPath/convert/5.6.3.1.RELEASE/20161109_alter_os_propertyset.sql"),
      dbScript("$dbPath/convert/5.6.3.1.RELEASE/20161109_alter_report_parameter.sql"),
      // PL/SQL Changes
      dbScript("$dbPath/plsql/create_prc_nomination_modal_window.sql"),
      dbScript("$dbPath/plsql/create_prc_nominations_my_win_list.sql"),
      dbScript("$dbPath/plsql/pkg_extracts.sql"),
      dbScript("$dbPath/plsql/fnc_get_manager_node.sql"),
      dbScript("$dbPath/plsql/pkg_list_past_win_nominations.sql"),
      dbScript("$dbPath/plsql/pkg_list_pend_nominations.sql"),
      dbScript("$dbPath/plsql/pkg_query_awards_received.sql"),
      dbScript("$dbPath/plsql/pkg_query_recog_purl_activity.sql"),
      dbScript("$dbPath/plsql/pkg_report_recognition.sql"),
      dbScript("$dbPath/plsql/pkg_query_badge_activity.sql"),
      dbScript("$dbPath/plsql/pkg_query_claims_activity.sql"),
      dbScript("$dbPath/plsql/pkg_query_login_activity.sql"),
      dbScript("$dbPath/plsql/pkg_query_plateau_levels.sql"),
      dbScript("$dbPath/plsql/pkg_query_quiz_activity.sql")
    ]
  ],

  convert_5631_to_5632: [
    task: true,
    description: "Converts database from 5.6.3.1 to 5.6.3.2 Release",
    group: project.ext.databaseConvertGroup,
    actions: [
      // Confirmation
      dbSublist("convert_confirmation"),
      // Schema changes
      dbScript("$dbPath/convert/5.6.3.2.RELEASE/20161121_alter_propertyset.sql"),
      dbScript("$dbPath/convert/5.6.3.2.RELEASE/20161220_drop_pkg_query_recog_behaviors.sql"),
      dbScript("$dbPath/convert/5.6.3.2.RELEASE/20161220_drop_prc_nom_rpt_refresh.sql"),
      dbScript("$dbPath/convert/5.6.3.2.RELEASE/20161220_drop_prc_pc_rpt_refresh.sql"),
      dbScript("$dbPath/convert/5.6.3.2.RELEASE/20161220_drop_rec_rpt_recog_behavior_summary_tbl.sql"),
      dbScript("$dbPath/convert/5.6.3.2.RELEASE/20161227_alter_nomination_claim.sql"),
      dbScript("$dbPath/convert/5.6.3.2.RELEASE/20161227_alter_participant_survey.sql"),
      // PL/SQL Changes
      dbScript("$dbPath/plsql/fnc_get_manager_node.sql"),
      dbScript("$dbPath/plsql/create_prc_nom_more_info_page.sql"),
      dbScript("$dbPath/plsql/pkg_engagement_extract.sql"),
      dbScript("$dbPath/plsql/pkg_list_past_win_nominations.sql"),
      dbScript("$dbPath/plsql/pkg_query_goalquest.sql"),
      dbScript("$dbPath/plsql/pkg_query_quiz_activity.sql"),
      dbScript("$dbPath/plsql/pkg_query_recog_recipients.sql"),
      dbScript("$dbPath/plsql/pkg_report_budget.sql"),
      dbScript("$dbPath/plsql/prc_purl_celebration_page.sql"),
      dbScript("$dbPath/plsql/prc_ssi_progress_load.sql"),
      dbScript("$dbPath/plsql/pkg_query_nomi_aging.sql"),
      dbScript("$dbPath/plsql/pkg_engagement.sql"),
      dbScript("$dbPath/plsql/pkg_query_recog_received.sql"),
      dbScript("$dbPath/plsql/prc_report_refresh.sql"),
      dbScript("$dbPath/plsql/pkg_extracts.sql")
    ]
  ],

  convert_5632_to_5633: [
    task: true,
    description: "Converts database from 5.6.3.2 to 5.6.3.3 Release",
    group: project.ext.databaseConvertGroup,
    actions: [
      // Confirmation
      dbSublist("convert_confirmation"),
      // Schema changes
      dbScript("$dbPath/convert/5.6.3.3.RELEASE/20161229_alter_badge_activity_report_parameter_tbl.sql"),
      dbScript("$dbPath/convert/5.6.3.3.RELEASE/20170103_alter_cash_budget_balance_report_parameter_tbl.sql"),
      dbScript("$dbPath/convert/5.6.3.3.RELEASE/20170124_alter_budget_report.sql"),
      dbScript("$dbPath/convert/5.6.3.3.RELEASE/20170104_alter_points_budget_balance_report_parameter_tbl.sql"),
      dbScript("$dbPath/convert/5.6.3.3.RELEASE/20170110_alter_behavior_activity_chart_report_tbl.sql"),
      dbScript("$dbPath/convert/5.6.3.3.RELEASE/20170111_alter_rpt_behavior_detail.sql"),
      dbScript("$dbPath/convert/5.6.3.3.RELEASE/20170116_alter_nominations_list_of_nominators_report_parameter_tbl.sql"),
      dbScript("$dbPath/convert/5.6.3.3.RELEASE/20170116_alter_nominations_list_of_nominees_report_parameter_tbl.sql"),
      dbScript("$dbPath/convert/5.6.3.3.RELEASE/20170117_alter_nomination_activity_by_org_report_parameter_tbl.sql"),
      dbScript("$dbPath/convert/5.6.3.3.RELEASE/20170123_alter_nomination_aging_status_report_parameter_tbl.sql"),
      dbScript("$dbPath/convert/5.6.3.3.RELEASE/20170125_alter_awards_reeived_participants_report_parameter_tbl.sql"),
      dbScript("$dbPath/convert/5.6.3.3.RELEASE/20170130_alter_awards_received_by_org_report_parameter_tbl.sql"),
      dbScript("$dbPath/convert/5.6.3.3.RELEASE/20170120_alter_journal.sql"),
      dbScript("$dbPath/convert/5.6.3.3.RELEASE/20170116_alter_core_mailing_message_locale_tbl.sql"),
      dbScript("$dbPath/convert/5.6.3.3.RELEASE/20170209_create_alter_approver_option.sql"),
      dbScript("$dbPath/convert/5.6.3.3.RELEASE/20170210_update_os_propertyset.sql"),
      dbScript("$dbPath/convert/5.6.3.3.RELEASE/20170213_create_new_table_cms_content_data_str.sql"),
      dbScript("$dbPath/convert/5.6.3.3.RELEASE/20170221_drop_report_old_behavior_objects.sql"),
      dbScript("$dbPath/schema/create_mv_cms_asset_value1.sql"),
      dbScript("$dbPath/schema/create_mv_cms_asset_value2.sql"),
      dbScript("$dbPath/schema/create_mv_cms_asset_value3.sql"),
      dbScript("$dbPath/schema/create_mv_cms_code_value.sql"),
      dbScript("$dbPath/schema/create_mv_cms_user_characteristic.sql"),
      dbScript("$dbPath/schema/create_vw_cms_asset_value.sql"),
      dbScript("$dbPath/convert/5.6.3.3.RELEASE/20170221_fix_report_parameter_sequence.sql"),
      // PL/SQL Changes
      dbScript("$dbPath/plsql/create_pkg_query_behaviors_report.sql"),
      dbScript("$dbPath/plsql/create_pkg_report_behavior.sql"),
      dbScript("$dbPath/plsql/pkg_const.sql"),
      dbScript("$dbPath/plsql/pkg_extracts.sql"),
      dbScript("$dbPath/plsql/pkg_list_past_win_nominations.sql"),
      dbScript("$dbPath/plsql/pkg_list_pend_nominations.sql"),
      dbScript("$dbPath/plsql/pkg_list_recognition_wall.sql"),
      dbScript("$dbPath/plsql/pkg_nom_approver_verify_import.sql"),
      dbScript("$dbPath/plsql/pkg_query_awards_received.sql"),
      dbScript("$dbPath/plsql/pkg_query_badge_activity.sql"),
      dbScript("$dbPath/plsql/pkg_query_cash_budget_balance.sql"),
      dbScript("$dbPath/plsql/pkg_query_nomi_aging.sql"),
      dbScript("$dbPath/plsql/pkg_query_nomi_given.sql"),
      dbScript("$dbPath/plsql/pkg_query_nomi_receive.sql"),
      dbScript("$dbPath/plsql/pkg_query_nomination.sql"),
      dbScript("$dbPath/plsql/pkg_report_nomination.sql"),
      dbScript("$dbPath/plsql/pkg_query_point_budget_balance.sql"),
      dbScript("$dbPath/plsql/prc_report_refresh.sql"),
      dbScript("$dbPath/plsql/pkg_query_recog_given.sql"),
      dbScript("$dbPath/plsql/pkg_query_recog_list_of_givers.sql"),
      dbScript("$dbPath/plsql/pkg_query_recog_received.sql"),
      dbScript("$dbPath/plsql/pkg_query_recog_recipients.sql"),
      dbScript("$dbPath/plsql/pkg_report_budget.sql"),
      dbScript("$dbPath/plsql/pkg_report_cash_budget.sql"),
      dbScript("$dbPath/plsql/pkg_report_client_reports.sql"),
      dbScript("$dbPath/plsql/prc_custom_approver_list_cas.sql"),
      dbScript("$dbPath/plsql/prc_budget_transfer.sql")
    ]
  ],

  convert_5632_to_60: [
    task: true,
    description: "Converts database from 5.6.3.2 to 6.0 Release",
    group: project.ext.databaseConvertGroup,
    actions: [
      // Confirmation
      dbSublist("convert_confirmation"),
      // Schema changes
      dbScript("$dbPath/convert/6.0.RELEASE/201607260929_alter_filter_module_app.sql"),
      dbScript("$dbPath/convert/6.0.RELEASE/20160901_alter_rpt_recognition_detail.sql"),
      dbScript("$dbPath/convert/6.0.RELEASE/20161003_alter_application_user.sql"),
      dbScript("$dbPath/convert/6.0.RELEASE/20161003_create_user_pwd_history.sql"),
      dbScript("$dbPath/convert/6.0.RELEASE/20161020_alter_module_app.sql"),
      dbScript("$dbPath/convert/6.0.RELEASE/20161028_create_ssi_admin_actions.sql"),
      dbScript("$dbPath/convert/6.0.RELEASE/20161104_create_ssi_contest_superviewer.sql"),
      dbScript("$dbPath/convert/6.0.RELEASE/20161116_create_stage_ssi_import.sql"),
      dbScript("$dbPath/convert/6.0.RELEASE/20161121_alter_journal.sql"),
      dbScript("$dbPath/convert/6.0.RELEASE/20161230_create_core_public_recognition_user_connections.sql"),
      dbScript("$dbPath/convert/6.0.RELEASE/20161230_create_core_tmp_audience_user_id.sql"),
      dbScript("$dbPath/schema/create_mv_cms_badge.sql"),
      dbScript("$dbPath/convert/6.0.RELEASE/20161409_update_module_app.sql"),
      dbScript("$dbPath/convert/6.0.RELEASE/20161224_diy_news.sql"),
      dbScript("$dbPath/convert/6.0.RELEASE/20161224_diy_banner.sql"),
      dbScript("$dbPath/convert/6.0.RELEASE/20161003_insert_os_propertyset.sql"),
      dbScript("$dbPath/convert/6.0.RELEASE/20161122_alter_os_propertyset.sql"),
      dbScript("$dbPath/convert/6.0.RELEASE/2016_12_05_insert_os_propertyset.sql"),
      dbScript("$dbPath/convert/6.0.RELEASE/20161220_drop_pkg_report_recog_behavior.sql"),
      // PL/SQL Changes
      dbScript("$dbPath/plsql/create_pkg_ssi_atn_load.sql"),
      dbScript("$dbPath/plsql/create_pkg_ssi_dtgt_load.sql"),
      dbScript("$dbPath/plsql/create_pkg_ssi_objective_load.sql"),
      dbScript("$dbPath/plsql/create_pkg_ssi_stack_rank_load.sql"),
      dbScript("$dbPath/plsql/create_pkg_ssi_step_it_up_load.sql"),
      dbScript("$dbPath/plsql/create_prc_get_user_info.sql"),
      dbScript("$dbPath/plsql/create_prc_ssi_contest_extract.sql"),
      dbScript("$dbPath/plsql/fnc_get_osp_int.sql"),
      dbScript("$dbPath/plsql/pkg_bulk_pax_stage.sql"),
      dbScript("$dbPath/plsql/pkg_const.sql"),
      dbScript("$dbPath/plsql/pkg_engagement_extract.sql"),
      dbScript("$dbPath/plsql/pkg_extracts.sql"),
      dbScript("$dbPath/plsql/pkg_hierarchy_verify_import.sql"),
      dbScript("$dbPath/plsql/pkg_list_past_win_nominations.sql"),
      dbScript("$dbPath/plsql/pkg_list_recognition_wall.sql"),
      dbScript("$dbPath/plsql/pkg_participant_verify_import.sql"),
      dbScript("$dbPath/plsql/pkg_report_recognition.sql"),
      dbScript("$dbPath/plsql/pkg_ssi_contest.sql"),
      dbScript("$dbPath/plsql/prc_purl_celebration_page.sql"),
      dbScript("$dbPath/plsql/prc_report_refresh.sql"),
      dbScript("$dbPath/plsql/pkg_report_common.sql"),
      dbScript("$dbPath/plsql/prc_ssi_progress_load.sql")
    ]
  ],

  convert_5633_to_61: [
    task: true,
    description: "Converts database from 5.6.3.3 to 6.1 Release",
    group: project.ext.databaseConvertGroup,
    actions: [
      // Confirmation
      dbSublist("convert_confirmation"),
      // Schema changes to convert to 6.0 Release
      dbScript("$dbPath/convert/6.0.RELEASE/201607260929_alter_filter_module_app.sql"),
      dbScript("$dbPath/convert/6.0.RELEASE/20160901_alter_rpt_recognition_detail.sql"),
      dbScript("$dbPath/convert/6.0.RELEASE/20161003_alter_application_user.sql"),
      dbScript("$dbPath/convert/6.0.RELEASE/20161003_create_user_pwd_history.sql"),
      dbScript("$dbPath/convert/6.0.RELEASE/20161020_alter_module_app.sql"),
      dbScript("$dbPath/convert/6.0.RELEASE/20161028_create_ssi_admin_actions.sql"),
      dbScript("$dbPath/convert/6.0.RELEASE/20161104_create_ssi_contest_superviewer.sql"),
      dbScript("$dbPath/convert/6.0.RELEASE/20161116_create_stage_ssi_import.sql"),
      dbScript("$dbPath/convert/6.0.RELEASE/20161121_alter_journal.sql"),
      dbScript("$dbPath/convert/6.0.RELEASE/20161230_create_core_public_recognition_user_connections.sql"),
      dbScript("$dbPath/convert/6.0.RELEASE/20161230_create_core_tmp_audience_user_id.sql"),
      dbScript("$dbPath/schema/create_mv_cms_badge.sql"),
      dbScript("$dbPath/convert/6.0.RELEASE/20161409_update_module_app.sql"),
      dbScript("$dbPath/convert/6.0.RELEASE/20161224_diy_news.sql"),
      dbScript("$dbPath/convert/6.0.RELEASE/20161224_diy_banner.sql"),
      dbScript("$dbPath/convert/6.0.RELEASE/20161003_insert_os_propertyset.sql"),
      dbScript("$dbPath/convert/6.0.RELEASE/20161122_alter_os_propertyset.sql"),
      dbScript("$dbPath/convert/6.0.RELEASE/2016_12_05_insert_os_propertyset.sql"),
      // Schema changes to convert to 6.1 Release
      dbScript("$dbPath/convert/6.1.RELEASE/20170120_create_ssi_contest_bill_code.sql"),
      dbScript("$dbPath/convert/6.1.RELEASE/20161128_insert_message.sql"),
      dbScript("$dbPath/convert/6.1.RELEASE/20161129_alter_import_file.sql"),
      dbScript("$dbPath/convert/6.1.RELEASE/20161215_insert_os_property_set.sql"),
      dbScript("$dbPath/convert/6.1.RELEASE/20170109_delete_cms_content.sql"),
      dbScript("$dbPath/convert/6.1.RELEASE/20170111_alter_application_user.sql"),
      dbScript("$dbPath/convert/6.1.RELEASE/20170111_alter_journal.sql"),
      dbScript("$dbPath/convert/6.1.RELEASE/20170113_alter_promo_bill_code.sql"),
      dbScript("$dbPath/convert/6.1.RELEASE/20170120_alter_stage_ssi_import.sql"),
      dbScript("$dbPath/convert/6.1.RELEASE/20170123_update_os_property_set.sql"),
      dbScript("$dbPath/convert/6.1.RELEASE/20170127_create_merch_order_bill_code.sql"),
      dbScript("$dbPath/convert/6.1.RELEASE/20170202_drop_java_sha.sql"),
      dbScript("$dbPath/convert/6.1.RELEASE/20170313_alter_report_parameter.sql"),
      dbScript("$dbPath/schema/create_index_performance.sql"),
      dbScript("$dbPath/schema/create_mv_cms_asset_value1.sql"),
      dbScript("$dbPath/schema/create_mv_cms_asset_value2.sql"),
      dbScript("$dbPath/schema/create_mv_cms_asset_value3.sql"),
      dbScript("$dbPath/schema/create_mv_cms_code_value.sql"),
      dbScript("$dbPath/schema/create_mv_cms_user_characteristic.sql"),
      dbScript("$dbPath/convert/6.1.RELEASE/20170309_rpt_awardmedia_summary.sql"),
      dbScript("$dbPath/convert/6.1.RELEASE/20170314_update_cms_content_data_code.sql")
    ]
  ],

  convert_60_to_61: [
    task: true,
    description: "Converts database from 6.0 to 6.1 Release",
    group: project.ext.databaseConvertGroup,
    actions: [
      // Confirmation
      dbSublist("convert_confirmation"),
      // Adding 5.6.3.3 changes to this converts as 5.6.3.3 changes are cherry picked into 6.1 Release and clients who are on 6.0 (Bravo in this case) doesn't have reports changes.
      dbScript("$dbPath/convert/5.6.3.3.RELEASE/20161229_alter_badge_activity_report_parameter_tbl.sql"),
      dbScript("$dbPath/convert/5.6.3.3.RELEASE/20170103_alter_cash_budget_balance_report_parameter_tbl.sql"),
      dbScript("$dbPath/convert/5.6.3.3.RELEASE/20170124_alter_budget_report.sql"),
      dbScript("$dbPath/convert/5.6.3.3.RELEASE/20170104_alter_points_budget_balance_report_parameter_tbl.sql"),
      dbScript("$dbPath/convert/5.6.3.3.RELEASE/20170110_alter_behavior_activity_chart_report_tbl.sql"),
      dbScript("$dbPath/convert/5.6.3.3.RELEASE/20170111_alter_rpt_behavior_detail.sql"),
      dbScript("$dbPath/convert/5.6.3.3.RELEASE/20170116_alter_nominations_list_of_nominators_report_parameter_tbl.sql"),
      dbScript("$dbPath/convert/5.6.3.3.RELEASE/20170116_alter_nominations_list_of_nominees_report_parameter_tbl.sql"),
      dbScript("$dbPath/convert/5.6.3.3.RELEASE/20170117_alter_nomination_activity_by_org_report_parameter_tbl.sql"),
      dbScript("$dbPath/convert/5.6.3.3.RELEASE/20170123_alter_nomination_aging_status_report_parameter_tbl.sql"),
      dbScript("$dbPath/convert/5.6.3.3.RELEASE/20170125_alter_awards_reeived_participants_report_parameter_tbl.sql"),
      dbScript("$dbPath/convert/5.6.3.3.RELEASE/20170130_alter_awards_received_by_org_report_parameter_tbl.sql"),
      dbScript("$dbPath/convert/5.6.3.3.RELEASE/20170120_alter_journal.sql"),
      dbScript("$dbPath/convert/5.6.3.3.RELEASE/20170116_alter_core_mailing_message_locale_tbl.sql"),
      dbScript("$dbPath/convert/5.6.3.3.RELEASE/20170209_create_alter_approver_option.sql"),
      dbScript("$dbPath/convert/5.6.3.3.RELEASE/20170210_update_os_propertyset.sql"),
      dbScript("$dbPath/convert/5.6.3.3.RELEASE/20170213_create_new_table_cms_content_data_str.sql"),
      dbScript("$dbPath/convert/5.6.3.3.RELEASE/20170221_fix_report_parameter_sequence.sql"),
      // Schema changes
      dbScript("$dbPath/convert/6.1.RELEASE/20170120_create_ssi_contest_bill_code.sql"),
      dbScript("$dbPath/convert/6.1.RELEASE/20161128_insert_message.sql"),
      dbScript("$dbPath/convert/6.1.RELEASE/20161129_alter_import_file.sql"),
      dbScript("$dbPath/convert/6.1.RELEASE/20161215_insert_os_property_set.sql"),
      dbScript("$dbPath/convert/6.1.RELEASE/20170109_delete_cms_content.sql"),
      dbScript("$dbPath/convert/6.1.RELEASE/20170111_alter_application_user.sql"),
      dbScript("$dbPath/convert/6.1.RELEASE/20170111_alter_journal.sql"),
      dbScript("$dbPath/convert/6.1.RELEASE/20170113_alter_promo_bill_code.sql"),
      dbScript("$dbPath/convert/6.1.RELEASE/20170120_alter_stage_ssi_import.sql"),
      dbScript("$dbPath/convert/6.1.RELEASE/20170123_update_os_property_set.sql"),
      dbScript("$dbPath/convert/6.1.RELEASE/20170127_create_merch_order_bill_code.sql"),
      dbScript("$dbPath/convert/6.1.RELEASE/20170202_drop_java_sha.sql"),
      dbScript("$dbPath/convert/6.1.RELEASE/20170313_alter_report_parameter.sql"),
      dbScript("$dbPath/schema/create_index_performance.sql"),
      dbScript("$dbPath/schema/create_mv_cms_asset_value1.sql"),
      dbScript("$dbPath/schema/create_mv_cms_asset_value2.sql"),
      dbScript("$dbPath/schema/create_mv_cms_asset_value3.sql"),
      dbScript("$dbPath/schema/create_mv_cms_code_value.sql"),
      dbScript("$dbPath/schema/create_mv_cms_user_characteristic.sql"),
      dbScript("$dbPath/schema/create_vw_cms_asset_value.sql"),
      dbScript("$dbPath/convert/6.1.RELEASE/20170309_rpt_awardmedia_summary.sql"),
      dbScript("$dbPath/convert/6.1.RELEASE/20170314_update_cms_content_data_code.sql")
    ]
  ],

  convert_61_to_62: [
    task: true,
    description: "Converts database from 6.1 to 6.2 Release",
    group: project.ext.databaseConvertGroup,
    actions: [
      // Confirmation
      dbSublist("convert_confirmation"),
      
      //2nd Security Patch role changes. If client has already applied these security patches, these scripts are likely to fail. Please ignore the errors.
      dbScript("$dbPath/convert/6.2.RELEASE/20170315_insert_message.sql"),
      dbScript("$dbPath/convert/6.2.RELEASE/20170321_delete_roles.sql"),
      dbScript("$dbPath/convert/6.2.RELEASE/20170321_insert_role.sql"),
      
      // Schema changes
      dbScript("$dbPath/convert/6.2.RELEASE/20170317_alter_promo_recognition.sql"),
      dbScript("$dbPath/convert/6.2.RELEASE/20170223_create_core_user_tnc_history.sql"),
      dbScript("$dbPath/convert/6.2.RELEASE/20170322_alter_os_property_set.sql"),
      dbScript("$dbPath/convert/6.2.RELEASE/20170323_alter_participant.sql"),
      dbScript("$dbPath/convert/6.2.RELEASE/20170324_alter_promo_goalquest.sql"),
      dbScript("$dbPath/convert/6.2.RELEASE/20170324_insert_os_property_set.sql"),
      dbScript("$dbPath/convert/6.2.RELEASE/20170323_insert_os_property_set.sql"),
      dbScript("$dbPath/convert/6.2.RELEASE/20170324_alter_participant.sql"),
      dbScript("$dbPath/convert/6.2.RELEASE/20172903_drop_sequence.sql"),
      dbScript("$dbPath/convert/6.2.RELEASE/20170519_create_sequence.sql"),
      dbScript("$dbPath/convert/6.2.RELEASE/20170405_insert_report_workhappier.sql"),
      dbScript("$dbPath/convert/6.2.RELEASE/20170407_alter_module_app.sql"),
      dbScript("$dbPath/convert/6.2.RELEASE/20170413_update_google_cloud_server_id.sql"),
      dbScript("$dbPath/convert/6.2.RELEASE/20170419_delete_ios_user_devices.sql"),
      //WorkHappier report refresh..this is included as we need complete refresh of WorkHappier report table.
      dbScript("$dbPath/convert/6.2.RELEASE/20170405_rpt_work_happier_refresh.sql"),
      dbScript("$dbPath/convert/6.2.RELEASE/20170417_drop_workhappier_extract.sql"),
      dbScript("$dbPath/convert/6.2.RELEASE/20170410_alter_report_parameter.sql"),
      dbScript("$dbPath/convert/6.2.RELEASE/20170410_alter_tmp_nomi_approver_detail.sql"),
      dbScript("$dbPath/convert/6.2.RELEASE/20170414_alter_workhappier_text.sql"),
      dbScript("$dbPath/convert/6.2.RELEASE/20170414_alter_os_propertyset.sql"),
      dbScript("$dbPath/convert/6.2.RELEASE/20170414_alter_report.sql"),
      dbScript("$dbPath/convert/6.2.RELEASE/20170418_alter_leaderboard.sql"),
      dbScript("$dbPath/convert/6.2.RELEASE/20170421_insert_os_propertyset.sql"),
      dbScript("$dbPath/convert/6.2.RELEASE/20170421_drop_rpt_recognition_summary.sql"),
      dbScript("$dbPath/convert/6.2.RELEASE/20170421_prc_conv_script_pax_term_date.sql"),
      dbScript("$dbPath/convert/6.2.RELEASE/20170421_exec_prc_conv_script_pax_term_date.sql"),
      dbScript("$dbPath/convert/6.2.RELEASE/20170426_alter_rpt_budget_usage_detail.sql"),
      dbScript("$dbPath/convert/6.2.RELEASE/20170428_new_ecards.sql"),
      dbScript("$dbPath/convert/6.2.RELEASE/20170503_alter_promo_goalquest.sql"),
      dbScript("$dbPath/convert/6.2.RELEASE/20170504_alter_ecard_locale.sql"),
      dbScript("$dbPath/convert/6.2.RELEASE/20170503_insert_message.sql"),
      dbScript("$dbPath/convert/6.2.RELEASE/20170512_refresh_rpm_from_scratch.sql"),
      dbScript("$dbPath/convert/6.2.RELEASE/20170512_os_propertyset_cleanup.sql"),
      dbScript("$dbPath/convert/6.2.RELEASE/20170517_fix_cumm_nom_reports_data.sql"),
      dbScript("$dbPath/convert/6.2.RELEASE/20170516_insert_os_property_set.sql"),
      dbScript("$dbPath/convert/6.2.RELEASE/20170602_alter_participant.sql")
    ]
  ]
]
