installation:
    pid: "01192016"
    useUrl: true
    propertiesUrl: "http://beaconqa.biworldwide.com/g3installwizard/exportProject.do?pid=${project.config.installation.pid}"
    propertiesProdUrl: "http://beacon.biworldwide.com/g3installwizard/exportProject.do?pid=${project.config.installation.pid}"
    bonfire: true

database:
    driver: "oracle.jdbc.driver.OracleDriver"
    jdbcUrl: "jdbc:oracle:thin:@localhost:49161:XE"
    port: 49161
    name: "beacon"
    userName: "beacon"
    password: "beacon"

cmdiff:
    baseDir: "D:/projects/cmdiff"
    cpdBaseDir: "//ss3/ndstat/java/GSeries/Product-g-cmdiffs"
    importExportFilePath: "src/main/resources/db/cmData.xml"
    goldcopyImportExportFilePath: "src/main/resources/db/cmData-goldcopy.xml"
    goldcopyDifftFilePath: "src/main/resources/db/cmDiff-goldcopy.xml"
    goldcopyCmDiff: true #Should be set to true only for development branch
    importLogError: "false"

unittest:
    debug: false
    driver: "oracle.jdbc.driver.OracleDriver"
    jdbcUrl: "jdbc:oracle:thin:@database:1521:XE"
    port: 1521
    name: "beacon"
    userName: "beacon"
    password: "beacon"
