UPDATE MODULE_APP SET AVAILABLE_SIZES='4X4,4X2,2X2,2X1,1X1', APP_AUDIENCE_TYPE='claimModule', TILE_MAPPING_TYPE='claimModule', UI_APP_NAME='claimModule'
	WHERE MODULE_APP_ID=3004
/
UPDATE MODULE_APP SET TILE_MAPPING_TYPE='recognitionModule'
	WHERE MODULE_APP_ID=3005
/
UPDATE MODULE_APP SET AUDIENCE_TYPE='allactivepaxaudience', APP_AUDIENCE_TYPE='forumModule', TILE_MAPPING_TYPE='forumModule', UI_APP_NAME='forum'
	WHERE MODULE_APP_ID=3016
/
UPDATE MODULE_APP SET APP_AUDIENCE_TYPE='goalquestModule', TILE_MAPPING_TYPE='goalquestModule', UI_APP_NAME='goalquest'
	WHERE MODULE_APP_ID=3017
/
INSERT INTO MODULE_APP
   (MODULE_APP_ID,NAME,DESCRIPTION,IS_MOBILE_ENABLED,AVAILABLE_SIZES,AUDIENCE_TYPE, APP_AUDIENCE_TYPE, TILE_MAPPING_TYPE,  UI_APP_NAME,ADMIN_AUDIENCE_SETUP, CREATED_BY, DATE_CREATED,VERSION)
VALUES
   (3031, 'ChallengePoint', 'Desc - ChallengePoint ',0, '4X4,4X2,2X2,2X1,1X1','allactivepaxaudience','challengepointModule','challengepointModule', 'goalquest',0,5662, sysdate, 1)
/
INSERT INTO MODULE_APP
   (MODULE_APP_ID,NAME,DESCRIPTION,IS_MOBILE_ENABLED,AVAILABLE_SIZES,AUDIENCE_TYPE, APP_AUDIENCE_TYPE, TILE_MAPPING_TYPE,  UI_APP_NAME,ADMIN_AUDIENCE_SETUP, CREATED_BY, DATE_CREATED,VERSION)
VALUES
   (3032, 'Manager GoalQuest', 'Desc - Manager tile for GQ',0, '4X4,4X2,2X2,2X1,1X1','allactivepaxaudience','goalquestManagerModule','goalquestManagerModule', 'goalquest',0,5662, sysdate, 1)
/
INSERT INTO MODULE_APP
   (MODULE_APP_ID,NAME,DESCRIPTION,IS_MOBILE_ENABLED,AVAILABLE_SIZES,AUDIENCE_TYPE, APP_AUDIENCE_TYPE, TILE_MAPPING_TYPE,  UI_APP_NAME,ADMIN_AUDIENCE_SETUP, CREATED_BY, DATE_CREATED,VERSION)
VALUES
   (3033, 'Manager Challengepoint', 'Desc - Manager tile for CP',0, '4X4,4X2,2X2,2X1,1X1','allactivepaxaudience','challengepointManagerModule','challengepointManagerModule', 'goalquest',0,5662, sysdate, 1)
/