CREATE TABLE FORUM_DISCUSSION_LIKE
   (DISCUSSION_ID     			NUMBER(18) NOT NULL,
    USER_ID  		            NUMBER(18) NOT NULL,
    CONSTRAINT DISCUSSION_LIKE_DISID_FK FOREIGN KEY (DISCUSSION_ID) REFERENCES FORUM_DISCUSSION (DISCUSSION_ID),
    CONSTRAINT DISCUSSION_LIKE_USERID_FK FOREIGN KEY (USER_ID) REFERENCES APPLICATION_USER (USER_ID)
   ) 
/
