ALTER TABLE STRONGMAIL_USER
ADD (FIRST_NAME  VARCHAR2(40 CHAR),
    LAST_NAME   VARCHAR2(40 CHAR),
    USER_NAME   VARCHAR2(40 CHAR) NOT NULL,
    EMAIL_ADDR  VARCHAR2(75 CHAR) NOT NULL,
    EMAIL_STATUS VARCHAR2(40 CHAR),
    COMPANY     VARCHAR2(200 CHAR),
    WEBSITE_URL VARCHAR2(500 CHAR),
    CONTACT_URL VARCHAR2(500 CHAR),
    LANGUAGE_ID VARCHAR2(10 CHAR) NOT NULL)
/
ALTER TABLE STRONGMAIL_USER DROP COLUMN USER_ID
/
