DROP TABLE stage_gq_base_data_import CASCADE CONSTRAINTS
/
DROP TABLE stage_gq_goal_data_import CASCADE CONSTRAINTS
/
DROP TABLE stage_gq_progress_data_import CASCADE CONSTRAINTS
/
DROP TABLE goalquest_paxgoal CASCADE CONSTRAINTS
/
DROP TABLE stage_gq_vin_nbr_import CASCADE CONSTRAINTS
/
DROP TABLE goalquest_survey CASCADE CONSTRAINTS
/
DROP TABLE rpt_goal_selection_detail CASCADE CONSTRAINTS
/
DROP TABLE RPT_CP_SELECTION_DETAIL CASCADE CONSTRAINTS
/
DROP TABLE STAGE_CP_BASE_DATA_IMPORT CASCADE CONSTRAINTS
/
DROP TABLE STAGE_CP_DATA_IMPORT CASCADE CONSTRAINTS
/
DROP TABLE STAGE_CP_PROGRESS_DATA_IMPORT CASCADE CONSTRAINTS
/
DROP TABLE rpt_goal_selection_summary CASCADE CONSTRAINTS
/
DROP TABLE promo_goalquest CASCADE CONSTRAINTS
/
DROP TABLE goalquest_goallevel CASCADE CONSTRAINTS
/
DROP TABLE goalquest_paxgoal CASCADE CONSTRAINTS
/
DROP TABLE goalquest_participant_activity CASCADE CONSTRAINTS
/
DROP TABLE PARTICIPANT_PARTNER CASCADE CONSTRAINTS
/
DROP TABLE RPT_GOAL_ROI CASCADE CONSTRAINTS
/
DROP TABLE rpt_goal_partner CASCADE CONSTRAINTS
/
DROP TABLE promo_challengepoint CASCADE CONSTRAINTS
/
DROP TABLE challengepoint_award CASCADE CONSTRAINTS
/
DROP TABLE challengepoint_progress CASCADE CONSTRAINTS
/
DROP TABLE RPT_CP_SELECTION_SUMMARY CASCADE CONSTRAINTS
/
DROP TABLE RPT_CP_PRODUCTION CASCADE CONSTRAINTS
/
DROP SEQUENCE promo_goalquest_survey_pk_sq
/
DROP SEQUENCE rpt_goal_selection_detail_sq
/
DROP SEQUENCE RPT_CP_SELECTION_DETAIL_SQ
/
DROP SEQUENCE rpt_goal_selection_summary_sq
/
DROP SEQUENCE goalquest_goallevel_pk_sq
/
DROP SEQUENCE GOALQUEST_PAXGOAL_PK_SQ
/
DROP SEQUENCE goalquest_pax_activity_pk_sq
/
DROP SEQUENCE PARTICIPANT_PARTNER_PK_SQ
/
DROP SEQUENCE RPT_GOAL_ROI_SQ
/
DROP SEQUENCE rpt_goal_partner_pk_sq
/
DROP SEQUENCE CHALLENGEPOINT_AWARD_PK_SQ
/
DROP SEQUENCE challengepoint_progress_pk_sq
/
DROP SEQUENCE RPT_CP_SELECTION_SUMMARY_SQ
/
DROP SEQUENCE RPT_CP_PRODUCTION_SQ
/