CREATE SEQUENCE AWARDGEN_MANAGER_PK_SQ INCREMENT BY 1 START WITH 5000 
/
CREATE TABLE AWARDGEN_MANAGER
( AWARDGEN_MANAGER_ID NUMBER(18) NOT NULL,
  AWARDGEN_BATCH_ID NUMBER(18) NOT NULL,
  USER_ID NUMBER(18) NOT NULL,
  AWARDGEN_PARTICIPANT_ID NUMBER(18),
  EXPIRY_DATE DATE,
  CREATED_BY NUMBER(18),
  DATE_CREATED DATE NOT NULL,
  MODIFIED_BY NUMBER(18),
  DATE_MODIFIED DATE,
  VERSION NUMBER(18) NOT NULL)
/
ALTER TABLE AWARDGEN_MANAGER ADD
  CONSTRAINT AWARDGEN_MANAGER_PK PRIMARY KEY (AWARDGEN_MANAGER_ID)
/
ALTER TABLE AWARDGEN_MANAGER ADD CONSTRAINT AWARDGEN_MGR_BATCH_FK
  FOREIGN KEY (AWARDGEN_BATCH_ID) REFERENCES AWARDGEN_BATCH (AWARDGEN_BATCH_ID)
/