CREATE TABLE FORUM_TOPIC_AUDIENCE
   (AUDIENCE_ID                 NUMBER(18) NOT NULL,
    FORUM_TOPIC_ID     			NUMBER(18) NOT NULL,
    CONSTRAINT FORUM_TOPIC_audienceId_FK FOREIGN KEY (AUDIENCE_ID) REFERENCES AUDIENCE (AUDIENCE_ID),
    CONSTRAINT FORUM_TOPIC_topicId_FK FOREIGN KEY (FORUM_TOPIC_ID) REFERENCES FORUM_TOPIC (FORUM_TOPIC_ID)
   ) 
/
