CREATE SEQUENCE FORUM_DISCUSSION_PK_SQ INCREMENT BY 1 START WITH 1
/
CREATE TABLE FORUM_DISCUSSION
   (DISCUSSION_ID     			NUMBER(18) NOT NULL,
    FORUM_TOPIC_ID     			NUMBER(18) NOT NULL,
    PARENT_DISCUSSION_ID        NUMBER(18),
    DISCUSSION_TITLE 			VARCHAR2(150),
    DISCUSSION_BODY  			VARCHAR2(4000),
    USER_ID  		            NUMBER(18),
    IS_REPLY                    NUMBER(1),
    STATUS                      VARCHAR2(1),
    CREATED_BY   				NUMBER(18),
    DATE_CREATED 				DATE,
    MODIFIED_BY  				NUMBER(18),
    DATE_MODIFIED 				DATE,
    VERSION 					NUMBER(18) NOT NULL,
    CONSTRAINT FORUM_DISCUSSION_PK PRIMARY KEY (DISCUSSION_ID),
    CONSTRAINT FORUM_DISCUSSION_FK FOREIGN KEY (FORUM_TOPIC_ID) REFERENCES FORUM_TOPIC (FORUM_TOPIC_ID),
    CONSTRAINT FORUM_DISCUSSION_USER_FK FOREIGN KEY (USER_ID) REFERENCES APPLICATION_USER (USER_ID)
   ) 
/
