CREATE SEQUENCE AWARDGEN_PARTICIPANT_PK_SQ INCREMENT BY 1 START WITH 5000 
/
CREATE TABLE AWARDGEN_PARTICIPANT
( AWARDGEN_PARTICIPANT_ID NUMBER(18) NOT NULL,
  AWARDGEN_BATCH_ID NUMBER(18) NOT NULL,
  USER_ID NUMBER(18) NOT NULL,
  LEVEL_ID NUMBER(18),
  AWARD_AMOUNT NUMBER(18),
  ANNIVERSARY_DATE DATE,
  ISSUE_DATE DATE,
  IS_DISMISSED VARCHAR2(1),
  CREATED_BY NUMBER(18),
  DATE_CREATED DATE NOT NULL,
  MODIFIED_BY NUMBER(18),
  DATE_MODIFIED DATE,
  VERSION NUMBER(18) NOT NULL)
/
ALTER TABLE AWARDGEN_PARTICIPANT ADD
  CONSTRAINT AWARDGEN_PARTICIPANT_PK PRIMARY KEY (AWARDGEN_PARTICIPANT_ID)
/
ALTER TABLE AWARDGEN_PARTICIPANT ADD CONSTRAINT AWARDGEN_PAX_BATCH_FK
  FOREIGN KEY (AWARDGEN_BATCH_ID) REFERENCES AWARDGEN_BATCH (AWARDGEN_BATCH_ID)
/
