CREATE OR REPLACE FORCE VIEW SM_CP_PAX_ACHIEVED_VW
(
   MAILING_ID,
   USER_ID,
   LOCALE,
   BATCH_ID,
   EMAIL_ADDR,   
   FIRST_NAME,
   LAST_NAME,   
   PROGRAM_NAME,
   BASE,
   PROMOTION_END_DATE ,
   primaryAwardIncrement ,
   primaryAward ,
   totalChallengepointValue ,
   actual_results , 
   percentToChallengepoint,
   date_1,
   AWARD_PERQS,
   actualResults,
   primaryEarnings,
   interimAmount,
   remainingPoints,
   calculationapprovedate,
   rewardAmount,
   totalRewardAmount,
   totalPreviousDeposit,
   merchandiseTravelType,
   mgr,
   nonmgr,
   SITE_LINK,
   CONTACT_US_URL
)
AS
     SELECT r.mailing_id,
            r.user_id,
            r.locale,
            m.batch_id,
            ue.email_addr,            
            MAX (DECODE (d.data_key, 'firstName', d.data_value, NULL)) firstName,
            MAX (DECODE (d.data_key, 'lastName', d.data_value, NULL)) lastName,            
            MAX (DECODE (d.data_key, 'programName', d.data_value, NULL)) programName,
            MAX (DECODE (d.data_key, 'base', d.data_value, NULL)) base,
            MAX (DECODE (d.data_key, 'promotionEndDate', d.data_value, NULL)) promotionEndDate,
            MAX (DECODE (d.data_key, 'primaryAwardIncrement', d.data_value, NULL)) primaryAwardIncrement,
            MAX (DECODE (d.data_key, 'primaryAward', d.data_value, NULL)) primaryAward,
            MAX (DECODE (d.data_key, 'totalChallengepointValue', d.data_value, NULL)) totalChallengepointValue,
            MAX (DECODE (d.data_key, 'actual_results', d.data_value, NULL)) actual_results,
            MAX (DECODE (d.data_key, 'percentToChallengepoint', d.data_value, NULL)) percentToChallengepoint,
            MAX (DECODE (d.data_key, 'date', d.data_value, NULL)) date_1,
            MAX (DECODE (d.data_key, 'points', d.data_value, NULL)) points,
            MAX (DECODE (d.data_key, 'actualResults', d.data_value, NULL)) actualResults,
            MAX (DECODE (d.data_key, 'primaryEarnings', d.data_value, NULL)) primaryEarnings,
            MAX (DECODE (d.data_key, 'interimAmount', d.data_value, NULL)) interimAmount,
            MAX (DECODE (d.data_key, 'remainingPoints', d.data_value, NULL)) remainingPoints,
            MAX (DECODE (d.data_key, 'calculationapprovedate', d.data_value, NULL)) calculationapprovedate,   
            MAX (DECODE (d.data_key, 'rewardAmount', d.data_value, NULL)) rewardAmount,
            MAX (DECODE (d.data_key, 'totalRewardAmount', d.data_value, NULL)) totalRewardAmount,
            MAX (DECODE (d.data_key, 'totalPreviousDeposit', d.data_value, NULL)) totalPreviousDeposit,
            MAX (DECODE (d.data_key, 'merchandiseTravelType', d.data_value, NULL)) merchandiseTravelType,
            MAX (DECODE (d.data_key, 'mgr', d.data_value, NULL)) mgr,
            MAX (DECODE (d.data_key, 'nonmgr', d.data_value, NULL)) nonmgr,
            MAX (DECODE (d.data_key, 'siteLink', d.data_value, NULL)) siteLink,
            MAX (DECODE (d.data_key, 'contactUsUrl', d.data_value, NULL)) contactUsUrl
       FROM mailing_recipient r, mailing_recipient_data d, mailing m, user_email_address ue
      WHERE m.batch_id is not null 
        AND r.MAILING_RECIPIENT_ID = d.MAILING_RECIPIENT_ID
        AND m.mailing_id = r.mailing_id       
        AND d.data_key IN ( 'firstName','lastName' , 'programName' ,'base' , 'promotionEndDate' , 'primaryAwardIncrement' , 'primaryAward' , 'totalChallengepointValue' , 'actual_results' , 'percentToChallengepoint','date','points',  
		   'actualResults',
		   'primaryEarnings',
		   'interimAmount',
		   'remainingPoints',
		   'calculationapprovedate',
		   'rewardAmount',
		   'totalRewardAmount',
		   'totalPreviousDeposit',
		   'merchandiseTravelType',
		   'mgr',
		   'nonmgr',
		   'siteLink',
		   'contactUsUrl')
        AND ue.user_id = r.user_id
        AND ue.is_primary = 1        
   GROUP BY R.USER_ID, R.MAILING_ID, R.LOCALE , M.BATCH_ID, UE.EMAIL_ADDR
/