ALTER TABLE RPT_AWARD_EARNINGS
ADD CHARACTERISTIC_VALUE6  VARCHAR2(400 BYTE)
/
ALTER TABLE RPT_AWARD_EARNINGS
ADD CHARACTERISTIC_VALUE7  VARCHAR2(400 BYTE)
/
ALTER TABLE RPT_AWARD_EARNINGS
ADD CHARACTERISTIC_VALUE8  VARCHAR2(400 BYTE)
/
ALTER TABLE RPT_AWARD_EARNINGS
ADD CHARACTERISTIC_VALUE9  VARCHAR2(400 BYTE)
/
ALTER TABLE RPT_AWARD_EARNINGS
ADD CHARACTERISTIC_VALUE10  VARCHAR2(400 BYTE)
/
ALTER TABLE RPT_AWARD_EARNINGS
ADD CHARACTERISTIC_VALUE11  VARCHAR2(400 BYTE)
/
ALTER TABLE RPT_AWARD_EARNINGS
ADD CHARACTERISTIC_VALUE12  VARCHAR2(400 BYTE)
/
ALTER TABLE RPT_AWARD_EARNINGS
ADD CHARACTERISTIC_VALUE13  VARCHAR2(400 BYTE)
/
ALTER TABLE RPT_AWARD_EARNINGS
ADD CHARACTERISTIC_VALUE14  VARCHAR2(400 BYTE)
/
ALTER TABLE RPT_AWARD_EARNINGS
ADD CHARACTERISTIC_VALUE15  VARCHAR2(400 BYTE)
/

  
  
  
  
  
  
  
  
  
  
