ALTER TABLE promotion
ADD BILLS_ACTIVE 	NUMBER(1,0) DEFAULT 0
/
ALTER TABLE promotion
MODIFY BILLS_ACTIVE NOT NULL
/
ALTER TABLE promotion
ADD TRACK_BILLS_BY 		    VARCHAR2(10)
/
ALTER TABLE promotion
ADD PRIMARY_BILL_CODE   	VARCHAR2(100)
/
ALTER TABLE promotion
ADD PRIMARY_CUSTOM_VALUE    VARCHAR2(50)
/
ALTER TABLE promotion
ADD SECONDARY_BILL_CODE	    VARCHAR2(100)
/
ALTER TABLE promotion
ADD SECONDARY_CUSTOM_VALUE	VARCHAR2(100) 
/
ALTER TABLE promotion
ADD SWP_BILLS_ACTIVE 	NUMBER(1,0) DEFAULT 0
/
ALTER TABLE promotion
MODIFY SWP_BILLS_ACTIVE NOT NULL
/
ALTER TABLE promotion
ADD SWP_PRIMARY_BILL_CODE	VARCHAR2(100) 
/
ALTER TABLE promotion
ADD SWP_PRIMARY_CUSTOM_VALUE VARCHAR2(50) 
/
ALTER TABLE promotion
ADD SWP_SECONDARY_BILL_CODE	VARCHAR2(100) 
/
ALTER TABLE promotion
ADD SWP_SECONDARY_CUSTOM_VALUE	VARCHAR2(100) 

 
 