ALTER TABLE RPT_AWARD_ITEM_ACTIVITY
ADD NODE_ID  			NUMBER(18)
/
ALTER TABLE RPT_AWARD_ITEM_ACTIVITY
ADD AWARD_DATE   		DATE
/
ALTER TABLE RPT_AWARD_ITEM_ACTIVITY
ADD CREATED_BY          NUMBER(18)
/
ALTER TABLE RPT_AWARD_ITEM_ACTIVITY
ADD DATE_CREATED        DATE
/
ALTER TABLE RPT_AWARD_ITEM_ACTIVITY
ADD MODIFIED_BY         NUMBER(18)
/
ALTER TABLE RPT_AWARD_ITEM_ACTIVITY
ADD DATE_MODIFIED       DATE
/
  
  
  
  
  