--
--SET DEFAULT HIERARCHY_NODE_TYPE
--
INSERT INTO node_type
(NODE_TYPE_ID,CM_ASSET_CODE,NAME_CM_KEY,IS_DELETED,CREATED_BY,DATE_CREATED,MODIFIED_BY,DATE_MODIFIED,VERSION)
VALUES
(4000,'hierarchy.hierarchy','DEFAULT_NODE_TYPE',0,0,sysdate,NULL,NULL,0)
/
