CREATE SEQUENCE file_store_pk_sq START WITH 250 INCREMENT BY 1
/
CREATE TABLE FILE_STORE
   (
    FILE_STORE_ID                    NUMBER(18) NOT NULL,
    USER_ID                         NUMBER(18) NOT NULL,
    USER_FILE_NAME                    VARCHAR2( 255 CHAR) NOT NULL,
    INTERNAL_FILE_NAME                    VARCHAR2( 255 CHAR) NOT NULL,
    FILE_STORE_TYPE                    VARCHAR2(80) NOT NULL,
    DOWNLOADED                        NUMBER(1) DEFAULT 0,
    DATE_GENERATED                  DATE,
    CONSTRAINT FILE_STORE_PK PRIMARY KEY (FILE_STORE_ID))
/
ALTER TABLE FILE_STORE ADD CONSTRAINT FILE_USER_FK
  FOREIGN KEY (USER_ID) REFERENCES APPLICATION_USER (USER_ID) 
/