UPDATE REPORT SET REPORT_CODE ='loginActivityOrg' WHERE REPORT_CODE='loginActivity'
/
UPDATE REPORT_PARAMETER SET PARAMETER_GROUP = UPPER(PARAMETER_GROUP)
/
UPDATE REPORT_DASHBOARD_ITEM SET NODE_AND_BELOW=1 WHERE NODE_AND_BELOW IS NULL
/
UPDATE REPORT_PARAMETER SET PARAMETER_GROUP = 'TIME_FRAME' WHERE PARAMETER_GROUP = 'TIMEFRAME'
/
UPDATE REPORT_PARAMETER SET PARAMETER_GROUP = 'EXPORT_SELECTION' WHERE PARAMETER_GROUP = 'EXPORT SELECTION'
/
