CREATE TABLE promo_ssi
(
	PROMOTION_ID           		   NUMBER(18) NOT NULL,
	SELECTED_CONTESTS			   NUMBER(12),
	ALLOW_AWARD_POINTS			   NUMBER(1) DEFAULT 0 NOT NULL,
	ALLOW_AWARD_OTHER			   NUMBER(1) DEFAULT 0 NOT NULL,
	ALLOW_ACTIVITY_UPLOAD		   NUMBER(1),
	REQUIRE_CONTEST_APPROVAL	   NUMBER(1) DEFAULT 0 NOT NULL,	
	CONTEST_APPROVAL_LEVELS		   NUMBER(1) DEFAULT 0 NOT NULL,
	CONTEST_APPROVAL_LVL1_AUD_TYPE   VARCHAR2(40),
	CONTEST_APPROVAL_LVL2_AUD_TYPE   VARCHAR2(40),
	MAX_CONTEST_TO_DISPLAY         NUMBER(2),
	DAYS_TO_ARCHIVE				   NUMBER(2),
	DAYS_TO_APPROVE_ON_SUBMISSION  NUMBER(4),
	CONTEST_GUIDE_URL 			   VARCHAR2(400) NOT NULL
)
/
ALTER TABLE promo_ssi
ADD CONSTRAINT promo_ssi_pk PRIMARY KEY (promotion_id)
USING INDEX
/
ALTER TABLE promo_ssi ADD CONSTRAINT promo_ssi_promotion_fk
  FOREIGN KEY (promotion_id) REFERENCES promotion (promotion_id)
/