CREATE SEQUENCE SSI_CONTEST_PAX_PAYOUT_PK_SQ
  START WITH 1
  MAXVALUE 9999999999999999999999999999
/
CREATE TABLE SSI_CONTEST_PAX_PAYOUT
(
  SSI_CONTEST_PAX_PAYOUT_ID  NUMBER(18)         NOT NULL,
  SSI_CONTEST_ID             NUMBER(18)         NOT NULL,
  SSI_CONTEST_ACTIVITY_ID    NUMBER(18),
  USER_ID                    NUMBER(18)         NOT NULL,
  PAYOUT_AMOUNT              NUMBER(18,4),
  JOURNAL_ID                 NUMBER(18),
  AWARD_ISSUANCE_NUMBER      NUMBER(18),
  CREATED_BY                 NUMBER(18)         NOT NULL,
  DATE_CREATED               DATE               NOT NULL,
  MODIFIED_BY                NUMBER(18),
  DATE_MODIFIED              DATE,
  VERSION                    NUMBER(18)         NOT NULL
)
/
CREATE UNIQUE INDEX SSI_CONTEST_PAX_PAYOUT_PK ON SSI_CONTEST_PAX_PAYOUT
(SSI_CONTEST_PAX_PAYOUT_ID)
/
ALTER TABLE SSI_CONTEST_PAX_PAYOUT ADD (
  CONSTRAINT SSI_CONTEST_PAX_PAYOUT_PK
  PRIMARY KEY
  (SSI_CONTEST_PAX_PAYOUT_ID)
  USING INDEX SSI_CONTEST_PAX_PAYOUT_PK
  ENABLE VALIDATE)
/