UPDATE ROLE SET ROLE_ID = 1001 where 
CODE like 'DIY_BANNER_ADMIN'
/
UPDATE ROLE SET ROLE_ID = 1002 where 
CODE like 'DIY_NEWS_ADMIN'
/
UPDATE ROLE SET ROLE_ID = 1003 where 
CODE like 'DIY_RESOURCE_ADMIN'
/
UPDATE ROLE SET ROLE_ID =1004 where 
CODE like 'DIY_TIPS_ADMIN'
/
