ALTER TABLE ENG_RULES_USER
add
(
  RECEIVED_TARGET_MONTH          NUMBER(12),
  SENT_TARGET_MONTH              NUMBER(12),
  CONNECTED_TARGET_MONTH         NUMBER(12),
  CONNECTED_FROM_TARGET_MONTH    NUMBER(12),
  LOGIN_ACTIVITY_TARGET_MONTH    NUMBER(12),
  RECEIVED_TARGET_QUARTER        NUMBER(12),
  SENT_TARGET_QUARTER            NUMBER(12),
  CONNECTED_TARGET_QUARTER       NUMBER(12),
  CONNECTED_FROM_TARGET_QUARTER  NUMBER(12),
  LOGIN_ACTIVITY_TARGET_QUARTER  NUMBER(12),
  RECEIVED_TARGET_YEAR           NUMBER(12),
  SENT_TARGET_YEAR               NUMBER(12),
  CONNECTED_TARGET_YEAR          NUMBER(12),
  CONNECTED_FROM_TARGET_YEAR     NUMBER(12),
  LOGIN_ACTIVITY_TARGET_YEAR     NUMBER(12),
  RECEIVED_WEIGHT                NUMBER(12),
  SENT_WEIGHT                    NUMBER(12),
  CONNECTED_WEIGHT               NUMBER(12),
  CONNECTED_FROM_WEIGHT          NUMBER(12),
  LOGIN_ACTIVITY_WEIGHT          NUMBER(12)
)
/