INSERT INTO MODULE_APP
   (MODULE_APP_ID,NAME,DESCRIPTION,IS_MOBILE_ENABLED,AVAILABLE_SIZES,AUDIENCE_TYPE, APP_AUDIENCE_TYPE, TILE_MAPPING_TYPE,  UI_APP_NAME,ADMIN_AUDIENCE_SETUP, CREATED_BY, DATE_CREATED,VERSION)
VALUES
   (3049, 'SSI Participant View Contest', 'Desc - SSI Participant View',0, '4X4,4X2,2X2,2X1','allactivepaxaudience','SSIParticipantModule','SSIParticipantModule', 'ssi',1,5662, sysdate, 1)
/
INSERT INTO MODULE_APP
   (MODULE_APP_ID,NAME,DESCRIPTION,IS_MOBILE_ENABLED,AVAILABLE_SIZES,AUDIENCE_TYPE, APP_AUDIENCE_TYPE, TILE_MAPPING_TYPE,  UI_APP_NAME,ADMIN_AUDIENCE_SETUP, CREATED_BY, DATE_CREATED,VERSION)
VALUES
   (3050, 'SSI Manager View Contest', 'Desc - SSI Manager View',0, '4X4,4X2,2X2,2X1','allactivepaxaudience','SSIManagerModule','SSIManagerModule', 'ssi',1,5662, sysdate, 1)
/
INSERT INTO MODULE_APP
   (MODULE_APP_ID,NAME,DESCRIPTION,IS_MOBILE_ENABLED,AVAILABLE_SIZES,AUDIENCE_TYPE, APP_AUDIENCE_TYPE, TILE_MAPPING_TYPE,  UI_APP_NAME,ADMIN_AUDIENCE_SETUP, CREATED_BY, DATE_CREATED,VERSION)
VALUES
   (3051, 'SSI Creator View Contest', 'Desc - SSI Creator View',0, '4X4,4X2,2X2,2X1','allactivepaxaudience','SSICreatorModule','SSICreatorModule', 'ssi',1,5662, sysdate, 1)
/
INSERT INTO MODULE_APP
   (MODULE_APP_ID,NAME,DESCRIPTION,IS_MOBILE_ENABLED,AVAILABLE_SIZES,AUDIENCE_TYPE, APP_AUDIENCE_TYPE, TILE_MAPPING_TYPE,  UI_APP_NAME,ADMIN_AUDIENCE_SETUP, CREATED_BY, DATE_CREATED,VERSION)
VALUES
   (3052, 'SSI Create a Contest', 'Desc - SSI Create a Contest',0, '4X4,4X2,2X2,2X1','allactivepaxaudience','SSICreatorContestsModule','SSICreatorContestsModule', 'ssi',1,5662, sysdate, 1)
/
UPDATE MODULE_APP SET APP_AUDIENCE_TYPE = 'highlightedReportModule' WHERE MODULE_APP_ID = 3020
/
UPDATE MODULE_APP SET AVAILABLE_SIZES = '4X4,4X2,2X2,2X1,1X1' where MODULE_APP_ID = 3012
/
DELETE FROM MODULE_APP WHERE MODULE_APP_ID = 3042
/