ALTER TABLE SCHEDULED_RECOGNITION 
ADD(IS_SCHEDULED               		VARCHAR2(5),
    SENDER_NODE_ID             		VARCHAR2(18),
    PROXY_USER_ID              		VARCHAR2(18),
    RECIPIENT_NODE_ID          		VARCHAR2(18),
    SENDER_COMMENTS            		VARCHAR2(4000),
    BUDGET_ID                  		VARCHAR2(18),
    TEAM_ID                    		VARCHAR2(18),
    BEHAVIOR                   		VARCHAR2(40),
    CERTIFICATE_ID             		VARCHAR2(18),
    CARD_ID                    		VARCHAR2(18),
    COPY_SENDER            			VARCHAR2(5),
    COPY_MANAGER       				VARCHAR2(5),
    COPY_OTHERS           			VARCHAR2(5),
    SEND_COPY_TO_OTHERS        		VARCHAR2(1000),
    AWARD_QTY             			VARCHAR2(18),
    CALCULATOR_SCORE           		VARCHAR2(10),
    LEVEL_ID                   		VARCHAR2(18),
    PRODUCT_ID                 		VARCHAR2(18),
    RECIPIENT_COUNTRY_CODE     		VARCHAR2(10),
    CLAIM_ELEMENTS             		VARCHAR2(4000),
    CALCULATOR_RESPONSE        		VARCHAR2(4000),
    ANNIVERSARY_NUM_DAYS 			VARCHAR2(5),
    ANNIVERSARY_NUM_YEARS 			VARCHAR2(5),
    CELEBRATION_MGR_MESSAGE_ID 		VARCHAR2(18))
/
COMMENT ON COLUMN SCHEDULED_RECOGNITION.IS_SCHEDULED IS 'true = DelaySendRecognitionProcess has been scheduled'
/
COMMENT ON COLUMN SCHEDULED_RECOGNITION.SENDER_NODE_ID IS 'node_id of the sender'
/
COMMENT ON COLUMN SCHEDULED_RECOGNITION.PROXY_USER_ID IS 'user_id of the proxy'
/
COMMENT ON COLUMN SCHEDULED_RECOGNITION.RECIPIENT_NODE_ID IS 'user_id of the recipient'
/
COMMENT ON COLUMN SCHEDULED_RECOGNITION.SENDER_COMMENTS IS 'sender comments'
/
COMMENT ON COLUMN SCHEDULED_RECOGNITION.BUDGET_ID IS 'budget_id'
/
COMMENT ON COLUMN SCHEDULED_RECOGNITION.TEAM_ID IS 'team_id'
/
COMMENT ON COLUMN SCHEDULED_RECOGNITION.BEHAVIOR IS 'behavior'
/
COMMENT ON COLUMN SCHEDULED_RECOGNITION.CERTIFICATE_ID IS 'certificate_id'
/
COMMENT ON COLUMN SCHEDULED_RECOGNITION.CARD_ID IS 'card_id'
/
COMMENT ON COLUMN SCHEDULED_RECOGNITION.COPY_SENDER IS 'true or false'
/
COMMENT ON COLUMN SCHEDULED_RECOGNITION.COPY_MANAGER IS 'true or false'
/
COMMENT ON COLUMN SCHEDULED_RECOGNITION.COPY_OTHERS IS 'true or false'
/
COMMENT ON COLUMN SCHEDULED_RECOGNITION.SEND_COPY_TO_OTHERS IS 'list of email addresses'
/
COMMENT ON COLUMN SCHEDULED_RECOGNITION.AWARD_QTY IS 'award_qty'
/
COMMENT ON COLUMN SCHEDULED_RECOGNITION.CALCULATOR_SCORE IS 'calculator_score'
/
COMMENT ON COLUMN SCHEDULED_RECOGNITION.LEVEL_ID IS 'level_id'
/
COMMENT ON COLUMN SCHEDULED_RECOGNITION.PRODUCT_ID IS 'product_id'
/
COMMENT ON COLUMN SCHEDULED_RECOGNITION.RECIPIENT_COUNTRY_CODE IS 'recipient country code'
/
COMMENT ON COLUMN SCHEDULED_RECOGNITION.CLAIM_ELEMENTS IS 'list of claim elements'
/
COMMENT ON COLUMN SCHEDULED_RECOGNITION.CALCULATOR_RESPONSE IS 'calculator response'
/
COMMENT ON COLUMN SCHEDULED_RECOGNITION.ANNIVERSARY_NUM_DAYS IS 'anniversary number of days'
/
COMMENT ON COLUMN SCHEDULED_RECOGNITION.ANNIVERSARY_NUM_YEARS IS 'anniversary number of years'
/
COMMENT ON COLUMN SCHEDULED_RECOGNITION.CELEBRATION_MGR_MESSAGE_ID IS 'celebration manager message_id'
/