INSERT INTO os_propertyset
(ENTITY_ID,ENTITY_NAME,ENTITY_KEY,KEY_TYPE,BOOLEAN_VAL,DOUBLE_VAL,STRING_VAL,LONG_VAL,INT_VAL,DATE_VAL)
VALUES (entity_id_pk_sq.nextval,'nomination.report.comment.available','Nomination Extract Comment Available',1,0,0,NULL,0,0,NULL)
/

UPDATE REPORT_CHART 
SET CHART_TYPE = 'Line' 
WHERE REPORT_CHART_ID = 3026
/

INSERT INTO REPORT_PARAMETER 
(REPORT_PARAMETER_ID, REPORT_ID, PARAMETER_NAME, PARAMETER_CM_KEY, DATABASE_COLUMN, PARAMETER_TYPE, LIST_DEFINITION, PARAMETER_GROUP, SEQUENCE_NUM, CREATED_BY, DATE_CREATED, MODIFIED_BY, DATE_MODIFIED, VERSION, COLLECTION_NAME, DEFAULT_VALUE, HIDE_SHOW_ALL_OPTION) 
VALUES (3158,4008,'nomCommentAvailable','NOM_COMMENT_AVBL_FIELD','nomCommentAvailableList','selectPicklist','picklist.nominationcomment.available.type','EXPORT_SELECTION',10,5661,to_date('20-AUG-12','DD-MON-RR'),5661,to_date('20-AUG-12','DD-MON-RR'),0,'nomCommentAvailableList','no', 1)
/

UPDATE REPORT_PARAMETER 
SET PARAMETER_CM_KEY = 'NOMINATED_FIELD' 
WHERE REPORT_PARAMETER_ID = 2089
/

INSERT INTO REPORT_PARAMETER 
(REPORT_PARAMETER_ID, REPORT_ID, PARAMETER_NAME, PARAMETER_CM_KEY, DATABASE_COLUMN, PARAMETER_TYPE, LIST_DEFINITION, PARAMETER_GROUP, SEQUENCE_NUM, CREATED_BY, DATE_CREATED, MODIFIED_BY, DATE_MODIFIED, VERSION, COLLECTION_NAME, DEFAULT_VALUE, HIDE_SHOW_ALL_OPTION) 
VALUES (3159,4009,'nomCommentAvailable','NOM_COMMENT_AVBL_FIELD','nomCommentAvailableList','selectPicklist','picklist.nominationcomment.available.type','EXPORT_SELECTION',10,5661,to_date('20-AUG-12','DD-MON-RR'),5661,to_date('20-AUG-12','DD-MON-RR'),0,'nomCommentAvailableList','no', 1)
/

UPDATE REPORT_PARAMETER 
SET PARAMETER_CM_KEY = 'NOMINATED_FIELD' 
WHERE REPORT_PARAMETER_ID = 2099
/

INSERT INTO REPORT_PARAMETER 
(REPORT_PARAMETER_ID, REPORT_ID, PARAMETER_NAME, PARAMETER_CM_KEY, DATABASE_COLUMN, PARAMETER_TYPE, LIST_DEFINITION, PARAMETER_GROUP, SEQUENCE_NUM, CREATED_BY, DATE_CREATED, MODIFIED_BY, DATE_MODIFIED, VERSION, COLLECTION_NAME, DEFAULT_VALUE, HIDE_SHOW_ALL_OPTION) 
VALUES(3160,4010,'nomCommentAvailable','NOM_COMMENT_AVBL_FIELD','nomCommentAvailableList','selectPicklist','picklist.nominationcomment.available.type','EXPORT_SELECTION',10,5661,to_date('20-AUG-12','DD-MON-RR'),5661,to_date('20-AUG-12','DD-MON-RR'),0,'nomCommentAvailableList','no', 1)
/

INSERT INTO REPORT_PARAMETER (REPORT_PARAMETER_ID, REPORT_ID, PARAMETER_NAME, PARAMETER_CM_KEY, DATABASE_COLUMN, PARAMETER_TYPE, LIST_DEFINITION, PARAMETER_GROUP, SEQUENCE_NUM, CREATED_BY, DATE_CREATED, MODIFIED_BY, DATE_MODIFIED, VERSION, COLLECTION_NAME, DEFAULT_VALUE, HIDE_SHOW_ALL_OPTION) 
VALUES (3161,4011,'nomCommentAvailable','NOM_COMMENT_AVBL_FIELD','nomCommentAvailableList','selectPicklist','picklist.nominationcomment.available.type','EXPORT_SELECTION',10,5661,to_date('20-AUG-12','DD-MON-RR'),5661,to_date('20-AUG-12','DD-MON-RR'),0,'nomCommentAvailableList','no', 1)
/

INSERT INTO REPORT_PARAMETER 
(REPORT_PARAMETER_ID, REPORT_ID, PARAMETER_NAME, PARAMETER_CM_KEY, DATABASE_COLUMN, PARAMETER_TYPE, LIST_DEFINITION, PARAMETER_GROUP, SEQUENCE_NUM, CREATED_BY, DATE_CREATED, MODIFIED_BY, DATE_MODIFIED, VERSION, COLLECTION_NAME, DEFAULT_VALUE, HIDE_SHOW_ALL_OPTION) 
VALUES (3162,4012,'nomCommentAvailable','NOM_COMMENT_AVBL_FIELD','nomCommentAvailableList','selectPicklist','picklist.nominationcomment.available.type','EXPORT_SELECTION',10,5661,to_date('20-AUG-12','DD-MON-RR'),5661,to_date('20-AUG-12','DD-MON-RR'),0,'nomCommentAvailableList','no', 1)
/

UPDATE REPORT_PARAMETER 
SET LIST_DEFINITION = 'com.biperf.core.domain.node.reportParameterValueChoices.allLiveQuizAndDIYQuizPromotions' 
WHERE REPORT_PARAMETER_ID = 2177
/

UPDATE REPORT_PARAMETER 
SET LIST_DEFINITION = 'com.biperf.core.domain.node.reportParameterValueChoices.allLiveQuizAndDIYQuizPromotions' 
WHERE REPORT_PARAMETER_ID = 2185
/

UPDATE REPORT_PARAMETER 
SET LIST_DEFINITION = 'picklist.badgereceived.type' 
WHERE REPORT_PARAMETER_ID = 2224
/

CREATE TABLE RPT_USER_CHARACTERISTIC
(
  LOCALE             VARCHAR2(10 CHAR),
  CMS_NAME           VARCHAR2(1000 CHAR),
  CMS_CODE           VARCHAR2(1000 CHAR),
  CHARACTERISTIC_ID  NUMBER(18),
  DATE_CREATED       DATE,
  CREATED_BY         NUMBER(18)
)
/

ALTER TABLE rpt_recog_behavior_summary ADD 
 (KEY_FIELD_HASH                 RAW(16),
  MODIFIED_BY                    NUMBER(18),
  DATE_MODIFIED                  DATE,
  SUM_TYPE                       VARCHAR2(49 CHAR)
)
/

ALTER TABLE recognition_claim ADD 
 (SKIP_STANDARD_RECOG_EMAIL  	NUMBER(1) DEFAULT 0 NOT NULL
  )
/

CREATE INDEX NOMINATION_CLAIM_CARD_FK_IDX ON NOMINATION_CLAIM (CARD_ID)
/
ALTER TABLE NOMINATION_CLAIM ADD (
CONSTRAINT NOMINATION_CLAIM_CARD_FK 
FOREIGN KEY (CARD_ID) 
REFERENCES CARD (CARD_ID)
ENABLE VALIDATE)
/
CREATE INDEX nom_claim_idx ON nomination_claim(team_id,hide_public_recognition,claim_id)
/
CREATE INDEX RECOGNITION_CLAIM_CARD_FK_IDX ON RECOGNITION_CLAIM
(CARD_ID)
/
ALTER TABLE RECOGNITION_CLAIM ADD (
  CONSTRAINT RECOGNITION_CLAIM_CARD_FK 
  FOREIGN KEY (CARD_ID) 
  REFERENCES CARD (CARD_ID)
  ENABLE VALIDATE)
/
CREATE INDEX rec_claim_idx ON recognition_claim (team_id,hide_public_recognition,claim_id)
/
ALTER TABLE welcome_message ADD 
 (secondary_message_id   NUMBER(18,0)
  )
/
ALTER TABLE STAGE_PRD_CLAIM_IMP_PRD_RECORD
MODIFY PRODUCT_NAME VARCHAR2(70)
/
ALTER TABLE STAGE_PRD_CLAIM_IMPORT_RECORD
MODIFY PRODUCT_NAME VARCHAR2(70)
/

DECLARE

CURSOR user_cur IS
SELECT *
FROM application_user au
WHERE is_active = 1
AND EXISTS (SELECT 'x'
            FROM participant_employer pe
            WHERE pe.user_id = au.user_id);

CURSOR dtl_cur (cv_user_id NUMBER) IS
SELECT A.*, rowid
FROM participant_employer A
WHERE user_id = cv_user_id
ORDER BY participant_employer_index desc;

BEGIN

  UPDATE participant_employer
  SET termination_date = NVL(date_modified,date_created)
  WHERE termination_date IS NULL;
  COMMIT;

  FOR user_rec IN user_cur LOOP
    
    FOR dtl_rec IN dtl_cur (user_rec.user_id) LOOP
          
      UPDATE participant_employer
      SET termination_date = NULL
      WHERE rowid = dtl_rec.rowid;
      
      EXIT; -- just processing the first rec
    
    END LOOP; -- FOR dtl_rec IN dtl_cur    
  END LOOP; -- FOR user_rec IN user_cur
  COMMIT;
END;
/
