--liquibase formatted sql

--changeset ramesh:1
--comment Plateau Redemption sequence for tracking  merchOrder
CREATE SEQUENCE PLATEAU_REDEMPTION_TRACKING_SQ START WITH 250 INCREMENT BY 1;
--rollback DROP SEQUENCE PLATEAU_REDEMPTION_TRACKING_SQ;

--changeset ramesh:2
--comment PLATEAU_REDEMPTION_TRACKING table for merchOrder audit purpose
CREATE TABLE PLATEAU_REDEMPTION_TRACKING(  
	TRACKING_ID	        NUMBER(18),
	MERCH_ORDER_ID		NUMBER(18),
	USER_ID	            NUMBER(18),
	DATE_CREATED	    DATE,
	CREATED_BY	        NUMBER(18),
	DATE_MODIFIED	    DATE,
	MODIFIED_BY	        NUMBER(18),
	VERSION                    NUMBER(18),
	CONSTRAINT PR_TRACKING_ID_PK PRIMARY KEY (TRACKING_ID)
);
--rollback DROP TABLE PLATEAU_REDEMPTION_TRACKING CASCADE CONSTRAINTS;
