<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions"%>
<%@ include file="/include/taglib.jspf"%>
<%@ page import="com.biperf.core.ui.utils.RequestUtils"%>
<%@page import="com.biperf.core.utils.ClientStatePasswordManager"%>
<%@page import="com.biperf.core.utils.ClientStateSerializer"%>
<%@ page import="java.util.*" %>
<!-- ======== GOALQUEST SURVEY TAKE PAGE ======== -->

<%
	Long promotionId = null;
	Long surveyId = null;
	String clientState = RequestUtils.getRequiredParamString( request, "clientState" );
	 String cryptoPass = RequestUtils.getOptionalParamString( request, "cryptoPass" );
	 String password = ClientStatePasswordManager.getPassword();
	if ( cryptoPass != null && cryptoPass.equals( "1" ) )
	{
	 	password = ClientStatePasswordManager.getGlobalPassword();
	}
	
	// Deserialize the client state.
	Map clientStateMap = ClientStateSerializer.deserialize( clientState, password );
	promotionId = (Long)clientStateMap.get( "promotionId" );
	if(clientStateMap.get( "id" )!=null){
	  surveyId = (Long)clientStateMap.get( "id" );
	}
	String promotionCode = (String)clientStateMap.get( "promotionCode" );
	pageContext.setAttribute("id",surveyId);
	pageContext.setAttribute("promotionId",promotionId);
	pageContext.setAttribute("promotionCode",promotionCode);
%>
			
<div id="goalQuestPageSurvey" class="goalquest page-content">
    <div class="row-fluid">
        <div class="span12">
            <h2>
                <%-- This page services both GQ and CP promotions, but we need to pick the right logo --%>
                <c:choose>
					<c:when test="${ promotionCode eq 'challengepoint' }">
                        <img src="${pageContext.request.contextPath}/assets/img/goalquest/challengepoint.svg" alt="Challengepoint" class="gqtitlelogo">
                    </c:when>
                    <c:otherwise>
                        <img src="${pageContext.request.contextPath}/assets/img/goalquest/goalquest.svg" alt="GoalQuest" class="gqtitlelogo">
                    </c:otherwise>
                </c:choose>
            </h2>
        </div>
    </div>

    <div class="row-fluid">
        <div class="span12" id="surveyTakeView">

            <!-- content generated by surveyPageTakeTpl -->

        </div><!-- /.span12 -->
    </div><!-- /.row-fluid -->
</div>

<!-- Instantiate the PageView - this goes here as it expresses the DOM element the PageView is getting attached to -->
<script>
    $(document).ready(function() {

        // if desired, the surveyJson object from core/base/ajax/goalquestPageTakeSurvey.json can be embedded here
        var surveyJson;

        //attach the view to an existing DOM element
        G5.views.SurveyPageTake = new SurveyPageTakeView({
            el:$('#goalQuestPageSurvey'),
            pageNav : {
                back : {
                    text : '<cms:contentText key="BACK" code="system.button"/>',
                    url : '<%= RequestUtils.getBaseURI(request)%>/homePage.do'
                },
                home : {
                    text : '<cms:contentText key="HOME" code="system.button"/>',
                    url : '<%= RequestUtils.getBaseURI(request)%>/homePage.do'
                }
            },
            pageTitle : '${promoTypeName}  <cms:contentText key="HEADING" code="survey.question_response" />',
            surveyJson : surveyJson,
            // options to pass to the SurveyModel
            modelOpts: {
                url: {
                    load: G5.props.URL_ROOT+'goalquest/surveyPageTakeGQSurvey.do?method=displayInfo&promotionId=${promotionId}&surveyId=${surveyId}',
                    submit: G5.props.URL_ROOT+'goalquest/surveyPageSaveGQSurvey.do?method=submit&promotionId=${promotionId}&surveyId=${surveyId}',
                    save: G5.props.URL_ROOT+'goalquest/surveyPageSaveGQSurvey.do?method=saveForLater&promotionId=${promotionId}&surveyId=${surveyId}'
                }
            },
            // I have been doing some experimenting with passing CM keys as JSON instead of embedding within the JSPs, but haven't perfected the technique yet
            // That said, I want to try this out on this particular page
            cm : {
                btn : {
                    done : "<cms:contentText key="DONE" code="survey.take" />",
                    submit : "<cms:contentText key="SUBMIT_SURVEY" code="survey.take" />",
                    save : "<cms:contentText key="SAVE_FOR_LATER" code="survey.take" />"
                }
            }
        });

    });
</script>

<script type="text/template" id="surveyTakeTplTpl">
    <%@include file="/survey/surveyTakeTpl.jsp" %>
</script>

<c:if test="${ goalSelectionModal == true}">
    <tiles:insert definition="select.goal.confirmation.modal" flush="true" ignore="true" />
</c:if>
