DELETE FROM FILTER_MODULE_APP
/
INSERT INTO MODULE_APP
   (MODULE_APP_ID,MODULE_TYPE,NAME,DESCRIPTION,IS_MOBILE_ENABLED,AVAILABLE_SIZES,AUDIENCE_TYPE, APP_AUDIENCE_TYPE, TILE_MAPPING_TYPE,  UI_APP_NAME,ADMIN_AUDIENCE_SETUP, CREATED_BY, DATE_CREATED,VERSION)
VALUES
   (MODULE_APP_PK.nextval, 'standard', 'Billboard', 'Desc - Billboard',0, '4X4,4X2,2X2','allactivepaxaudience','heroModule','heroModule', 'hero',1,5662, sysdate, 1)
/
INSERT INTO MODULE_APP
   (MODULE_APP_ID,MODULE_TYPE,NAME,DESCRIPTION,IS_MOBILE_ENABLED,AVAILABLE_SIZES,AUDIENCE_TYPE, APP_AUDIENCE_TYPE, TILE_MAPPING_TYPE,  UI_APP_NAME,ADMIN_AUDIENCE_SETUP, CREATED_BY, DATE_CREATED,VERSION)
VALUES
   (MODULE_APP_PK.nextval, 'standard', 'Custom Display', 'Custom Display',0, '4X4,4X2,2X2','allactivepaxaudience','xpromoModule','xpromoModule', 'xpromo',1,5662, sysdate, 1)
/
INSERT INTO MODULE_APP
	(MODULE_APP_ID,MODULE_TYPE,NAME,DESCRIPTION,IS_MOBILE_ENABLED,AVAILABLE_SIZES,AUDIENCE_TYPE, APP_AUDIENCE_TYPE, TILE_MAPPING_TYPE,  UI_APP_NAME,ADMIN_AUDIENCE_SETUP, CREATED_BY, DATE_CREATED,VERSION)
VALUES
	(MODULE_APP_PK.nextval, 'standard', 'Upcoming Celebrations', 'Desc - Upcoming Celebrations',0, '4X4,4X2,2X2','allactivepaxaudience','purlCelebrateModule','purlCelebrateModule', 'purlContribute',1,5662, sysdate, 1)
/
UPDATE MODULE_APP SET IS_ACTIVE=0 WHERE NAME='Quiz'
/
UPDATE MODULE_APP SET IS_ACTIVE=0 WHERE NAME='Highlighted Report'
/
UPDATE MODULE_APP SET IS_ACTIVE=0 WHERE NAME='DIY Travel'
/
UPDATE MODULE_APP SET IS_ACTIVE=0 WHERE NAME='Merchandise'
/
UPDATE MODULE_APP SET IS_ACTIVE=0 WHERE NAME='International Catalog'
/
UPDATE MODULE_APP SET IS_ACTIVE=0 WHERE NAME='Throwdown Smack Talk'
/
UPDATE MODULE_APP SET IS_ACTIVE=0 WHERE NAME='Throwdown Training Camp'
/
UPDATE MODULE_APP SET IS_ACTIVE=0 WHERE NAME='Throwdown News'
/
UPDATE MODULE_APP SET IS_ACTIVE=0 WHERE NAME='Throwdown Standings'
/
UPDATE MODULE_APP SET IS_ACTIVE=0 WHERE NAME='Throwdown Match List'
/
UPDATE MODULE_APP SET IS_ACTIVE=0 WHERE NAME='Throwdown PromoName Selector'
/
UPDATE MODULE_APP SET IS_ACTIVE=0 WHERE NAME='Throwdown Match Summary'
/
UPDATE MODULE_APP SET IS_ACTIVE=0 WHERE NAME='Throwdown Rankings'
/
UPDATE MODULE_APP SET IS_ACTIVE=0 WHERE NAME='Instant Poll'
/
UPDATE MODULE_APP SET IS_ACTIVE=0 WHERE NAME='Celebration'
/
UPDATE MODULE_APP SET IS_ACTIVE=0 WHERE NAME='Plateau Awards Redeem'
/
UPDATE MODULE_APP SET IS_ACTIVE=0 WHERE NAME='Nominations Approval Module'
/
UPDATE MODULE_APP SET IS_ACTIVE=0 WHERE NAME='Badges'
/
UPDATE MODULE_APP SET IS_ACTIVE=0 WHERE NAME='Engagement'
/
UPDATE MODULE_APP SET IS_ACTIVE=0 WHERE NAME='Budget Meter'
/
UPDATE MODULE_APP SET IS_ACTIVE=0 WHERE NAME='PURL (Managers only)'
/
UPDATE MODULE_APP SET IS_ACTIVE=0 WHERE NAME in ('Communications', 'Events', 'Forum', 'Great Deal', 'Travel Great Deal', 'In Progress Nomination', 'Nomination', 'Purl Celebrate', 'Real Deal', 'Recognition')
/
UPDATE MODULE_APP SET NAME='RPM Manager' WHERE NAME = 'Engagement Manager'
/
UPDATE MODULE_APP SET MODULE_TYPE='xpromo', SORT_ORDER=1 WHERE NAME='Banner Ads'
/
UPDATE MODULE_APP SET MODULE_TYPE='xpromo', SORT_ORDER=2 WHERE NAME='News'
/