CREATE SEQUENCE USER_CONNECTIONS_SQ INCREMENT BY 1 START WITH 700
/

CREATE TABLE USER_CONNECTIONS (
	 ID             NUMBER (18) NOT NULL, 
	 SENDER_ID      NUMBER (18) NOT NULL, 
	 RECEIVER_ID    NUMBER (18) NOT NULL,
     CREATED_BY     NUMBER(18) NOT NULL,
     DATE_CREATED   DATE NOT NULL,
     MODIFIED_BY    NUMBER(18),
     DATE_MODIFIED  DATE,
     VERSION        NUMBER (18)
 )
/

ALTER TABLE USER_CONNECTIONS
ADD CONSTRAINT user_connections_pk PRIMARY KEY (ID)
USING INDEX
/