CREATE TABLE STAGE_SSI_OBJECTIVE_IMPORT
(
  IMPORT_RECORD_ID          NUMBER(18),
  IMPORT_FILE_ID            NUMBER(18),
  USER_ID                   NUMBER(18),
  USER_NAME                 VARCHAR2(40 CHAR),
  FIRST_NAME                VARCHAR2(40 CHAR),
  LAST_NAME                 VARCHAR2(40 CHAR),
  ROLE                      VARCHAR2(40 CHAR),
  OBJECTIVE_DESCRIPTION     VARCHAR2(100 CHAR),
  OBJECTIVE_AMOUNT          NUMBER(18,4),
  OBJECTIVE_PAYOUT          NUMBER(18,4),
  OTHER_PAYOUT_DESCRIPTION  VARCHAR2(100 CHAR),
  OTHER_VALUE               NUMBER(18,4),
  BONUS_FOR_EVERY           NUMBER(18,4),
  BONUS_PAYOUT              NUMBER(18,4),
  BONUS_PAYOUT_CAP          NUMBER(18,4),
  DATE_CREATED              DATE,
  CREATED_BY                NUMBER(18)
)
/
CREATE UNIQUE INDEX STAGE_SSI_OBJECTIVE_IMPORT_PK ON STAGE_SSI_OBJECTIVE_IMPORT
(IMPORT_RECORD_ID)
/
CREATE INDEX STAGE_SSI_OBJ_IMPORT_FK_IDX ON STAGE_SSI_OBJECTIVE_IMPORT
(IMPORT_FILE_ID)
/
ALTER TABLE STAGE_SSI_OBJECTIVE_IMPORT ADD (
  CONSTRAINT STAGE_SSI_OBJECTIVE_IMPORT_PK
  PRIMARY KEY
  (IMPORT_RECORD_ID)
  USING INDEX STAGE_SSI_OBJECTIVE_IMPORT_PK
  ENABLE VALIDATE)
/
CREATE TABLE STAGE_SSI_DTGT_IMPORT
(
  IMPORT_RECORD_ID  NUMBER(18),
  IMPORT_FILE_ID    NUMBER(18),
  USER_ID           NUMBER(18),
  USER_NAME         VARCHAR2(40 CHAR),
  FIRST_NAME        VARCHAR2(40 CHAR),
  LAST_NAME         VARCHAR2(40 CHAR),
  ROLE              VARCHAR2(40 CHAR),
  DATE_CREATED      DATE,
  CREATED_BY        NUMBER(18)
)
/
CREATE UNIQUE INDEX STAGE_SSI_DTGT_IMPORT_PK ON STAGE_SSI_DTGT_IMPORT
(IMPORT_RECORD_ID)
/
CREATE INDEX STAGE_SSI_DTGT_IMPORT_FK_IDX ON STAGE_SSI_DTGT_IMPORT
(IMPORT_FILE_ID)
/
ALTER TABLE STAGE_SSI_DTGT_IMPORT ADD (
  CONSTRAINT STAGE_SSI_DTGT_IMPORT_PK
  PRIMARY KEY
  (IMPORT_RECORD_ID)
  USING INDEX STAGE_SSI_DTGT_IMPORT_PK
  ENABLE VALIDATE)
/
CREATE TABLE STAGE_SSI_STEP_IT_UP_IMPORT
(
  IMPORT_RECORD_ID  NUMBER(18),
  IMPORT_FILE_ID    NUMBER(18),
  USER_ID           NUMBER(18),
  USER_NAME         VARCHAR2(40 CHAR),
  FIRST_NAME        VARCHAR2(40 CHAR),
  LAST_NAME         VARCHAR2(40 CHAR),
  ROLE              VARCHAR2(40 CHAR),
  BASELINE          NUMBER(18,4),
  DATE_CREATED      DATE,
  CREATED_BY        NUMBER(18)
)
/
CREATE UNIQUE INDEX STAGE_SSI_STEP_IT_UP_IMPORT_PK ON STAGE_SSI_STEP_IT_UP_IMPORT
(IMPORT_RECORD_ID)
/
CREATE INDEX STAGE_SSI_STEP_IT_UP_IM_FK_IDX ON STAGE_SSI_STEP_IT_UP_IMPORT
(IMPORT_FILE_ID)
/
ALTER TABLE STAGE_SSI_STEP_IT_UP_IMPORT ADD (
  CONSTRAINT STAGE_SSI_STEP_IT_UP_IMPORT_PK
  PRIMARY KEY
  (IMPORT_RECORD_ID)
  USING INDEX STAGE_SSI_STEP_IT_UP_IMPORT_PK
  ENABLE VALIDATE)
/
CREATE TABLE STAGE_SSI_STACK_RANK_IMPORT
(
  IMPORT_RECORD_ID  NUMBER(18),
  IMPORT_FILE_ID    NUMBER(18),
  USER_ID           NUMBER(18),
  USER_NAME         VARCHAR2(40 CHAR),
  FIRST_NAME        VARCHAR2(40 CHAR),
  LAST_NAME         VARCHAR2(40 CHAR),
  ROLE              VARCHAR2(40 CHAR),
  DATE_CREATED      DATE,
  CREATED_BY        NUMBER(18)
)
/
CREATE UNIQUE INDEX STAGE_SSI_STACK_RANK_IMPORT_PK ON STAGE_SSI_STACK_RANK_IMPORT
(IMPORT_RECORD_ID)
/
CREATE INDEX STAGE_SSI_STK_RK_IMPORT_FK_IDX ON STAGE_SSI_STACK_RANK_IMPORT
(IMPORT_FILE_ID)
/
ALTER TABLE STAGE_SSI_STACK_RANK_IMPORT ADD (
  CONSTRAINT STAGE_SSI_STACK_RANK_IMPORT_PK
  PRIMARY KEY
  (IMPORT_RECORD_ID)
  USING INDEX STAGE_SSI_STACK_RANK_IMPORT_PK
  ENABLE VALIDATE)
/
CREATE TABLE STAGE_SSI_ATN_IMPORT
(
  IMPORT_RECORD_ID      NUMBER(18),
  IMPORT_FILE_ID        NUMBER(18),
  USER_ID               NUMBER(18),
  USER_NAME             VARCHAR2(40 CHAR),
  FIRST_NAME            VARCHAR2(40 CHAR),
  LAST_NAME             VARCHAR2(40 CHAR),
  ROLE                  VARCHAR2(40 CHAR),
  ACTIVITY_DESCRIPTION  VARCHAR2(100 CHAR),
  ACTIVITY_AMOUNT       NUMBER(18,4),
  PAYOUT_AMOUNT         NUMBER(18,4),
  PAYOUT_DESCRIPTION    VARCHAR2(100 CHAR),
  AWARD_ISSUE_VALUE     NUMBER(18,4),
  DATE_CREATED          DATE,
  CREATED_BY            NUMBER(18)
)
/
CREATE UNIQUE INDEX STAGE_SSI_ATN_IMPORT_PK ON STAGE_SSI_ATN_IMPORT
(IMPORT_RECORD_ID)
/
CREATE INDEX STAGE_SSI_ATN_IMPORT_FK_IDX ON STAGE_SSI_ATN_IMPORT
(IMPORT_FILE_ID)
/
ALTER TABLE STAGE_SSI_ATN_IMPORT ADD (
  CONSTRAINT STAGE_SSI_ATN_IMPORT_PK
  PRIMARY KEY
  (IMPORT_RECORD_ID)
  USING INDEX STAGE_SSI_ATN_IMPORT_PK
  ENABLE VALIDATE)
/