CREATE SEQUENCE MODULE_APP_PK START WITH 1 INCREMENT BY 1
/
ALTER TABLE MODULE_APP ADD ( MODULE_TYPE VARCHAR2(50) DEFAULT 'standard' NOT NULL  )
/
ALTER TABLE MODULE_APP ADD ( 
	is_active	NUMBER(1) DEFAULT 1 )
/
UPDATE MODULE_APP 
 set IS_ACTIVE = (DECODE(APP_AUDIENCE_TYPE,'disabled',0,1))
/
ALTER TABLE MODULE_APP MODIFY ( 
	is_active	NUMBER(1) DEFAULT 1  NOT NULL )
/
ALTER TABLE MODULE_APP ADD
( SORT_ORDER 	   		NUMBER(18))
/