CREATE INDEX RPT_BADGE_DETAIL_IDX1 ON RPT_BADGE_DETAIL
(USER_ID, NODE_ID, EARNED_DATE, PROMOTION_ID)
/
CREATE UNIQUE INDEX RPT_BADGE_DETAIL_ID_PK ON RPT_BADGE_DETAIL
(RPT_BADGE_DETAIL_ID)
/
ALTER TABLE RPT_BADGE_DETAIL ADD (
  CONSTRAINT RPT_BADGE_DETAIL_ID_PK
  PRIMARY KEY
  (RPT_BADGE_DETAIL_ID)
  USING INDEX RPT_BADGE_DETAIL_ID_PK
  ENABLE VALIDATE)
/