CREATE SEQUENCE PSW_HIST_PK_SQ START WITH 250 INCREMENT BY 1
/
CREATE TABLE USER_PASSWORD_HISTORY
(
  USER_PASSWORD_HISTORY_ID  NUMBER(18)          NOT NULL,
  USER_ID                   NUMBER(18)          NOT NULL,
  PASSWORD_SET_DATE         DATE                NOT NULL,
  PASSWORD                  VARCHAR2(100 CHAR)  NOT NULL,
  CREATED_BY                VARCHAR2(30 CHAR)   NOT NULL,
  DATE_CREATED              DATE                NOT NULL,
  SEQUENCE_NUM        		NUMBER(10) NOT NULL
)
/
ALTER TABLE USER_PASSWORD_HISTORY ADD (
  CONSTRAINT USR_PSW_HIST_FK
  FOREIGN KEY (USER_ID)
  REFERENCES APPLICATION_USER (USER_ID)
  ENABLE VALIDATE)
/