CREATE INDEX EEU_NODE_ID_IDX ON ENGAGEMENT_ELIG_USER
(NODE_ID)
/
alter TABLE ENGAGEMENT_ELIG_MANAGER ADD 
NODE_USERS_COUNT  NUMBER(18)
/
alter TABLE ENG_RECOG_SENT_BY_PROMO
MODIFY RANK NUMBER(8)
/
alter TABLE ENG_RECOG_RECVD_BY_PROMO
MODIFY RANK NUMBER(8)
/
alter TABLE ENGAGEMENT_RECOG_SENT
MODIFY RANK NUMBER(8)
/
alter TABLE ENGAGEMENT_RECOG_RECEIVED
MODIFY RANK NUMBER(8)
/