DROP VIEW SM_CP_GOAL_NOT_SELECTED_VW
/
DROP VIEW SM_CP_INTERIM_VW
/
DROP VIEW SM_CP_PAX_ACHIEVED_VW
/
DROP VIEW SM_CP_PAX_NOT_ACHIEVED_VW
/
DROP VIEW SM_CP_PROGRESS_UPDATED_VW
/
DROP VIEW SM_CP_PROMO_LAUNCH_NOTI_VW
/
DROP VIEW SM_CP_WELCOME_LOGIN_PWD_VW
/