DROP VIEW SM_GQ_PAX_GOAL_ACHIEVED_VW
/
DROP VIEW SM_GQ_PAX_GOAL_NOT_ACHIEVED_VW
/
DROP VIEW SM_GQ_PAX_GOAL_NOT_SELECTED_VW
/
DROP VIEW SM_GQ_PAX_PROG_UPD_VW
/
DROP VIEW SM_GQ_PART_GOAL_ACHIEVED_VW
/
DROP VIEW SM_GQP_GOAL_ACH_NO_PAYOUT_VW
/
DROP VIEW SM_GQ_PART_NOT_ACHIEVED_VW
/
DROP VIEW SM_GQ_PART_PROG_UPD_VW
/
DROP VIEW SM_GQ_PROMO_LAUNCH_NOTI_VW
/