DROP MATERIALIZED VIEW mv_cms_asset_value
/
CREATE MATERIALIZED VIEW LOG ON cms_asset
   WITH PRIMARY KEY, ROWID, SEQUENCE (code) INCLUDING NEW VALUES
/
CREATE MATERIALIZED VIEW LOG ON cms_content_key
   WITH PRIMARY KEY, ROWID, SEQUENCE (asset_id) INCLUDING NEW VALUES
/
CREATE MATERIALIZED VIEW LOG ON cms_content
   WITH PRIMARY KEY, ROWID, SEQUENCE (content_key_id, content_status, locale) INCLUDING NEW VALUES
/
CREATE MATERIALIZED VIEW LOG ON cms_content_data_str
   WITH PRIMARY KEY, ROWID, SEQUENCE (value_str) INCLUDING NEW VALUES
/
