CREATE SEQUENCE SSI_CONTEST_BILL_CODE_PK_SQ
  START WITH 100
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
/
CREATE TABLE SSI_CONTEST_BILL_CODE
(
  SSI_CONTEST_BILL_CODE_ID  NUMBER(18)          NOT NULL,
  SSI_CONTEST_ID            NUMBER(18)          NOT NULL,
  TRACK_BILLS_BY            VARCHAR2(15 CHAR),
  BILL_CODE                 VARCHAR2(100 CHAR),
  CUSTOM_VALUE              VARCHAR2(100 CHAR),
  SORT_ORDER                NUMBER(12),
  CREATED_BY                NUMBER(18)          NOT NULL,
  DATE_CREATED              DATE                NOT NULL,
  MODIFIED_BY               NUMBER(18),
  DATE_MODIFIED             DATE,
  VERSION                   NUMBER(18)          NOT NULL
)
/
CREATE UNIQUE INDEX SSI_CONTEST_BILL_CODE_PK ON SSI_CONTEST_BILL_CODE
(SSI_CONTEST_BILL_CODE_ID)
/
CREATE INDEX SSI_BILL_CODE_SSI_FK_IDX ON SSI_CONTEST_BILL_CODE
(SSI_CONTEST_ID)
/
ALTER TABLE SSI_CONTEST_BILL_CODE ADD (
  CONSTRAINT SSI_CONTEST_BILL_CODE_PK
  PRIMARY KEY
  (SSI_CONTEST_BILL_CODE_ID)
  USING INDEX SSI_CONTEST_BILL_CODE_PK
  ENABLE VALIDATE)
/
