DROP TABLE GTT_MANAGER_ID CASCADE CONSTRAINTS
/
CREATE GLOBAL TEMPORARY TABLE GTT_MANAGER_ID
(
  USER_ID          NUMBER(18),
  MANAGER_USER_ID  NUMBER(18)
)
ON COMMIT PRESERVE ROWS
RESULT_CACHE (MODE DEFAULT)
NOCACHE
/
