CREATE TABLE ENCRYPTION_CONVERSION
(TABLE_NAME    VARCHAR2(30 CHAR),
 COLUMN_NAME   VARCHAR2(30 CHAR),
 DATA_TYPE     VARCHAR2(30 CHAR),
 NEEDS_ENCRYPTION  VARCHAR2(1 CHAR)
)
/

ALTER TABLE ENCRYPTION_CONVERSION
ADD CONSTRAINT ENCRYPTION_CONVERSION_udk UNIQUE (TABLE_NAME, COLUMN_NAME)
USING INDEX
/