--liquibase formatted sql

--changeset gorantla:1
--comment ADD index
--preconditions onFail:MARK_RAN onError:MARK_RAN
--precondition-sql-check expectedResult:0 SELECT COUNT(1) FROM USER_INDEXES WHERE TABLE_NAME = 'APPLICATION_USER' AND INDEX_NAME = 'USER_ROSTERPERSONID_IDX';
 CREATE INDEX USER_ROSTERPERSONID_IDX ON APPLICATION_USER(ROSTERPERSONID);
--rollback DROP INDEX USER_ROSTERPERSONID_IDX;
 
--changeset gorantla:2
--comment Add unique constraint on ROSTERPERSONID
--preconditions onFail:MARK_RAN onError:MARK_RAN
--precondition-sql-check expectedResult:0 SELECT COUNT(1) FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'APPLICATION_USER' AND CONSTRAINT_NAME = 'ROSTERPERSONID_UK';
 ALTER TABLE APPLICATION_USER ADD CONSTRAINT ROSTERPERSONID_UK UNIQUE (ROSTERPERSONID);
--rollback ALTER TABLE APPLICATION_USER DROP CONSTRAINT ROSTERPERSONID_UK;  

