CREATE TABLE STG_CHAN_CHANNELS
(
  ID         VARCHAR2(50 CHAR)                  NOT NULL,
  ISDELETED  VARCHAR2(10 CHAR)                  DEFAULT 'false',
  CREATEDAT  DATE                               NOT NULL,
  UPDATEDAT  DATE                               NOT NULL,
  COMPANYID  VARCHAR2(50 CHAR)                  NOT NULL
);


CREATE TABLE STG_CHAN_MESSAGES
(
  ID                    VARCHAR2(50 CHAR)       NOT NULL,
  CHANNELID             VARCHAR2(50 CHAR)       NOT NULL,
  CONTRIBUTORNAME       VARCHAR2(100 CHAR)      NOT NULL,
  CONTRIBUTORREFERENCE  VARCHAR2(64 CHAR)       NOT NULL,
  TEXT                  CLOB,
  EFFECTS               VARCHAR2(100 CHAR),
  REPLYTOID             VARCHAR2(50 CHAR),
  THREADID              VARCHAR2(50 CHAR)       NOT NULL,
  ISDELETED             VARCHAR2(10 CHAR)       DEFAULT 'false',
  CREATEDAT             DATE                    NOT NULL,
  UPDATEDAT             DATE                    NOT NULL,
  COMPANYID             VARCHAR2(50 CHAR)       NOT NULL,
  ISFLAGGED             VARCHAR2(10 CHAR)       DEFAULT 'false',
  ATTACHMENTS           VARCHAR2(1000 CHAR)     DEFAULT '[]',
  ISPRIVATE             VARCHAR2(10 CHAR)       DEFAULT 'false',
  CONTRIBUTORSTATUS     VARCHAR2(15 CHAR)       DEFAULT 'peer'
);


CREATE TABLE STG_CMX_KEY
(
  ID              VARCHAR2(50 CHAR)             NOT NULL,
  NAME            VARCHAR2(255 CHAR)            NOT NULL,
  PROJECTID       VARCHAR2(50 CHAR),
  TAGS            VARCHAR2(50 CHAR),
  CREATEDAT       DATE                          NOT NULL,
  UPDATEDAT       DATE                          NOT NULL,
  DONOTTRANSLATE  VARCHAR2(50 CHAR)             DEFAULT 'false',
  METADATA        VARCHAR2(1000 CHAR)           DEFAULT '[]'
);


CREATE TABLE STG_CMX_STRING
(
  KEYID      VARCHAR2(50 CHAR)                  NOT NULL,
  LOCALE     VARCHAR2(5 CHAR)                   NOT NULL,
  COMPANYID  VARCHAR2(50 CHAR)                  NOT NULL,
  VALUE      VARCHAR2(4000 CHAR),
  CREATEDAT  DATE                               NOT NULL,
  UPDATEDAT  DATE                               NOT NULL
);


CREATE TABLE STG_GC_AWARDS
(
  COMPANYID     VARCHAR2(50 CHAR)               NOT NULL,
  AWARDID       VARCHAR2(50 CHAR)               NOT NULL,
  PROGRAMID     VARCHAR2(50 CHAR)               NOT NULL,
  CREATEDAT     DATE                            NOT NULL,
  UPDATEDAT     DATE                            NOT NULL,
  BROWSECODE    VARCHAR2(25 CHAR),
  BILLPROFILES  VARCHAR2(3000 CHAR)
);


CREATE TABLE STG_GC_COUNTRIES
(
  COMPANYID      VARCHAR2(50 CHAR)              NOT NULL,
  AWARDID        VARCHAR2(50 CHAR)              NOT NULL,
  COUNTRYCODE    VARCHAR2(50 CHAR)              NOT NULL,
  PROGRAMNUMBER  VARCHAR2(50 CHAR)              NOT NULL,
  CREATEDAT      DATE                           NOT NULL,
  UPDATEDAT      DATE                           NOT NULL
);


CREATE TABLE STG_GC_GIFTCODES
(
  COMPANYID        VARCHAR2(50 CHAR)            NOT NULL,
  AWARDID          VARCHAR2(50 CHAR)            NOT NULL,
  GIFTCODEID       VARCHAR2(50 CHAR)            NOT NULL,
  REQUESTID        VARCHAR2(50 CHAR)            NOT NULL,
  COUNTRYCODE      VARCHAR2(25 CHAR)            NOT NULL,
  BATCHID          NUMBER(18)                   NOT NULL,
  PROGRAMNUMBER    VARCHAR2(10 CHAR)            NOT NULL,
  LEVELNAME        VARCHAR2(25 CHAR)            NOT NULL,
  GIFTCODE         VARCHAR2(25 CHAR)            NOT NULL,
  REFERENCENUMBER  VARCHAR2(25 CHAR)            NOT NULL,
  EXPIREDAT        DATE,
  DESCRIPTION      VARCHAR2(50 CHAR),
  FIRSTNAME        VARCHAR2(50 CHAR),
  LASTNAME         VARCHAR2(50 CHAR),
  LOCALE           VARCHAR2(25 CHAR),
  REQUESTEDBY      VARCHAR2(25 CHAR)            NOT NULL,
  STATUS           VARCHAR2(25 CHAR)            NOT NULL,
  BILLPROFILES     VARCHAR2(3000 CHAR),
  CREATEDAT        DATE                         NOT NULL,
  UPDATEDAT        DATE                         NOT NULL,
  ORGUNITNAME      VARCHAR2(25 CHAR),
  STATUSUPDATEDAT  DATE,
  RETURNEDAT       DATE
);


CREATE TABLE STG_GC_LEVELS
(
  ID           VARCHAR2(50 CHAR)                NOT NULL,
  COMPANYID    VARCHAR2(50 CHAR)                NOT NULL,
  AWARDID      VARCHAR2(50 CHAR)                NOT NULL,
  LEVELCODE    VARCHAR2(25 CHAR),
  LEVELNAME    VARCHAR2(1000 CHAR),
  DEFAULTITEM  VARCHAR2(1000 CHAR),
  CREATEDAT    DATE                             NOT NULL,
  UPDATEDAT    DATE                             NOT NULL
);


CREATE TABLE STG_SA_CELEBRATIONSPERSONS
(
  CELEBRATIONID     VARCHAR2(50 CHAR)           NOT NULL,
  CONTRIBUTIONID    VARCHAR2(50 CHAR)           NOT NULL,
  PERSONID          VARCHAR2(50 CHAR)           NOT NULL,
  ROLE              VARCHAR2(50 CHAR)           DEFAULT 'peer',
  CREATEDAT         DATE                        NOT NULL,
  UPDATEDAT         DATE                        NOT NULL,
  MOBILECODE        VARCHAR2(14 CHAR)           NOT NULL,
  INVITATIONSENTAT  DATE,
  INVITERPERSONID   VARCHAR2(255 CHAR)
);


CREATE TABLE STG_SA_MILESTONES
(
  ID                    NUMBER(18)              NOT NULL,
  COMPANYID             VARCHAR2(50 CHAR)       NOT NULL,
  PROGRAMID             VARCHAR2(50 CHAR)       NOT NULL,
  MILESTONEID           VARCHAR2(50 CHAR)       NOT NULL,
  MILESTONECODE         VARCHAR2(25 CHAR)       NOT NULL,
  MILESTONENAME         VARCHAR2(1000 CHAR)     NOT NULL,
  MILESTONEAWARD        VARCHAR2(1000 CHAR)     NOT NULL,
  MILESTONESTATE        VARCHAR2(25 CHAR)       NOT NULL,
  ECARD                 VARCHAR2(1000 CHAR),
  CELEBRATIONTYPE       VARCHAR2(25 CHAR)       NOT NULL,
  CONTRIBUTIONTYPE      VARCHAR2(25 CHAR)       NOT NULL,
  CREATEDAT             DATE                    NOT NULL,
  UPDATEDAT             DATE                    NOT NULL,
  MAXAWARD              NUMBER(18)              DEFAULT 0,
  MESSAGELEVELLABEL     VARCHAR2(1000 CHAR),
  WEBMESSAGEIMAGEURL    VARCHAR2(500 CHAR),
  EMAILMESSAGEIMAGEURL  VARCHAR2(500 CHAR),
  COUNTRYCODE           VARCHAR2(3 CHAR)
);


CREATE TABLE STG_SA_PERSONS
(
  ID               VARCHAR2(50 CHAR)            NOT NULL,
  USERNAME         VARCHAR2(50 CHAR),
  FIRSTNAME        VARCHAR2(50 CHAR),
  LASTNAME         VARCHAR2(50 CHAR),
  EMAILADDRESS     VARCHAR2(100 CHAR),
  LOCALECODE       VARCHAR2(5 CHAR),
  COUNTRYISO3CODE  VARCHAR2(50 CHAR),
  COMPANYID        VARCHAR2(50 CHAR)            NOT NULL,
  DEPARTMENTNAME   VARCHAR2(100 CHAR),
  ORGUNITNAME      VARCHAR2(100 CHAR),
  CHARACTERISTICS  VARCHAR2(3000 CHAR)          DEFAULT '{}',
  CREATEDAT        DATE                         NOT NULL,
  UPDATEDAT        DATE                         NOT NULL,
  ROSTERPERSONID   VARCHAR2(255 CHAR),
  AVATARURL        VARCHAR2(255 CHAR),
  ACCEPTEDTCAT     DATE,
  CANAUTHENTICATE  VARCHAR2(10 CHAR)
);


CREATE TABLE STG_SA_PROGRAMS
(
  ID                       NUMBER(18),
  COMPANYID                VARCHAR2(50 CHAR)    NOT NULL,
  PROGRAM_UUID             VARCHAR2(50 CHAR)    NOT NULL,
  PROGRAMNAME              VARCHAR2(1000 CHAR)  NOT NULL,
  PROGRAMSTARTDATE         DATE                 NOT NULL,
  PROGRAMENDDATE           DATE,
  PROGRAMSTATE             VARCHAR2(25 CHAR)    NOT NULL,
  AWARDTYPE                VARCHAR2(25 CHAR)    NOT NULL,
  ISBILLPROFILEACTIVE      VARCHAR2(10 CHAR)    NOT NULL,
  BILLPROFILES             VARCHAR2(3000 CHAR),
  GIFTCODEAWARDID          VARCHAR2(50 CHAR),
  AWARDINTERVALTYPE        VARCHAR2(25 CHAR)    NOT NULL,
  AWARDINTERVALFIELD       VARCHAR2(50 CHAR),
  AWARDINTERVALNUMBER      NUMBER(18),
  AWARDINTERVALPART        VARCHAR2(25 CHAR),
  RECIPIENTEMAIL           VARCHAR2(1000 CHAR),
  GIFTCODEREMINDEREMAIL    VARCHAR2(1000 CHAR),
  GCREMEMAILSENDDAYSAFTER  NUMBER(18),
  GIFTCODEEXPIRATIONEMAIL  VARCHAR2(1000 CHAR),
  GCEXPEMAILSENDDAYSPRIOR  NUMBER(18),
  CONTRIBUTIONEMAIL        VARCHAR2(3000 CHAR),
  CREATEDAT                DATE                 NOT NULL,
  UPDATEDAT                DATE                 NOT NULL,
  PROGRAMSETUP             VARCHAR2(1000 CHAR),
  GCREMEMAILFREQUENCY      VARCHAR2(25 CHAR),
  GCREMEMAILSENDTIME       VARCHAR2(25 CHAR),
  GCREMEMAILSENDSTARTDATE  DATE,
  GCREMEMAILSENDENDDATE    DATE,
  CELEBRATIONSETTINGS      CLOB,
  MANAGEREMAIL             VARCHAR2(1000 CHAR),
  BRANDING                 VARCHAR2(1000 CHAR),
  HIERARCHYID              VARCHAR2(50 CHAR),
  EMAILDISPLAYNAME         VARCHAR2(1000 CHAR),
  SIGNATUREIMAGEURL        VARCHAR2(500 CHAR)
);


CREATE TABLE STG_SA_RECIPIENTS
(
  ID                   NUMBER(18)               NOT NULL,
  COMPANYID            VARCHAR2(50 CHAR)        NOT NULL,
  RECIPIENTID          VARCHAR2(50 CHAR)        NOT NULL,
  RECIPIENTSTATE       VARCHAR2(25 CHAR)        NOT NULL,
  RECIPIENTSTATUS      VARCHAR2(25 CHAR)        NOT NULL,
  PROGRAMID            VARCHAR2(50 CHAR)        NOT NULL,
  MILESTONECODE        VARCHAR2(25 CHAR),
  AWARDDATE            DATE,
  AWARDEXPIRATIONDATE  DATE,
  GIFTCODEID           VARCHAR2(50 CHAR),
  GIFTCODEREFERENCE    VARCHAR2(10 CHAR),
  CREATEDBY            VARCHAR2(25 CHAR)        NOT NULL,
  CREATEDREFERENCE     VARCHAR2(64 CHAR),
  CREATEDAT            DATE                     NOT NULL,
  UPDATEDAT            DATE                     NOT NULL,
  AWARDDATETIMEZONE    VARCHAR2(50 CHAR)        DEFAULT 'America/Chicago',
  CELEBRATIONID        VARCHAR2(50 CHAR),
  CELEBRATIONSETTINGS  CLOB,
  PARTICIPANTPERSONID  VARCHAR2(50 CHAR),
  MANAGER1PERSONID     VARCHAR2(50 CHAR),
  MANAGER2PERSONID     VARCHAR2(50 CHAR),
  CELEBRATIONYEAR      NUMBER(18),
  EMAILSETTINGS        VARCHAR2(3000 CHAR),
  AWARDEVENTSENTAT     DATE
);


CREATE UNIQUE INDEX CELEBRATIONSPERSONS_PKEY ON STG_SA_CELEBRATIONSPERSONS
(CELEBRATIONID, PERSONID);


CREATE UNIQUE INDEX COUNTRIES_PKEY ON STG_GC_COUNTRIES
(AWARDID, COUNTRYCODE);


ALTER TABLE STG_GC_COUNTRIES ADD (
  CONSTRAINT COUNTRIES_PKEY
  PRIMARY KEY
  (AWARDID, COUNTRYCODE)
  USING INDEX COUNTRIES_PKEY
  ENABLE VALIDATE);

ALTER TABLE STG_SA_CELEBRATIONSPERSONS ADD (
  CONSTRAINT CELEBRATIONSPERSONS_PKEY
  PRIMARY KEY
  (CELEBRATIONID, PERSONID)
  USING INDEX CELEBRATIONSPERSONS_PKEY
  ENABLE VALIDATE);
