
package com.biperf.core.domain.enums;

public enum ActivityType
{
	// Client customization for WIP 58122
  AWARD_REMINDER, 
  PENDING_APPROVALS, 
  PROGRAM_END, 
  PARTICIPANT_INACTIVITY, 
  BUDGET_END, 
  PURL_INVITATION,
  PURL_CONTRIBUTION,
  PURL_CONTRIBUTION_DEFAULT_INVITEE, 
  PURL_CONTRIBUTION_NON_DEFAULT_INVITEE,
  PURL_VIEW, 
  MANAGER_ALERT, 
  SUBMIT_PROMOTION, 
  FILE_DOWNLOAD, 
  PLATEAU_AWARD_REMINDER, 
  AWARD_GENERATOR_MANAGER_REMINDER, 
  GQ_SURVEY, 
  SURVEY_ALERT, 
  CELEBRATION_MANAGER_REMINDER_ALERT, 
  SSI_APPROVAL, 
  SSI_CLAIM_APPROVAL, 
  SSI_PROGRESS_LOAD_CREATOR_ALERT, 
  SSI_PROGRESS_LOAD_MGR_ALERT, 
  SSI_PROGRESS_LOAD_PAX_ALERT, 
  APPROVER_REMINDER, 
  NOMINATOR_REQMOREINFO_ALERT, 
  APPROVER_REQMOREINFO_REC_ALERT, 
  POLLS_PAX_ALERT, 
  CELEBRATION_PAX_ALERT, 
  NOMINATION_PAX_WINNER_ALERT, 
  NOMINATION_PAX_SAVED_SUBMISSIONS, 
  NOMS_APPROVER_REMAINDER_SUMMARY,
  UNVERIFIED_RECOVERY_CONTACT_ALERT,
  RA_ALERT_NEW_HIRE,
  RA_ALERT_OVER_DUE,
  PENDING_CLAIM_AWARD,
  PENDING_CLAIM_AWARD_NOMINATION;
}
