
package com.biperf.core.utils.fileprocessing;

public enum ColumnLevelOperation
{
  VALIDATION_MINL, VALIDATION_MAXL, VALIDATION_MINV, VALIDATION_MAXV, VALIDATION_REQD, VALIDATION_DFTR, VALIDATION_DPST, VALIDATION_DAFT, VALIDATION_DBFR, VALIDATION_PTRN, VALIDATION_CSLV, FORMAT_UPCS, FORMAT_LOCS, FORMAT_MXCS, FORMAT_INSV, FORMAT_DFTR, FORMAT_DPST, FORMAT_DAFT, FORMAT_DBFR, FORMAT_RMCH, FORMAT_TRIM, FORMAT_INSN
}
