INSERT INTO MODULE_APP
   (MODULE_APP_ID,NAME,DESCRIPTION,IS_MOBILE_ENABLED,AVAILABLE_SIZES,AUDIENCE_TYPE, APP_AUDIENCE_TYPE, TILE_MAPPING_TYPE,  UI_APP_NAME,ADMIN_AUDIENCE_SETUP, CREATED_BY, DATE_CREATED,VERSION)
VALUES
   (3053, 'Plateau Awards Redeem', 'Desc - Plateau Awards Redeem',0, '4X4,4X2,2X2,2X1,1X1','allactivepaxaudience','plateauAwardsRedeemModule','plateauAwardsRedeemModule', 'plateauAwards',1,5662, sysdate, 1)
/