DELETE FROM REPORT_PARAMETER WHERE REPORT_PARAMETER_ID = 3163
/
INSERT INTO REPORT_PARAMETER
(REPORT_PARAMETER_ID, REPORT_ID, PARAMETER_NAME, PARAMETER_CM_KEY, DATABASE_COLUMN, PARAMETER_TYPE, LIST_DEFINITION, PARAMETER_GROUP, SEQUENCE_NUM, DISPLAY_ON_DASHBOARD, COLLECTION_NAME, DEFAULT_VALUE, ADMIN_SELECT_ONLY, HIDE_SHOW_ALL_OPTION, VERSION, CREATED_BY, DATE_CREATED)
VALUES
(3163, 4029, 'promotionStatus', 'PROMOTION_STATUS_FIELD', 'reportPromotionStatusTypeList', 'selectPicklist', 'picklist.reportpromotion.statustype', 'BASICS', 7, 0, 'reportPromotionStatusTypeList', 'live', 0, 0, 0, 0, SYSDATE)
/