DELETE FROM FILTER_MODULE_APP where MODULE_APP_ID = '3012'
/
UPDATE FILTER_MODULE_APP SET ORDER_NUMBER = 5 WHERE MODULE_APP_ID = 3003 AND FILTER_SETUP_TYPE = 'activities'
/
UPDATE FILTER_MODULE_APP SET ORDER_NUMBER = 6 WHERE MODULE_APP_ID = 3002 AND FILTER_SETUP_TYPE = 'activities'
/
UPDATE FILTER_MODULE_APP SET ORDER_NUMBER = 7 WHERE MODULE_APP_ID = 3000 AND FILTER_SETUP_TYPE = 'activities'
/
UPDATE FILTER_MODULE_APP SET ORDER_NUMBER = 8 WHERE MODULE_APP_ID = 3007 AND FILTER_SETUP_TYPE = 'activities'
/
UPDATE FILTER_MODULE_APP SET ORDER_NUMBER = 9 WHERE MODULE_APP_ID = 3010 AND FILTER_SETUP_TYPE = 'activities'
/
UPDATE FILTER_MODULE_APP SET ORDER_NUMBER = 10 WHERE MODULE_APP_ID = 3015 AND FILTER_SETUP_TYPE = 'activities'
/
UPDATE FILTER_MODULE_APP SET ORDER_NUMBER = 11 WHERE MODULE_APP_ID = 3019 AND FILTER_SETUP_TYPE = 'activities'
/
UPDATE FILTER_MODULE_APP SET PRIORITY = 1 WHERE MODULE_APP_ID = 3005 AND FILTER_SETUP_TYPE = 'social'
/