update REPORT_CHART set Y_AXIS_NAME_CM_KEY='BUDGET_PER_CHART_Y_AXIS_NAME' where REPORT_CHART_ID=3029
/
update REPORT_CHART set X_AXIS_NAME_CM_KEY = 'PROMO_NAME', Y_AXIS_NAME_CM_KEY= 'BUDGET_UTIL_CHART_Y_AXIS_NAME' where REPORT_CHART_ID=3031
/