update REPORT_PARAMETER 
set LIST_DEFINITION = 'com.biperf.core.domain.node.reportParameterValueChoices.allLivePromotionsWithAwards'
where REPORT_PARAMETER_ID = 2016 and REPORT_ID = 4002
/
update REPORT_PARAMETER 
set LIST_DEFINITION = 'com.biperf.core.domain.node.reportParameterValueChoices.allLivePromotionsWithAwards'
where REPORT_PARAMETER_ID = 2025 and REPORT_ID = 4003
/
update REPORT_CHART 
set SHOW_PERCENT_VALUES = 0,Y_AXIS_NAME_CM_KEY='BUDGET_PER_CHART_Y_AXIS_NAME'
where REPORT_CHART_ID = 3029 and REPORT_ID = 4006
/
update REPORT_CHART 
set X_AXIS_NAME_CM_KEY='PROMO_NAME',Y_AXIS_NAME_CM_KEY='BUDGET_UTIL_CHART_Y_AXIS_NAME',SEQUENCE_NUM='1'
where REPORT_CHART_ID = 3031 and REPORT_ID = 4006
/
delete from REPORT_PARAMETER where REPORT_PARAMETER_ID = '2072' and REPORT_ID = '4008'
/
delete from REPORT_CHART where REPORT_CHART_ID = 3030 and REPORT_ID = 4006
/
update REPORT_PARAMETER 
set PARAMETER_GROUP = 'EXPORT_SELECTION'
where REPORT_PARAMETER_ID = 2183 and REPORT_ID = 4019
/
update REPORT_PARAMETER 
set SEQUENCE_NUM = '2'
where REPORT_PARAMETER_ID = 2195 and REPORT_ID = 4024
/
update REPORT_PARAMETER 
set SEQUENCE_NUM = '2'
where REPORT_PARAMETER_ID = 2201 and REPORT_ID = 4025
/
update REPORT_PARAMETER 
set SEQUENCE_NUM = '2'
where REPORT_PARAMETER_ID = 2207 and REPORT_ID = 4026
/
update REPORT_PARAMETER 
set SEQUENCE_NUM = '2'
where REPORT_PARAMETER_ID = 2213 and REPORT_ID = 4027
/
update REPORT_PARAMETER 
set SEQUENCE_NUM = '2'
where REPORT_PARAMETER_ID = 2216 and REPORT_ID = 4028
/