UPDATE MODULE_APP SET NAME = 'Browse Awards',DESCRIPTION = 'Desc - Browse Awards ' WHERE MODULE_APP_ID = 3000
/
UPDATE MODULE_APP SET NAME = 'Budget Meter',DESCRIPTION = 'Desc - Budget Meter ' WHERE MODULE_APP_ID = 3001
/
UPDATE MODULE_APP SET NAME = 'Toolkit',DESCRIPTION = 'Desc - Toolkit ' WHERE MODULE_APP_ID = 3002
/
UPDATE MODULE_APP SET NAME = 'Product Claim',DESCRIPTION = 'Desc - Product Claim ' WHERE MODULE_APP_ID = 3004
/
UPDATE MODULE_APP SET NAME = 'Public Recognition',DESCRIPTION = 'Desc - Public Recognition ' WHERE MODULE_APP_ID = 3006
/
UPDATE MODULE_APP SET NAME = 'On The Spot',DESCRIPTION = 'Desc - On The Spot ' WHERE MODULE_APP_ID = 3010
/
UPDATE MODULE_APP SET NAME = 'Challengepoint',DESCRIPTION = 'Desc - Challengepoint ' WHERE MODULE_APP_ID = 3031
/
UPDATE MODULE_APP SET NAME = 'Communications' WHERE MODULE_APP_ID = 3012
/
UPDATE MODULE_APP SET APP_AUDIENCE_TYPE = 'resourceCenter' WHERE MODULE_APP_ID = 3018
/
INSERT INTO MODULE_APP
   (MODULE_APP_ID,NAME,DESCRIPTION,IS_MOBILE_ENABLED,AVAILABLE_SIZES,AUDIENCE_TYPE, APP_AUDIENCE_TYPE, TILE_MAPPING_TYPE,  UI_APP_NAME,ADMIN_AUDIENCE_SETUP, CREATED_BY, DATE_CREATED,VERSION)
VALUES
   (3044, 'Celebration', 'Desc - Celebration',0, '4X4,4X2,2X2,2x1,1x1','allactivepaxaudience','celebrationModule','celebrationModule', 'celebration',0,5662, sysdate, 1)
/
INSERT INTO MODULE_APP
   (MODULE_APP_ID,NAME,DESCRIPTION,IS_MOBILE_ENABLED,AVAILABLE_SIZES,AUDIENCE_TYPE, APP_AUDIENCE_TYPE, TILE_MAPPING_TYPE,  UI_APP_NAME,ADMIN_AUDIENCE_SETUP, CREATED_BY, DATE_CREATED,VERSION)
VALUES
   (3045, 'News', 'Desc - News ',0, '4X4,4X2,2X2,2X1,1X1','allactivepaxaudience','newsModule','newsModule', 'news',1,5662, sysdate, 1)
/
INSERT INTO MODULE_APP
   (MODULE_APP_ID,NAME,DESCRIPTION,IS_MOBILE_ENABLED,AVAILABLE_SIZES,AUDIENCE_TYPE, APP_AUDIENCE_TYPE, TILE_MAPPING_TYPE,  UI_APP_NAME,ADMIN_AUDIENCE_SETUP, CREATED_BY, DATE_CREATED,VERSION)
VALUES
   (3046, 'Engagement', 'Desc - Engagement', 0, '4X4,4X2,2X2,2X1,1X1','allactivepaxaudience','engagementModule','engagementModule', 'engagement', 1, 5662, sysdate, 1)
/
INSERT INTO MODULE_APP
   (MODULE_APP_ID,NAME,DESCRIPTION,IS_MOBILE_ENABLED,AVAILABLE_SIZES,AUDIENCE_TYPE, APP_AUDIENCE_TYPE, TILE_MAPPING_TYPE,  UI_APP_NAME, TEMPLATE_NAME, VIEW_NAME, ADMIN_AUDIENCE_SETUP, CREATED_BY, DATE_CREATED,VERSION)
VALUES
   (3047, 'Engagement Manager', 'Desc - Engagement Manager', 0, '4X4,4X2,2X2,2X1,1X1','allactivepaxaudience','engagementManagerModule','engagementManagerModule', 'engagement', 'engagementModule', 'engagementModuleManager',  1, 5662, sysdate, 1)
/
INSERT INTO MODULE_APP
   (MODULE_APP_ID,NAME,DESCRIPTION,IS_MOBILE_ENABLED,AVAILABLE_SIZES,AUDIENCE_TYPE, APP_AUDIENCE_TYPE, TILE_MAPPING_TYPE,  UI_APP_NAME,ADMIN_AUDIENCE_SETUP, CREATED_BY, DATE_CREATED,VERSION)
VALUES
   (3048, 'Purl Celebrate', 'Desc - Purl Celebrate',0, '4X4,4X2,2X2','allactivepaxaudience','purlCelebrateModule','purlCelebrateModule', 'purlContribute',1,5662, sysdate, 1)
/