CREATE TABLE RPT_BEHAVIOR_DETAIL
(
  RPT_BEHAVIOR_DETAIL_ID     NUMBER(18)         NOT NULL,
  GIVER_USER_ID              NUMBER(18),
  GIVER_LOGIN_ID             VARCHAR2(40 CHAR),
  GIVER_NODE_ID              NUMBER(18),
  GIVER_NODE_NAME            VARCHAR2(255 CHAR),
  GIVER_LAST_NAME            VARCHAR2(40 CHAR),
  GIVER_FIRST_NAME           VARCHAR2(40 CHAR),
  GIVER_MIDDLE_NAME          VARCHAR2(40 CHAR),
  GIVER_PAX_STATUS           VARCHAR2(30 CHAR),
  GIVER_COUNTRY_ID           NUMBER(12),
  GIVER_DEPARTMENT           VARCHAR2(100 CHAR),
  GIVER_JOB_POSITION         VARCHAR2(100 CHAR),
  RECVR_USER_ID              NUMBER(18),
  RECVR_LOGIN_ID             VARCHAR2(40 CHAR),
  RECVR_NODE_ID              NUMBER(18),
  RECVR_NODE_NAME            VARCHAR2(255 CHAR),
  RECVR_LAST_NAME            VARCHAR2(40 CHAR),
  RECVR_FIRST_NAME           VARCHAR2(40 CHAR),
  RECVR_MIDDLE_NAME          VARCHAR2(40 CHAR),
  RECVR_PAX_STATUS           VARCHAR2(30 CHAR),
  RECVR_COUNTRY_ID           NUMBER(12),
  RECVR_DEPARTMENT           VARCHAR2(100 CHAR),
  RECVR_JOB_POSITION         VARCHAR2(100 CHAR),
  CLAIM_ID                   NUMBER(12),
  PROMOTION_ID               NUMBER(18),
  PROMOTION_NAME             VARCHAR2(1000 CHAR),
  BEHAVIOR                   VARCHAR2(40 CHAR),
  DATE_SUBMITTED             DATE,
  DATE_APPROVED              DATE,
  CREATED_BY                 NUMBER(18)         NOT NULL,
  DATE_CREATED               DATE               NOT NULL,
  MODIFIED_BY                NUMBER(18),
  DATE_MODIFIED              DATE,
  VERSION                    NUMBER(18)         NOT NULL,
  CONSTRAINT RPT_BEHAVIOR_DETAIL_ID_PK PRIMARY KEY (RPT_BEHAVIOR_DETAIL_ID)
)
/
CREATE SEQUENCE rpt_behavior_detail_id_pk_sq
/

CREATE TABLE RPT_BEHAVIOR_SUMMARY
(
  RPT_BEHAVIOR_SUMMARY_ID        NUMBER(18) NOT NULL,
  SUM_TYPE                       VARCHAR2(49 CHAR),
  RECORD_TYPE                    VARCHAR2(49 CHAR),
  HEADER_NODE_ID                 NUMBER(18),
  DETAIL_NODE_ID                 NUMBER(18),
  GIVER_RECVR_TYPE               VARCHAR2(10 CHAR),
  PROMOTION_ID                   NUMBER(18),
  BEHAVIOR                       VARCHAR2(40 CHAR),
  DATE_SUBMITTED                 DATE,
  PAX_STATUS                     VARCHAR2(30 CHAR),
  JOB_POSITION                   VARCHAR2(100 CHAR),
  DEPARTMENT                     VARCHAR2(100 CHAR),
  BEHAVIOR_CNT                   NUMBER(12),
  KEY_FIELD_HASH                 RAW(16),
  HIER_LEVEL                     NUMBER,
  IS_LEAF                        NUMBER(1),
  DATE_CREATED                   DATE           NOT NULL,
  CREATED_BY                     NUMBER(18)     NOT NULL,
  MODIFIED_BY                    NUMBER(18),
  DATE_MODIFIED                  DATE,
  CONSTRAINT RPT_BEHAVIOR_SUMMARY_ID_PK PRIMARY KEY (RPT_BEHAVIOR_SUMMARY_ID)
)
/
CREATE SEQUENCE RPT_BEHAVIOR_SUMMARY_ID_PK_SQ
/