ALTER TABLE RPT_SSI_CONTEST_DETAIL MODIFY PROMOTION_ID NUMBER(12)
/
ALTER TABLE RPT_SSI_CONTEST_DETAIL MODIFY PROMOTION_NAME VARCHAR2(1000)
/
ALTER TABLE RPT_SSI_AWARD_DETAIL MODIFY PROMOTION_ID NUMBER(12)
/
ALTER TABLE RPT_SSI_AWARD_DETAIL MODIFY JOURNAL_ID NUMBER(12)
/
ALTER TABLE RPT_SSI_AWARD_DETAIL MODIFY COUNTRY_ID NUMBER(12)
/
ALTER TABLE RPT_SSI_AWARD_DETAIL MODIFY SSI_CONTEST_NAME VARCHAR2(50 CHAR)
/
ALTER TABLE RPT_SSI_AWARD_DETAIL MODIFY PROMOTION_NAME VARCHAR2(1000 CHAR)
/
ALTER TABLE RPT_SSI_AWARD_DETAIL MODIFY PAYOUT_TYPE VARCHAR2(40)
/
ALTER TABLE RPT_SSI_AWARD_DETAIL ADD PAYOUT_DESCRIPTION VARCHAR2(200 CHAR)
/
