ALTER TABLE RPT_PAX_PROMO_ELIG_SPEAUD_TEAM MODIFY PROMOTION_ID NUMBER(18)
/
ALTER TABLE RPT_PAX_PROMO_ELIG_SPEAUD_TEAM MODIFY ELIG_COUNT NUMBER(18)
/
ALTER TABLE RPT_PAX_PROMO_ELIG_SPEAUD_NODE MODIFY PROMOTION_TYPE VARCHAR2(80 CHAR)
/
ALTER TABLE RPT_PAX_PROMO_ELIG_SPEAUD_NODE MODIFY PROMOTION_STATUS VARCHAR2(30 CHAR)
/
ALTER TABLE RPT_PAX_PROMO_ELIG_SPEAUD_NODE MODIFY PAX_STATUS VARCHAR2(30 CHAR)
/
ALTER TABLE RPT_PAX_PROMO_ELIG_SPEAUD_NODE MODIFY ELIG_COUNT NUMBER(18)
/