CREATE TABLE APPROVER 
  ( 
     APPROVER_CRITERIA_ID NUMBER(18,0) NOT NULL, 
     USER_ID              NUMBER(18,0) NOT NULL, 
     CREATED_BY           NUMBER(18,0) NOT NULL, 
     DATE_CREATED         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, 
     MODIFIED_BY          NUMBER(18,0), 
     DATE_MODIFIED        TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
     VERSION              NUMBER(18,0) DEFAULT 1
  )
/
ALTER TABLE APPROVER
ADD CONSTRAINT APPROVER_FK FOREIGN KEY (APPROVER_CRITERIA_ID)
REFERENCES APPROVER_CRITERIA (APPROVER_CRITERIA_ID)
/
ALTER TABLE APPROVER
ADD CONSTRAINT APPLICATION_USER_FK FOREIGN KEY (USER_ID)
REFERENCES APPLICATION_USER (USER_ID)
/
