ALTER TABLE RPT_CLAIM_DETAIL MODIFY PROMOTION_NAME VARCHAR2(1000)
/
ALTER TABLE RPT_CLAIM_DETAIL MODIFY NODE_NAME VARCHAR2(255)
/
ALTER TABLE RPT_CLAIM_DETAIL MODIFY SUBMITTER_POINTS NUMBER(12)
/
ALTER TABLE RPT_CLAIM_SUMMARY MODIFY DETAIL_NODE_ID NUMBER(18)
/
ALTER TABLE RPT_CLAIM_SUMMARY MODIFY CLAIM_COUNT NUMBER(12)
/