ALTER TABLE RPT_PROGRAM_REFERENCE MODIFY FIRST_NAME VARCHAR2(40 CHAR)
/
ALTER TABLE RPT_PROGRAM_REFERENCE MODIFY LAST_NAME VARCHAR2(40 CHAR)
/
ALTER TABLE RPT_PROGRAM_REFERENCE MODIFY ADDR1 VARCHAR2(4000 CHAR)
/
ALTER TABLE RPT_PROGRAM_REFERENCE MODIFY ADDR2 VARCHAR2(4000 CHAR)
/
ALTER TABLE RPT_PROGRAM_REFERENCE MODIFY CITY VARCHAR2(40 CHAR)
/
ALTER TABLE RPT_PROGRAM_REFERENCE MODIFY STATE VARCHAR2(4000 CHAR)
/
ALTER TABLE RPT_PROGRAM_REFERENCE MODIFY POSTAL_CODE VARCHAR2(4000 CHAR)
/
ALTER TABLE RPT_PROGRAM_REFERENCE MODIFY COUNTRY VARCHAR2(30 CHAR)
/
ALTER TABLE RPT_PROGRAM_REFERENCE MODIFY EMAIL VARCHAR2(75 CHAR)
/
ALTER TABLE RPT_PROGRAM_REFERENCE MODIFY REFERENCE_NUMBER VARCHAR2(128 CHAR)
/
ALTER TABLE RPT_PROGRAM_REFERENCE MODIFY AWARD_LEVEL VARCHAR2(40 CHAR)
/
ALTER TABLE RPT_PROGRAM_REFERENCE MODIFY PROMOTION_NAME VARCHAR2(1000 CHAR)
/
ALTER TABLE RPT_PURL_CONTRIBUTION_SUMMARY MODIFY RECIPIENT_COUNT NUMBER(16)
/
ALTER TABLE RPT_PURL_CONTRIBUTION_SUMMARY MODIFY JOB_POSITION VARCHAR2(100 BYTE)
/
ALTER TABLE RPT_PURL_CONTRIBUTION_SUMMARY MODIFY DEPARTMENT VARCHAR2(100 BYTE)
/
ALTER TABLE RPT_PURL_CONTRIBUTION_SUMMARY MODIFY NUM_CONTRIBUTORS_INVITED NUMBER(12)
/
ALTER TABLE RPT_PURL_CONTRIBUTION_SUMMARY MODIFY NUM_CONTRIBUTORS_ACTUAL NUMBER(12)
/
ALTER TABLE RPT_PURL_CONTRIBUTION_DETAIL MODIFY PROMOTION_NAME VARCHAR2(1000 CHAR)
/
ALTER TABLE RPT_PURL_CONTRIBUTION_DETAIL MODIFY NODE_NAME VARCHAR2(255 CHAR)
/
ALTER TABLE RPT_PURL_CONTRIBUTION_DETAIL MODIFY RECIPIENT_LAST_NAME VARCHAR2(40 CHAR)
/
ALTER TABLE RPT_PURL_CONTRIBUTION_DETAIL MODIFY RECIPIENT_FIRST_NAME VARCHAR2(40 CHAR)
/
ALTER TABLE RPT_PURL_CONTRIBUTION_DETAIL MODIFY RECIPIENT_USER_NAME VARCHAR2(40 CHAR)
/
ALTER TABLE RPT_PURL_CONTRIBUTION_DETAIL MODIFY RECIPIENT_EMAIL_ADDR VARCHAR2(75 CHAR)
/
ALTER TABLE RPT_PURL_CONTRIBUTION_DETAIL MODIFY RECIPIENT_PAX_STATUS VARCHAR2(10 CHAR)
/
ALTER TABLE RPT_PURL_CONTRIBUTION_DETAIL MODIFY RECIPIENT_JOB_POSITION VARCHAR2(100 CHAR)
/
ALTER TABLE RPT_PURL_CONTRIBUTION_DETAIL MODIFY RECIPIENT_DEPARTMENT VARCHAR2(100 CHAR)
/
ALTER TABLE RPT_PURL_CONTRIBUTION_DETAIL MODIFY MANAGER_NODE_NAME VARCHAR2(255 CHAR)
/
ALTER TABLE RPT_PURL_CONTRIBUTION_DETAIL MODIFY MANAGER_LAST_NAME VARCHAR2(40 CHAR)
/
ALTER TABLE RPT_PURL_CONTRIBUTION_DETAIL MODIFY MANAGER_FIRST_NAME VARCHAR2(40 CHAR)
/
ALTER TABLE RPT_PURL_CONTRIBUTION_DETAIL MODIFY MANAGER_USER_NAME VARCHAR2(40 CHAR)
/
ALTER TABLE RPT_PURL_CONTRIBUTION_DETAIL MODIFY MANAGER_EMAIL_ADDR VARCHAR2(75 CHAR)
/
ALTER TABLE RPT_PURL_RECIPIENT_DETAIL MODIFY PROMOTION_NAME VARCHAR2(1000 CHAR)
/
ALTER TABLE RPT_PURL_RECIPIENT_DETAIL MODIFY RECIPIENT_LAST_NAME VARCHAR2(40 CHAR)
/
ALTER TABLE RPT_PURL_RECIPIENT_DETAIL MODIFY RECIPIENT_FIRST_NAME VARCHAR2(40 CHAR)
/
ALTER TABLE RPT_PURL_RECIPIENT_DETAIL MODIFY RECIPIENT_USER_NAME VARCHAR2(40 CHAR)
/
ALTER TABLE RPT_PURL_RECIPIENT_DETAIL MODIFY RECIPIENT_EMAIL_ADDR VARCHAR2(75 CHAR)
/
ALTER TABLE RPT_PURL_RECIPIENT_DETAIL MODIFY RECIPIENT_JOB_POSITION VARCHAR2(100 CHAR)
/
ALTER TABLE RPT_PURL_RECIPIENT_DETAIL MODIFY RECIPIENT_DEPARTMENT VARCHAR2(100 CHAR)
/
ALTER TABLE RPT_PURL_RECIPIENT_SUMMARY MODIFY RECIPIENT_COUNT NUMBER(16)
/
ALTER TABLE RPT_RECOG_BEHAVIOR_SUMMARY MODIFY RECOGNITION_CNT NUMBER(12)
/
ALTER TABLE RPT_RECOGNITION_DETAIL MODIFY PROMOTION_NAME VARCHAR2(1000)
/
ALTER TABLE RPT_RECOGNITION_DETAIL MODIFY GIVER_COUNTRY_ID NUMBER(12)
/
ALTER TABLE RPT_RECOGNITION_DETAIL MODIFY RECVR_COUNTRY_ID NUMBER(12)
/
ALTER TABLE RPT_RECOGNITION_DETAIL
ADD REASON_DENIED VARCHAR2(18)
/
ALTER TABLE RPT_RECOGNITION_SUMMARY MODIFY ACTUAL_GIVER_RECVR_CNT NUMBER(18)
/
ALTER TABLE RPT_RECOGNITION_SUMMARY MODIFY RECOGNITION_CNT NUMBER(12)
/
ALTER TABLE RPT_RECOGNITION_SUMMARY MODIFY MEDIA_AMT NUMBER(20,4)
/
ALTER TABLE RPT_RECOGNITION_SUMMARY MODIFY PLATEAU_EARNED NUMBER
/
ALTER TABLE RPT_RECOGNITION_SUMMARY MODIFY SWEEPSTAKES_WON NUMBER
/
ALTER TABLE RPT_RECOGNITION_SUMMARY MODIFY BADGES_EARNED NUMBER
/