ALTER TABLE RPT_CLAIM_PRODUCT_SUMMARY MODIFY TOTAL_QUANTITY NUMBER(18,4)
/
ALTER TABLE RPT_CLAIM_PRODUCT_SUMMARY MODIFY PRODUCT_CATEGORY_NAME VARCHAR2(50)
/
ALTER TABLE RPT_CLAIM_PRODUCT_SUMMARY MODIFY PRODUCT_SUBCATEGORY_NAME VARCHAR2(50)
/