ALTER TABLE RPT_QCARD_DETAIL MODIFY USER_ID NUMBER(12)
/
ALTER TABLE RPT_QCARD_DETAIL MODIFY JOURNAL_ID NUMBER(12)
/
ALTER TABLE RPT_QCARD_DETAIL MODIFY CERT_NUM VARCHAR2(255)
/
ALTER TABLE RPT_QCARD_DETAIL MODIFY FIRST_CERT VARCHAR2(255)
/
ALTER TABLE RPT_QCARD_DETAIL MODIFY SEC_CERT VARCHAR2(255)
/
ALTER TABLE RPT_QCARD_DETAIL MODIFY TRANSACTION_AMOUNT NUMBER(12,2)
/
ALTER TABLE RPT_QCARD_DETAIL MODIFY COUNTRY_ID NUMBER(12)
/