ALTER TABLE RPT_QUIZ_ACTIVITY_DETAIL MODIFY PROMO_QUIZ_NAME VARCHAR2(1000)
/
ALTER TABLE RPT_QUIZ_ACTIVITY_DETAIL MODIFY QUIZ_NAME VARCHAR2(200)
/
ALTER TABLE RPT_QUIZ_ACTIVITY_DETAIL MODIFY QUIZ_SCORE NUMBER(12,0)
/
ALTER TABLE RPT_QUIZ_ACTIVITY_DETAIL MODIFY QUIZ_RESULT VARCHAR2(255 CHAR)
/
ALTER TABLE RPT_QUIZ_ACTIVITY_DETAIL MODIFY QUIZ_PASSING_SCORE NUMBER(12,0)
/
ALTER TABLE RPT_QUIZ_ACTIVITY_DETAIL MODIFY QUIZ_QUESTION_COUNT NUMBER(12,0)
/
ALTER TABLE RPT_QUIZ_ACTIVITY_DETAIL MODIFY PARTICIPANT_ID NUMBER(18,0)
/
ALTER TABLE RPT_QUIZ_ACTIVITY_DETAIL MODIFY PARTICIPANT_LAST_NAME VARCHAR2(40)
/
ALTER TABLE RPT_QUIZ_ACTIVITY_DETAIL MODIFY PARTICIPANT_FIRST_NAME VARCHAR2(40)
/
ALTER TABLE RPT_QUIZ_ACTIVITY_DETAIL MODIFY PARTICIPANT_MIDDLE_NAME VARCHAR2(40)
/
ALTER TABLE RPT_QUIZ_ACTIVITY_DETAIL MODIFY JOB_TITLE VARCHAR2(100)
/
ALTER TABLE RPT_QUIZ_ACTIVITY_DETAIL MODIFY DEPARTMENT VARCHAR2(100)
/
ALTER TABLE RPT_QUIZ_ACTIVITY_DETAIL MODIFY AWARD_TYPE VARCHAR2(40)
/
ALTER TABLE RPT_QUIZ_ACTIVITY_DETAIL MODIFY AWARD_AMOUNT NUMBER(18,2)
/
ALTER TABLE RPT_QUIZ_ACTIVITY_DETAIL MODIFY QUIZ_CLAIM_ID NUMBER(12,0)
/
ALTER TABLE RPT_QUIZ_ACTIVITY_DETAIL MODIFY COUNTRY_ID NUMBER(12)
/
ALTER TABLE RPT_QUIZ_ACTIVITY_SUMMARY MODIFY AWARD_TYPE VARCHAR2(255)
/
ALTER TABLE RPT_QUIZ_ACTIVITY_SUMMARY MODIFY AWARD_GIVEN NUMBER(18,2)
/
ALTER TABLE RPT_QUIZ_ANALYSIS MODIFY Q_IN_POOL NUMBER(18,0)
/
ALTER TABLE RPT_QUIZ_QQ_ANALYSIS MODIFY NUMBER_OF_TIMES_ASKED NUMBER(18,0)
/
ALTER TABLE RPT_QUIZ_QQ_ANALYSIS MODIFY NUMBER_OF_CORRECT_RESPONSES NUMBER(10)
/
ALTER TABLE RPT_QUIZ_QQA_ANALYSIS MODIFY NUMBER_OF_TIMES_SELECTED NUMBER(10)
/
ALTER TABLE RPT_QUIZ_QQA_ANALYSIS MODIFY QQA_ANSWER_CM_KEY VARCHAR2(255)
/