CREATE SEQUENCE CASH_CURRENCY_HISTORY_ID_PK_SQ START WITH 250 INCREMENT BY 1
/
CREATE TABLE CASH_CURRENCY_HISTORY (
    CASH_CURRENCY_HISTORY_ID 	   NUMBER(18,0) NOT NULL,
    FROM_CUR					   VARCHAR2(10),
    TO_CUR						   VARCHAR2(10),
    RT_TYPE						   VARCHAR2(10),
    EFFDT						   DATE,
	BPOM_ENTERED_RATE			   NUMBER(10,5),
	RATE_MULT					   NUMBER(10,5),
	RATE_DIV					   NUMBER(10),
	DATE_CREATED       DATE        NOT NULL,
    CREATED_BY         NUMBER(18)  NOT NULL,
    DATE_MODIFIED      DATE,
    MODIFIED_BY        NUMBER(18),
    VERSION            NUMBER(18)
  )
/
ALTER TABLE CASH_CURRENCY_HISTORY
ADD CONSTRAINT CASH_CURRENCY_HISTORY_PK_SQ PRIMARY KEY (CASH_CURRENCY_HISTORY_ID)
USING INDEX
/