ALTER TABLE RPT_ENROLLMENT_DETAIL MODIFY PRIMARY_ADDRESS_TYPE VARCHAR2(255)
/
ALTER TABLE RPT_ENROLLMENT_DETAIL MODIFY COUNTRY_ID NUMBER(12)
/
ALTER TABLE RPT_ENROLLMENT_DETAIL MODIFY LANGUAGE_PREFERENCE VARCHAR2(10)
/
ALTER TABLE RPT_ENROLLMENT_SUMMARY MODIFY ENROLLMENT_COUNT NUMBER(18)
/