ALTER TABLE RPT_AWARD_EARNINGS MODIFY LAST_NAME VARCHAR2(40 CHAR)
/
ALTER TABLE RPT_AWARD_EARNINGS MODIFY FIRST_NAME VARCHAR2(40 CHAR)
/
ALTER TABLE RPT_AWARD_EARNINGS MODIFY REFERENCE_NUMBER VARCHAR2(128 CHAR)
/
ALTER TABLE RPT_AWARD_EARNINGS MODIFY EMAIL_ADDRESS VARCHAR2(75 CHAR)
/
ALTER TABLE RPT_AWARD_EARNINGS MODIFY SSN VARCHAR2(40 CHAR)
/
ALTER TABLE RPT_AWARD_EARNINGS MODIFY ADDR1 VARCHAR2(4000 CHAR)
/
ALTER TABLE RPT_AWARD_EARNINGS MODIFY ADDR2 VARCHAR2(4000 CHAR)
/
ALTER TABLE RPT_AWARD_EARNINGS MODIFY ADDR3 VARCHAR2(4000 CHAR)
/
ALTER TABLE RPT_AWARD_EARNINGS MODIFY CITY VARCHAR2(40 CHAR)
/
ALTER TABLE RPT_AWARD_EARNINGS MODIFY STATE VARCHAR2(4000 CHAR)
/
ALTER TABLE RPT_AWARD_ITEM_ACTIVITY MODIFY COUNTRY_ID NUMBER(12)
/
ALTER TABLE RPT_AWARD_ITEM_ACTIVITY MODIFY PROGRAM_ID VARCHAR2(40 CHAR)
/
ALTER TABLE RPT_AWARD_ITEM_SELECTION MODIFY PROMOTION_NAME VARCHAR2(1000)
/
ALTER TABLE RPT_AWARD_ITEM_SELECTION MODIFY COUNTRY_ID NUMBER(12)
/
ALTER TABLE RPT_AWARD_ORDER_DETAIL MODIFY PROMOTION_NAME VARCHAR2(1000)
/
ALTER TABLE RPT_AWARD_ORDER_DETAIL MODIFY FIRST_NAME VARCHAR2(40)
/
ALTER TABLE RPT_AWARD_ORDER_DETAIL MODIFY ADDRESS_1 VARCHAR2(4000)
/
ALTER TABLE RPT_AWARD_ORDER_DETAIL MODIFY ADDRESS_2 VARCHAR2(4000)
/
ALTER TABLE RPT_AWARD_ORDER_DETAIL MODIFY MIDDLE_NAME VARCHAR2(40)
/
ALTER TABLE RPT_AWARD_ORDER_DETAIL MODIFY LAST_NAME VARCHAR2(40)
/