CREATE SEQUENCE RPT_CASH_BUDGET_TRAN_DTL_PK_SQ
  START WITH 1001
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER
/

CREATE SEQUENCE RPT_CASH_BUDGT_USAGE_DTL_PK_SQ
  START WITH 1001
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER
/

CREATE TABLE RPT_CASH_BUDGET_PROMOTION
(
  BUDGET_ID          NUMBER(18)                 NOT NULL,
  BUDGET_MASTER_ID   NUMBER(18)                 NOT NULL,
  BUDGET_SEGMENT_ID  NUMBER(18)                 NOT NULL,
  PROMOTION_ID       NUMBER(18)                 NOT NULL,
  DISTRIBUTION_TYPE  VARCHAR2(10 CHAR)
)
/

COMMENT ON TABLE RPT_CASH_BUDGET_PROMOTION IS 'The RPT_CASH_BUDGET_PROMOTION table for the cash budget report.'
/
COMMENT ON COLUMN RPT_CASH_BUDGET_PROMOTION.BUDGET_ID IS 'from budget table'
/
COMMENT ON COLUMN RPT_CASH_BUDGET_PROMOTION.BUDGET_MASTER_ID IS 'from budget_master table'
/
COMMENT ON COLUMN RPT_CASH_BUDGET_PROMOTION.PROMOTION_ID IS 'from promotion table'
/



CREATE TABLE RPT_CASH_BUDGET_TRANS_DETAIL
(
  RPT_CASH_BUDGET_TRANS_DTL_ID    NUMBER(18)    NOT NULL,
  BUDGET_ID                       NUMBER(18)    NOT NULL,
  BUDGET_MASTER_ID                NUMBER(18),
  BUDGET_SEGMENT_ID               NUMBER(18),
  BUDGET_STATUS                   VARCHAR2(30 CHAR),
  BUDGET_TRANS_TYPE               VARCHAR2(30 CHAR),
  JOURNAL_ID                      NUMBER(12),
  TRANS_DATE                      DATE,
  TRANS_AMOUNT                    NUMBER(20,8),
  RECIPIENT_USER_ID               NUMBER(18),
  RECIPIENT_NAME                  VARCHAR2(120 CHAR),
  PROMOTION_ID                    NUMBER(18),
  PROMOTION_NAME                  VARCHAR2(1000 CHAR),
  DATE_CREATED                    DATE          NOT NULL,
  CREATED_BY                      NUMBER(18)    NOT NULL,
  RECIPIENT_COUNTRY_ID            NUMBER(12),
  BUDGET_HISTORY_ID               NUMBER(18),
  MERCH_ORDER_ID                  NUMBER(18),
  MODIFIED_BY                     NUMBER(18),
  DATE_MODIFIED                   DATE,
  VERSION                         NUMBER(18),
  BUDGET_REALLOCATION_HISTORY_ID  NUMBER
)
/

COMMENT ON TABLE RPT_CASH_BUDGET_TRANS_DETAIL IS 'The RPT_CASH_BUDGET_TRANS_DETAIL table for the cash budget report.'
/
COMMENT ON COLUMN RPT_CASH_BUDGET_TRANS_DETAIL.RPT_CASH_BUDGET_TRANS_DTL_ID IS 'System generated Primary Key'
/
COMMENT ON COLUMN RPT_CASH_BUDGET_TRANS_DETAIL.BUDGET_ID IS 'from budget table'
/
COMMENT ON COLUMN RPT_CASH_BUDGET_TRANS_DETAIL.BUDGET_MASTER_ID IS 'from budget_master table'
/
COMMENT ON COLUMN RPT_CASH_BUDGET_TRANS_DETAIL.BUDGET_TRANS_TYPE IS 'Psuedo column for the type of record stored - deposit or expenditure'
/
COMMENT ON COLUMN RPT_CASH_BUDGET_TRANS_DETAIL.JOURNAL_ID IS 'This field is used for expenditures - from journal'
/
COMMENT ON COLUMN RPT_CASH_BUDGET_TRANS_DETAIL.TRANS_DATE IS 'Date of the deposit addition or expenditure to the budget'
/
COMMENT ON COLUMN RPT_CASH_BUDGET_TRANS_DETAIL.TRANS_AMOUNT IS 'Amount of the deposit addition or expenditure to the budget'
/
COMMENT ON COLUMN RPT_CASH_BUDGET_TRANS_DETAIL.RECIPIENT_USER_ID IS 'This field is used for expenditures - from application_user'
/
COMMENT ON COLUMN RPT_CASH_BUDGET_TRANS_DETAIL.RECIPIENT_NAME IS 'This field is used for expenditures'
/
COMMENT ON COLUMN RPT_CASH_BUDGET_TRANS_DETAIL.PROMOTION_ID IS 'This field is used for expenditures - from promotion'
/
COMMENT ON COLUMN RPT_CASH_BUDGET_TRANS_DETAIL.PROMOTION_NAME IS 'This field is used for expenditures'
/
COMMENT ON COLUMN RPT_CASH_BUDGET_TRANS_DETAIL.DATE_CREATED IS 'Audit field'
/
COMMENT ON COLUMN RPT_CASH_BUDGET_TRANS_DETAIL.CREATED_BY IS 'Audit field'
/

CREATE TABLE RPT_CASH_BUDGET_USAGE_DETAIL
(
  RPT_CASH_BUDGET_USAGE_DTL_ID  NUMBER(18)      NOT NULL,
  NODE_ID                       NUMBER(18),
  BUDGET_NAME_CM_ASSET_CODE     VARCHAR2(80 CHAR),
  BUDGET_NAME_CM_KEY            VARCHAR2(30 CHAR),
  BUDGET_OWNER_ID               NUMBER(18),
  BUDGET_OWNER_NAME             VARCHAR2(80 CHAR),
  BUDGET_OWNER_TYPE             VARCHAR2(80 CHAR),
  BUDGET_AMT                    NUMBER(20,4),
  BUDGET_USED                   NUMBER(20,4),
  BUDGET_REMAINING              NUMBER(20,4),
  BUDGET_MASTER_ID              NUMBER(18),
  BUDGET_SEGMENT_ID             NUMBER(18),
  BUDGET_ID                     NUMBER(18)      NOT NULL,
  BUDGET_STATUS                 VARCHAR2(10 CHAR),
  INCEPTION_DATE                DATE,
  OVERRIDEABLE                  VARCHAR2(30 CHAR),
  CAP_AMOUNT                    NUMBER(18),
  COST_CENTER                   VARCHAR2(30 CHAR),
  BUDGET_MASTER_NAME            VARCHAR2(50 CHAR),
  RULE_FOR_FINAL_PAYOUT         VARCHAR2(60 CHAR),
  NODE_OWNER                    VARCHAR2(50 CHAR),
  PROMOTION_STRING              VARCHAR2(300 CHAR),
  BUDGET_TYPE                   VARCHAR2(30 CHAR),
  IS_ACTIVE                     NUMBER(1),
  START_DATE                    DATE,
  END_DATE                      DATE,
  BUDGET_OWNER_CNTRY_ID         NUMBER(12),
  DATE_CREATED                  DATE            NOT NULL,
  CREATED_BY                    NUMBER(18)      NOT NULL,
  MODIFIED_BY                   NUMBER(18),
  DATE_MODIFIED                 DATE,
  VERSION                       NUMBER(18),
  MULTI_PROMOTION               VARCHAR2(10 CHAR),
  REALLOCATED_AMOUNT            NUMBER
)
/

COMMENT ON TABLE RPT_CASH_BUDGET_USAGE_DETAIL IS 'The RPT_CASH_BUDGET_USAGE_DETAIL table for the cash budget report.'
/
COMMENT ON COLUMN RPT_CASH_BUDGET_USAGE_DETAIL.RPT_CASH_BUDGET_USAGE_DTL_ID IS 'System generated Primary Key'
/
COMMENT ON COLUMN RPT_CASH_BUDGET_USAGE_DETAIL.NODE_ID IS 'from node table'
/
COMMENT ON COLUMN RPT_CASH_BUDGET_USAGE_DETAIL.BUDGET_NAME_CM_ASSET_CODE IS 'Asset code used to get budget name from Content Manager'
/
COMMENT ON COLUMN RPT_CASH_BUDGET_USAGE_DETAIL.BUDGET_NAME_CM_KEY IS 'Key used to get budget name from Content Manager'
/
COMMENT ON COLUMN RPT_CASH_BUDGET_USAGE_DETAIL.BUDGET_OWNER_ID IS 'from application_user if type Pax or from node if type Node'
/
COMMENT ON COLUMN RPT_CASH_BUDGET_USAGE_DETAIL.BUDGET_OWNER_NAME IS 'Psuedo column for the Pax name or node name of the budget owner'
/
COMMENT ON COLUMN RPT_CASH_BUDGET_USAGE_DETAIL.BUDGET_OWNER_TYPE IS 'Psuedo column for the type of record stored - Pax or Node'
/
COMMENT ON COLUMN RPT_CASH_BUDGET_USAGE_DETAIL.BUDGET_AMT IS 'Sum of all budget deposit additions'
/
COMMENT ON COLUMN RPT_CASH_BUDGET_USAGE_DETAIL.BUDGET_USED IS 'Sum of all budget expenditures'
/
COMMENT ON COLUMN RPT_CASH_BUDGET_USAGE_DETAIL.BUDGET_REMAINING IS 'Budget deposits - budget expenditures'
/
COMMENT ON COLUMN RPT_CASH_BUDGET_USAGE_DETAIL.BUDGET_MASTER_ID IS 'from budget_master table'
/
COMMENT ON COLUMN RPT_CASH_BUDGET_USAGE_DETAIL.BUDGET_ID IS 'from budget table'
/
COMMENT ON COLUMN RPT_CASH_BUDGET_USAGE_DETAIL.INCEPTION_DATE IS 'Start date of the budget'
/
COMMENT ON COLUMN RPT_CASH_BUDGET_USAGE_DETAIL.OVERRIDEABLE IS 'From promotion for cap_type - hard or soft cap budget'
/
COMMENT ON COLUMN RPT_CASH_BUDGET_USAGE_DETAIL.CAP_AMOUNT IS 'Max budget that can be used'
/
COMMENT ON COLUMN RPT_CASH_BUDGET_USAGE_DETAIL.BUDGET_MASTER_NAME IS 'from budget_master table'
/
COMMENT ON COLUMN RPT_CASH_BUDGET_USAGE_DETAIL.RULE_FOR_FINAL_PAYOUT IS 'the rule for payout if the budget_type is central'
/
COMMENT ON COLUMN RPT_CASH_BUDGET_USAGE_DETAIL.NODE_OWNER IS 'from node table'
/
COMMENT ON COLUMN RPT_CASH_BUDGET_USAGE_DETAIL.PROMOTION_STRING IS 'the promotions that are tied to the budget'
/
COMMENT ON COLUMN RPT_CASH_BUDGET_USAGE_DETAIL.BUDGET_TYPE IS 'from budget_master table'
/
COMMENT ON COLUMN RPT_CASH_BUDGET_USAGE_DETAIL.IS_ACTIVE IS 'from budget_master table'
/
COMMENT ON COLUMN RPT_CASH_BUDGET_USAGE_DETAIL.START_DATE IS 'from budget table'
/
COMMENT ON COLUMN RPT_CASH_BUDGET_USAGE_DETAIL.END_DATE IS 'from budget table'
/


ALTER TABLE RPT_CASH_BUDGET_TRANS_DETAIL ADD (
  CONSTRAINT RPT_CASH_BUDGET_TRANS_DTL_PK
  PRIMARY KEY
  (RPT_CASH_BUDGET_TRANS_DTL_ID)
  ENABLE VALIDATE)
/


ALTER TABLE RPT_CASH_BUDGET_USAGE_DETAIL ADD (
  CONSTRAINT RPT_CASH_BUDGET_USAGE_DTL_PK
  PRIMARY KEY
  (RPT_CASH_BUDGET_USAGE_DTL_ID)
  ENABLE VALIDATE)
/