CREATE TABLE VIDEO_UPLOAD_DETAIL
	(VIDEO_UPLOAD_DETAIL_ID 	NUMBER(18) NOT NULL,
	 VIDEO_URL          		VARCHAR2(400),  
	 THUMBNAIL_URL      		VARCHAR2(400),
	 CREATED_BY 				NUMBER(18) NOT NULL,
	 DATE_CREATED       		DATE NOT NULL,
	 MODIFIED_BY 				NUMBER(18),
	 DATE_MODIFIED      		DATE,
	 VERSION            		NUMBER(18) NOT NULL)
/

ALTER TABLE VIDEO_UPLOAD_DETAIL
ADD CONSTRAINT VIDEO_UPLOAD_DETAIL_PK PRIMARY KEY (VIDEO_UPLOAD_DETAIL_ID)
USING INDEX
/

CREATE INDEX VIDEO_UPLOAD_DETAIL_IDX2 ON VIDEO_UPLOAD_DETAIL
  (THUMBNAIL_URL)
/

COMMENT ON TABLE VIDEO_UPLOAD_DETAIL IS 'Lookup table for Java use.'
/
COMMENT ON COLUMN VIDEO_UPLOAD_DETAIL.VIDEO_UPLOAD_DETAIL_ID IS 'System generated PK.'
/
COMMENT ON COLUMN VIDEO_UPLOAD_DETAIL.VIDEO_URL IS 'Java use only. Full video URL.'
/
COMMENT ON COLUMN VIDEO_UPLOAD_DETAIL.THUMBNAIL_URL IS 'Java use only. Preview image.'
/
COMMENT ON COLUMN VIDEO_UPLOAD_DETAIL.CREATED_BY IS 'Audit Column for new record, userID of the person'
/
COMMENT ON COLUMN VIDEO_UPLOAD_DETAIL.DATE_CREATED IS 'Audit column for new record'
/
COMMENT ON COLUMN VIDEO_UPLOAD_DETAIL.MODIFIED_BY IS 'Audit Column for tracking updates, userID of the person'
/
COMMENT ON COLUMN VIDEO_UPLOAD_DETAIL.DATE_MODIFIED IS 'Audit Column for tracking updates'
/
COMMENT ON COLUMN VIDEO_UPLOAD_DETAIL.VERSION IS 'Used for Java optimistic locking'
/

CREATE SEQUENCE VIDEO_UPLOAD_DETAIL_PK_SQ
  INCREMENT BY 1
  START WITH 3000
  MINVALUE 1
  MAXVALUE 999999999999999999999999999
  NOCYCLE
  NOORDER
  CACHE 20
/


