ALTER SEQUENCE RPT_NOMINATION_DETAIL_PK_SQ
  MAXVALUE 9999999999999999999999999
  NOCYCLE
  NOORDER
  CACHE 20
/
ALTER TABLE RPT_NOMINATION_DETAIL DROP COLUMN GIVER_FULL_NAME
/
ALTER TABLE RPT_NOMINATION_DETAIL DROP COLUMN GIVER_DEPARTMENT
/
ALTER TABLE RPT_NOMINATION_DETAIL DROP COLUMN GIVER_JOB_POSITION
/
ALTER TABLE RPT_NOMINATION_DETAIL DROP COLUMN GIVER_LOGIN_ID
/
ALTER TABLE RPT_NOMINATION_DETAIL DROP COLUMN GIVER_ACTIVITY_ID
/
ALTER TABLE RPT_NOMINATION_DETAIL DROP COLUMN RECVR_FULL_NAME
/
ALTER TABLE RPT_NOMINATION_DETAIL DROP COLUMN RECVR_DEPARTMENT
/
ALTER TABLE RPT_NOMINATION_DETAIL DROP COLUMN RECVR_JOB_POSITION
/
ALTER TABLE RPT_NOMINATION_DETAIL DROP COLUMN RECVR_LOGIN_ID
/
ALTER TABLE RPT_NOMINATION_DETAIL DROP COLUMN RECVR_ACTIVITY_ID
/
ALTER TABLE RPT_NOMINATION_DETAIL DROP COLUMN CUMULATIVE_NOM_CNT
/
ALTER TABLE RPT_NOMINATION_DETAIL DROP COLUMN BEHAVIOR
/
ALTER TABLE RPT_NOMINATION_DETAIL DROP COLUMN WON_FLAG
/
ALTER TABLE RPT_NOMINATION_DETAIL DROP COLUMN AWARD_TYPE
/
ALTER TABLE RPT_NOMINATION_DETAIL DROP COLUMN AWARD_AMT
/
ALTER TABLE RPT_NOMINATION_DETAIL DROP COLUMN FINAL_APPROVER_ID
/
ALTER TABLE RPT_NOMINATION_DETAIL DROP COLUMN FINAL_APPROVER_NAME
/
ALTER TABLE RPT_NOMINATION_DETAIL DROP COLUMN PROXY_USER_ID
/
ALTER TABLE RPT_NOMINATION_DETAIL DROP COLUMN PROXY_USER_NAME
/
ALTER TABLE RPT_NOMINATION_DETAIL DROP COLUMN APPROVER_COMMENTS
/
ALTER TABLE RPT_NOMINATION_DETAIL DROP COLUMN SUBMISSION_NOTIFY_FLAG
/
ALTER TABLE RPT_NOMINATION_DETAIL DROP COLUMN NOTIFICATION_DATE
/
ALTER TABLE RPT_NOMINATION_DETAIL DROP COLUMN SHOW_ON_REPORT_FLAG
/
ALTER TABLE RPT_NOMINATION_DETAIL DROP COLUMN CERTIFICATE
/
ALTER TABLE RPT_NOMINATION_DETAIL DROP COLUMN RECVR_POINTS
/
ALTER TABLE RPT_NOMINATION_DETAIL DROP COLUMN RECVR_SWEEPSTAKES_WON
/
ALTER TABLE RPT_NOMINATION_DETAIL DROP COLUMN GIVER_SWEEPSTAKES_WON
/
ALTER TABLE RPT_NOMINATION_DETAIL DROP COLUMN RECVR_SWEEPSTAKES_POINTS
/
ALTER TABLE RPT_NOMINATION_DETAIL DROP COLUMN GIVER_SWEEPSTAKES_POINTS
/
ALTER TABLE RPT_NOMINATION_DETAIL DROP COLUMN RECVR_BADGES_EARNED
/
ALTER TABLE RPT_NOMINATION_DETAIL DROP COLUMN APPROVAL_STATUS
/
ALTER TABLE RPT_NOMINATION_DETAIL DROP COLUMN EVALUATION_TYPE
/
ALTER TABLE RPT_NOMINATION_DETAIL DROP COLUMN AWARD_AMOUNT_FIXED
/
ALTER TABLE RPT_NOMINATION_DETAIL MODIFY CLAIM_ID NUMBER(18)
/
ALTER TABLE RPT_NOMINATION_DETAIL MODIFY CLAIM_ITEM_ID NUMBER(18)
/
ALTER TABLE RPT_NOMINATION_DETAIL MODIFY PROMOTION_ID NUMBER(18) NOT NULL
/
ALTER TABLE RPT_NOMINATION_DETAIL MODIFY PROMOTION_NAME VARCHAR2(1000) NOT NULL
/
ALTER TABLE RPT_NOMINATION_DETAIL MODIFY DATE_SUBMITTED DATE NOT NULL
/
ALTER TABLE RPT_NOMINATION_DETAIL MODIFY CLAIM_GROUP_ID NUMBER(18)
/
ALTER TABLE RPT_NOMINATION_DETAIL MODIFY TEAM_NAME VARCHAR2(50)
/
ALTER TABLE RPT_NOMINATION_DETAIL MODIFY GIVER_USER_ID NUMBER(18)
/
ALTER TABLE RPT_NOMINATION_DETAIL MODIFY GIVER_NODE_ID NUMBER(18)
/
ALTER TABLE RPT_NOMINATION_DETAIL MODIFY RECVR_USER_ID NUMBER(18)
/
ALTER TABLE RPT_NOMINATION_DETAIL MODIFY RECVR_NODE_ID NUMBER(18)
/
ALTER TABLE RPT_NOMINATION_DETAIL ADD ACTIVITY_ID NUMBER(18)
/
ALTER TABLE RPT_NOMINATION_DETAIL ADD PROMOTION_STATUS VARCHAR2(30)
/
ALTER TABLE RPT_NOMINATION_DETAIL ADD PROMOTION_AWARD_TYPE VARCHAR2(40)
/
ALTER TABLE RPT_NOMINATION_DETAIL ADD STEP_NUMBER NUMBER(2)
/
ALTER TABLE RPT_NOMINATION_DETAIL ADD CLAIM_APPROVAL_ROUND NUMBER(10)
/
ALTER TABLE RPT_NOMINATION_DETAIL ADD CLAIM_STATUS VARCHAR2(18)
/
ALTER TABLE RPT_NOMINATION_DETAIL ADD CLAIM_ITEM_STATUS VARCHAR2(18)
/
ALTER TABLE RPT_NOMINATION_DETAIL ADD NOMINATION_TIME_PERIOD_ID NUMBER(18)
/
ALTER TABLE RPT_NOMINATION_DETAIL ADD TIME_PERIOD_NAME VARCHAR2(50)
/
ALTER TABLE RPT_NOMINATION_DETAIL ADD TEAM_ID NUMBER(12)
/
ALTER TABLE RPT_NOMINATION_DETAIL ADD SWEEPSTAKES_WON NUMBER(1) DEFAULT 0
/
ALTER TABLE RPT_NOMINATION_DETAIL ADD GIVER_DEPARTMENT_TYPE VARCHAR2(100)
/
ALTER TABLE RPT_NOMINATION_DETAIL ADD GIVER_POSITION_TYPE VARCHAR2(100)
/
ALTER TABLE RPT_NOMINATION_DETAIL ADD GIVER_USER_NAME VARCHAR2(40)
/
ALTER TABLE RPT_NOMINATION_DETAIL ADD GIVER_ORG_ROLE VARCHAR2(30)
/
ALTER TABLE RPT_NOMINATION_DETAIL ADD RECVR_DEPARTMENT_TYPE VARCHAR2(100)
/
ALTER TABLE RPT_NOMINATION_DETAIL ADD RECVR_POSITION_TYPE VARCHAR2(100)
/
ALTER TABLE RPT_NOMINATION_DETAIL ADD RECVR_USER_NAME VARCHAR2(40)
/
ALTER TABLE RPT_NOMINATION_DETAIL ADD RECVR_ORG_ROLE VARCHAR2(30)
/
ALTER TABLE RPT_NOMINATION_DETAIL ADD CASH_AWARD_AMT NUMBER(18,4) DEFAULT 0 NOT NULL
/
ALTER TABLE RPT_NOMINATION_DETAIL ADD POINTS_AWARD_AMT NUMBER(12) DEFAULT 0 NOT NULL
/
ALTER TABLE RPT_NOMINATION_DETAIL ADD OTHER_AWARD_AMT NUMBER(18,4) DEFAULT 0 NOT NULL
/
ALTER TABLE RPT_NOMINATION_DETAIL ADD OTHER_AWARD_DESC VARCHAR2(300)
/
ALTER TABLE RPT_NOMINATION_DETAIL ADD R1_AWARD_TYPE VARCHAR2(40)
/
ALTER TABLE RPT_NOMINATION_DETAIL ADD R2_AWARD_TYPE VARCHAR2(40)
/
ALTER TABLE RPT_NOMINATION_DETAIL ADD R3_AWARD_TYPE VARCHAR2(40)
/
ALTER TABLE RPT_NOMINATION_DETAIL ADD R4_AWARD_TYPE VARCHAR2(40)
/
ALTER TABLE RPT_NOMINATION_DETAIL ADD R5_AWARD_TYPE VARCHAR2(40)
/
ALTER TABLE RPT_NOMINATION_DETAIL ADD R1_APPROVAL_STATUS VARCHAR2(18)
/
ALTER TABLE RPT_NOMINATION_DETAIL ADD R2_APPROVAL_STATUS VARCHAR2(18)
/
ALTER TABLE RPT_NOMINATION_DETAIL ADD R3_APPROVAL_STATUS VARCHAR2(18)
/
ALTER TABLE RPT_NOMINATION_DETAIL ADD R4_APPROVAL_STATUS VARCHAR2(18)
/
ALTER TABLE RPT_NOMINATION_DETAIL ADD R5_APPROVAL_STATUS VARCHAR2(18)
/
ALTER TABLE RPT_NOMINATION_DETAIL ADD R1_APPROVAL_DATE DATE
/
ALTER TABLE RPT_NOMINATION_DETAIL ADD R2_APPROVAL_DATE DATE
/
ALTER TABLE RPT_NOMINATION_DETAIL ADD R3_APPROVAL_DATE DATE
/
ALTER TABLE RPT_NOMINATION_DETAIL ADD R4_APPROVAL_DATE DATE
/
ALTER TABLE RPT_NOMINATION_DETAIL ADD R5_APPROVAL_DATE DATE
/
ALTER TABLE RPT_NOMINATION_DETAIL ADD R1_APPROVER_USER_ID NUMBER(18)
/
ALTER TABLE RPT_NOMINATION_DETAIL ADD R2_APPROVER_USER_ID NUMBER(18)
/
ALTER TABLE RPT_NOMINATION_DETAIL ADD R3_APPROVER_USER_ID NUMBER(18)
/
ALTER TABLE RPT_NOMINATION_DETAIL ADD R4_APPROVER_USER_ID NUMBER(18)
/
ALTER TABLE RPT_NOMINATION_DETAIL ADD R5_APPROVER_USER_ID NUMBER(18)
/
ALTER TABLE RPT_NOMINATION_DETAIL ADD R1_APPROVER_USER_NAME VARCHAR2(40)
/
ALTER TABLE RPT_NOMINATION_DETAIL ADD R2_APPROVER_USER_NAME VARCHAR2(40)
/
ALTER TABLE RPT_NOMINATION_DETAIL ADD R3_APPROVER_USER_NAME VARCHAR2(40)
/
ALTER TABLE RPT_NOMINATION_DETAIL ADD R4_APPROVER_USER_NAME VARCHAR2(40)
/
ALTER TABLE RPT_NOMINATION_DETAIL ADD R5_APPROVER_USER_NAME VARCHAR2(40)
/
ALTER TABLE RPT_NOMINATION_DETAIL ADD R1_APPROVER_FIRST_NAME VARCHAR2(40)
/
ALTER TABLE RPT_NOMINATION_DETAIL ADD R2_APPROVER_FIRST_NAME VARCHAR2(40)
/
ALTER TABLE RPT_NOMINATION_DETAIL ADD R3_APPROVER_FIRST_NAME VARCHAR2(40)
/
ALTER TABLE RPT_NOMINATION_DETAIL ADD R4_APPROVER_FIRST_NAME VARCHAR2(40)
/
ALTER TABLE RPT_NOMINATION_DETAIL ADD R5_APPROVER_FIRST_NAME VARCHAR2(40)
/
ALTER TABLE RPT_NOMINATION_DETAIL ADD R1_APPROVER_LAST_NAME VARCHAR2(40)
/
ALTER TABLE RPT_NOMINATION_DETAIL ADD R2_APPROVER_LAST_NAME VARCHAR2(40)
/
ALTER TABLE RPT_NOMINATION_DETAIL ADD R3_APPROVER_LAST_NAME VARCHAR2(40)
/
ALTER TABLE RPT_NOMINATION_DETAIL ADD R4_APPROVER_LAST_NAME VARCHAR2(40)
/
ALTER TABLE RPT_NOMINATION_DETAIL ADD R5_APPROVER_LAST_NAME VARCHAR2(40)
/
COMMENT ON TABLE RPT_NOMINATION_DETAIL IS 'Holds nomination details with up to 5 rounds of approvals.'
/
COMMENT ON COLUMN RPT_NOMINATION_DETAIL.RPT_NOMINATION_DETAIL_ID IS 'System generated Primary Key'
/
COMMENT ON COLUMN RPT_NOMINATION_DETAIL.CLAIM_ID IS 'Uniquely identifies the nomination claim.'
/
COMMENT ON COLUMN RPT_NOMINATION_DETAIL.CLAIM_ITEM_ID IS 'Uniquely identifies the nomination claim item.'
/
COMMENT ON COLUMN RPT_NOMINATION_DETAIL.ACTIVITY_ID IS 'Uniquely identifies the nomination activity.'
/
COMMENT ON COLUMN RPT_NOMINATION_DETAIL.PROMOTION_ID IS 'Uniquely identifies the nomination promotion.'
/
COMMENT ON COLUMN RPT_NOMINATION_DETAIL.PROMOTION_NAME IS 'The promotion name associated with the nomination.'
/
COMMENT ON COLUMN RPT_NOMINATION_DETAIL.PROMOTION_STATUS IS 'The promotion status associated with the nomination.'
/
COMMENT ON COLUMN RPT_NOMINATION_DETAIL.PROMOTION_AWARD_TYPE IS 'The promotion award type associated with the nomination.'
/
COMMENT ON COLUMN RPT_NOMINATION_DETAIL.DATE_SUBMITTED IS 'The date the nomination was originally submitted.'
/
COMMENT ON COLUMN RPT_NOMINATION_DETAIL.DATE_APPROVED IS 'The date the claim_item was approved..'
/
COMMENT ON COLUMN RPT_NOMINATION_DETAIL.IS_OPEN IS 'Indicates whether the nomination is still open for awarding.'
/
COMMENT ON COLUMN RPT_NOMINATION_DETAIL.STEP_NUMBER IS 'The number of rounds for this nomination.'
/
COMMENT ON COLUMN RPT_NOMINATION_DETAIL.CLAIM_APPROVAL_ROUND IS 'The current round of awards for this claim nomination.'
/
COMMENT ON COLUMN RPT_NOMINATION_DETAIL.CLAIM_STATUS IS 'The nomination claim status.'
/
COMMENT ON COLUMN RPT_NOMINATION_DETAIL.CLAIM_ITEM_STATUS IS 'The claim item status for the current approval round.'
/
COMMENT ON COLUMN RPT_NOMINATION_DETAIL.NOMINATION_TIME_PERIOD_ID IS 'Uniquely identifies the nomination''s associated time period.'
/
COMMENT ON COLUMN RPT_NOMINATION_DETAIL.TIME_PERIOD_NAME IS 'The associated time period''s name.'
/
COMMENT ON COLUMN RPT_NOMINATION_DETAIL.CLAIM_GROUP_ID IS 'Uniquely identifies the nominating group.'
/
COMMENT ON COLUMN RPT_NOMINATION_DETAIL.TEAM_ID IS 'Uniquely identifies the nominated team.'
/
COMMENT ON COLUMN RPT_NOMINATION_DETAIL.TEAM_NAME IS 'The name of the nominated team.'
/
COMMENT ON COLUMN RPT_NOMINATION_DETAIL.SWEEPSTAKES_WON IS 'Indicates whether the nomination is associated with sweepstakes.'
/
COMMENT ON COLUMN RPT_NOMINATION_DETAIL.GIVER_USER_ID IS 'The user ID of the nominator.'
/
COMMENT ON COLUMN RPT_NOMINATION_DETAIL.GIVER_NODE_ID IS 'The primary organization node of the nominator.'
/
COMMENT ON COLUMN RPT_NOMINATION_DETAIL.GIVER_COUNTRY_ID IS 'The primary address country of the nominator.'
/
COMMENT ON COLUMN RPT_NOMINATION_DETAIL.GIVER_DEPARTMENT_TYPE IS 'The employer department of the nominator.'
/
COMMENT ON COLUMN RPT_NOMINATION_DETAIL.GIVER_POSITION_TYPE IS 'The employer job of the nominator.'
/
COMMENT ON COLUMN RPT_NOMINATION_DETAIL.GIVER_PAX_STATUS IS 'The participant status of the nominator.'
/
COMMENT ON COLUMN RPT_NOMINATION_DETAIL.GIVER_USER_NAME IS 'The login ID of the nominator.'
/
COMMENT ON COLUMN RPT_NOMINATION_DETAIL.GIVER_FIRST_NAME IS 'The first name of the nominator.'
/
COMMENT ON COLUMN RPT_NOMINATION_DETAIL.GIVER_MIDDLE_NAME IS 'The middle name of the nominee.'
/
COMMENT ON COLUMN RPT_NOMINATION_DETAIL.GIVER_LAST_NAME IS 'The last name of the nominator.'
/
COMMENT ON COLUMN RPT_NOMINATION_DETAIL.GIVER_NODE_NAME IS 'The primary organization node name of the nominator.'
/
COMMENT ON COLUMN RPT_NOMINATION_DETAIL.GIVER_ORG_ROLE IS 'The primary organization role of the nominator.'
/
COMMENT ON COLUMN RPT_NOMINATION_DETAIL.RECVR_USER_ID IS 'The user ID of the nominee.'
/
COMMENT ON COLUMN RPT_NOMINATION_DETAIL.RECVR_NODE_ID IS 'The primary organization node of the nominee.'
/
COMMENT ON COLUMN RPT_NOMINATION_DETAIL.RECVR_COUNTRY_ID IS 'The primary address country of the nominee.'
/
COMMENT ON COLUMN RPT_NOMINATION_DETAIL.RECVR_DEPARTMENT_TYPE IS 'The employer job of the nominee.'
/
COMMENT ON COLUMN RPT_NOMINATION_DETAIL.RECVR_POSITION_TYPE IS 'The employer department of the nominee.'
/
COMMENT ON COLUMN RPT_NOMINATION_DETAIL.RECVR_PAX_STATUS IS 'The participant status of the nominee.'
/
COMMENT ON COLUMN RPT_NOMINATION_DETAIL.RECVR_USER_NAME IS 'The login ID of the nominee.'
/
COMMENT ON COLUMN RPT_NOMINATION_DETAIL.RECVR_FIRST_NAME IS 'The first name of the nominee.'
/
COMMENT ON COLUMN RPT_NOMINATION_DETAIL.RECVR_MIDDLE_NAME IS 'The middle name of the nominee.'
/
COMMENT ON COLUMN RPT_NOMINATION_DETAIL.RECVR_LAST_NAME IS 'The last name of the nominee.'
/
COMMENT ON COLUMN RPT_NOMINATION_DETAIL.RECVR_NODE_NAME IS 'The primary organization node name of the nominee.'
/
COMMENT ON COLUMN RPT_NOMINATION_DETAIL.RECVR_ORG_ROLE IS 'The primary organization role of the nominee.'
/
COMMENT ON COLUMN RPT_NOMINATION_DETAIL.CASH_AWARD_AMT IS 'Total cash awarded for this nomination.'
/
COMMENT ON COLUMN RPT_NOMINATION_DETAIL.POINTS_AWARD_AMT IS 'Total ponts awarded for this nomination.'
/
COMMENT ON COLUMN RPT_NOMINATION_DETAIL.OTHER_AWARD_AMT IS 'Total value of other award types awarded for this nomination.'
/
COMMENT ON COLUMN RPT_NOMINATION_DETAIL.OTHER_AWARD_DESC IS 'Description of other award types awarded for this nomination.'
/
COMMENT ON COLUMN RPT_NOMINATION_DETAIL.R1_AWARD_TYPE IS 'Round 1 award payout type.'
/
COMMENT ON COLUMN RPT_NOMINATION_DETAIL.R2_AWARD_TYPE IS 'Round 1 award payout type.'
/
COMMENT ON COLUMN RPT_NOMINATION_DETAIL.R3_AWARD_TYPE IS 'Round 2 award payout type.'
/
COMMENT ON COLUMN RPT_NOMINATION_DETAIL.R4_AWARD_TYPE IS 'Round 4 award payout type.'
/
COMMENT ON COLUMN RPT_NOMINATION_DETAIL.R5_AWARD_TYPE IS 'Round 5 award payout type.'
/
COMMENT ON COLUMN RPT_NOMINATION_DETAIL.R1_APPROVAL_STATUS IS 'Status of round 1 approval.'
/
COMMENT ON COLUMN RPT_NOMINATION_DETAIL.R2_APPROVAL_STATUS IS 'Status of round 2 approval.'
/
COMMENT ON COLUMN RPT_NOMINATION_DETAIL.R3_APPROVAL_STATUS IS 'Status of round 3 approval.'
/
COMMENT ON COLUMN RPT_NOMINATION_DETAIL.R4_APPROVAL_STATUS IS 'Status of round 4 approval.'
/
COMMENT ON COLUMN RPT_NOMINATION_DETAIL.R5_APPROVAL_STATUS IS 'Status of round 5 approval.'
/
COMMENT ON COLUMN RPT_NOMINATION_DETAIL.R1_APPROVAL_DATE IS 'Date round 1 of this nomiation was approved.'
/
COMMENT ON COLUMN RPT_NOMINATION_DETAIL.R2_APPROVAL_DATE IS 'Date round 2 of this nomiation was approved.'
/
COMMENT ON COLUMN RPT_NOMINATION_DETAIL.R3_APPROVAL_DATE IS 'Date round 3 of this nomiation was approved.'
/
COMMENT ON COLUMN RPT_NOMINATION_DETAIL.R4_APPROVAL_DATE IS 'Date round 4 of this nomiation was approved.'
/
COMMENT ON COLUMN RPT_NOMINATION_DETAIL.R5_APPROVAL_DATE IS 'Date round 5 of this nomiation was approved.'
/
COMMENT ON COLUMN RPT_NOMINATION_DETAIL.R1_APPROVER_USER_ID IS 'User ID of round 1 approver.'
/
COMMENT ON COLUMN RPT_NOMINATION_DETAIL.R2_APPROVER_USER_ID IS 'User ID of round 2 approver.'
/
COMMENT ON COLUMN RPT_NOMINATION_DETAIL.R3_APPROVER_USER_ID IS 'User ID of round 3 approver.'
/
COMMENT ON COLUMN RPT_NOMINATION_DETAIL.R4_APPROVER_USER_ID IS 'User ID of round 4 approver.'
/
COMMENT ON COLUMN RPT_NOMINATION_DETAIL.R5_APPROVER_USER_ID IS 'User ID of round 5 approver.'
/
COMMENT ON COLUMN RPT_NOMINATION_DETAIL.R1_APPROVER_USER_NAME IS 'The login ID of round 1 approver.'
/
COMMENT ON COLUMN RPT_NOMINATION_DETAIL.R2_APPROVER_USER_NAME IS 'The login ID of round 2 approver.'
/
COMMENT ON COLUMN RPT_NOMINATION_DETAIL.R3_APPROVER_USER_NAME IS 'The login ID of round 3 approver.'
/
COMMENT ON COLUMN RPT_NOMINATION_DETAIL.R4_APPROVER_USER_NAME IS 'The login ID of round 4 approver.'
/
COMMENT ON COLUMN RPT_NOMINATION_DETAIL.R5_APPROVER_USER_NAME IS 'The login ID of round 5 approver.'
/
COMMENT ON COLUMN RPT_NOMINATION_DETAIL.R1_APPROVER_FIRST_NAME IS 'First name of round 1 approver.'
/
COMMENT ON COLUMN RPT_NOMINATION_DETAIL.R2_APPROVER_FIRST_NAME IS 'First name of round 2 approver.'
/
COMMENT ON COLUMN RPT_NOMINATION_DETAIL.R3_APPROVER_FIRST_NAME IS 'First name of round 3 approver.'
/
COMMENT ON COLUMN RPT_NOMINATION_DETAIL.R4_APPROVER_FIRST_NAME IS 'First name of round 4 approver.'
/
COMMENT ON COLUMN RPT_NOMINATION_DETAIL.R5_APPROVER_FIRST_NAME IS 'First name of round 5 approver.'
/
COMMENT ON COLUMN RPT_NOMINATION_DETAIL.R1_APPROVER_LAST_NAME IS 'Last name of round 1 approver.'
/
COMMENT ON COLUMN RPT_NOMINATION_DETAIL.R2_APPROVER_LAST_NAME IS 'Last name of round 2 approver.'
/
COMMENT ON COLUMN RPT_NOMINATION_DETAIL.R3_APPROVER_LAST_NAME IS 'Last name of round 3 approver.'
/
COMMENT ON COLUMN RPT_NOMINATION_DETAIL.R4_APPROVER_LAST_NAME IS 'Last name of round 4 approver.'
/
COMMENT ON COLUMN RPT_NOMINATION_DETAIL.R5_APPROVER_LAST_NAME IS 'Last name of round 5 approver.'
/
COMMENT ON COLUMN RPT_NOMINATION_DETAIL.CREATED_BY IS 'The ID of the user who created this record.'
/
COMMENT ON COLUMN RPT_NOMINATION_DETAIL.DATE_CREATED IS 'The date and time at which this record was created.'
/
COMMENT ON COLUMN RPT_NOMINATION_DETAIL.MODIFIED_BY IS 'The ID of the user who last modified this record.'
/
COMMENT ON COLUMN RPT_NOMINATION_DETAIL.DATE_MODIFIED IS 'The date and time this record was last modified.'
/
COMMENT ON COLUMN RPT_NOMINATION_DETAIL.VERSION IS 'Indicates the current data iteration for this record.'
/
CREATE UNIQUE INDEX rpt_nomination_detail_PK
   ON rpt_nomination_detail
   (rpt_nomination_detail_id)
/
CREATE INDEX rpt_nomination_detail_idx2
   ON rpt_nomination_detail
   (date_submitted,
    giver_node_id,
    giver_user_id,
    promotion_id
   )
/
CREATE INDEX rpt_nomination_detail_idx3
   ON rpt_nomination_detail
   (date_submitted,
    recvr_node_id,
    recvr_user_id,
    promotion_id
   )
/
CREATE INDEX rpt_nomination_detail_idx4
   ON rpt_nomination_detail
   (giver_user_id,
    giver_node_id,
    date_submitted,
    promotion_id
   )
/
CREATE INDEX rpt_nomination_detail_idx5
   ON rpt_nomination_detail
   (recvr_user_id,
    recvr_node_id,
    date_submitted,
    promotion_id
   )
/
CREATE INDEX rpt_nomination_detail_idx6
   ON rpt_nomination_detail
   (claim_item_id,
    claim_id
   )
/
CREATE INDEX rpt_nomination_detail_idx7
   ON rpt_nomination_detail
   (activity_id
   )
/
ALTER TABLE rpt_nomination_detail ADD
( CONSTRAINT rpt_nomination_detail_PK
  PRIMARY KEY
     (rpt_nomination_detail_id)
  USING INDEX rpt_nomination_detail_PK
  ENABLE VALIDATE
)
/