ALTER TABLE PARTICIPANT_COMM_PREFERENCE ADD 
(CONSTRAINT PARTICIPANT_COMM_PREFER_ID_PK PRIMARY KEY (PARTICIPANT_COMM_PREFERENCE_ID))
/
ALTER TABLE PARTICIPANT_COMM_PREFERENCE ADD
(CONSTRAINT PARTICIPANT_COMM_PREFERENCE_UK UNIQUE(USER_ID,COMMUNICATION_CODE,SMS_GROUP_TYPE))
/