ALTER TABLE RPT_AWARDMEDIA_DETAIL MODIFY MEDIA_TYPE VARCHAR2(40 CHAR)
/
ALTER TABLE RPT_AWARDMEDIA_DETAIL MODIFY NODE_ID NUMBER(18)
/
ALTER TABLE RPT_AWARDMEDIA_DETAIL MODIFY NODE_NAME VARCHAR2(255 CHAR)
/
ALTER TABLE RPT_AWARDMEDIA_DETAIL MODIFY PROMOTION_ID NUMBER(18)
/
ALTER TABLE RPT_AWARDMEDIA_DETAIL MODIFY PROMOTION_NAME VARCHAR2(1000 CHAR)
/
ALTER TABLE RPT_AWARDMEDIA_DETAIL MODIFY PROMOTION_TYPE VARCHAR2(80 CHAR)
/
ALTER TABLE RPT_AWARDMEDIA_DETAIL MODIFY IS_TAXABLE NUMBER(1)
/
ALTER TABLE RPT_AWARDMEDIA_DETAIL MODIFY HIERARCHY_ID NUMBER(18)
/
ALTER TABLE RPT_AWARDMEDIA_DETAIL MODIFY USER_ID NUMBER(12)
/
ALTER TABLE RPT_AWARDMEDIA_DETAIL MODIFY PARTICIPANT_NAME VARCHAR2(150 CHAR)
/
ALTER TABLE RPT_AWARDMEDIA_DETAIL MODIFY PAX_FIRST_NAME VARCHAR2(40 CHAR)
/
ALTER TABLE RPT_AWARDMEDIA_DETAIL MODIFY PAX_MIDDLE_NAME VARCHAR2(40 CHAR)
/
ALTER TABLE RPT_AWARDMEDIA_DETAIL MODIFY PAX_LAST_NAME VARCHAR2(40 CHAR)
/
ALTER TABLE RPT_AWARDMEDIA_DETAIL MODIFY PARTICIPANT_CURRENT_STATUS VARCHAR2(30 CHAR)
/
ALTER TABLE RPT_AWARDMEDIA_DETAIL MODIFY USER_NAME VARCHAR2(40 CHAR)
/
ALTER TABLE RPT_AWARDMEDIA_DETAIL MODIFY POSITION_TYPE VARCHAR2(100 CHAR)
/
ALTER TABLE RPT_AWARDMEDIA_DETAIL MODIFY DEPARTMENT VARCHAR2(100 CHAR)
/
ALTER TABLE RPT_AWARDMEDIA_DETAIL MODIFY MEDIA_AMOUNT NUMBER(12,2)
/
ALTER TABLE RPT_AWARDMEDIA_DETAIL MODIFY SENDER_LAST_NAME VARCHAR2(40 CHAR)
/
ALTER TABLE RPT_AWARDMEDIA_DETAIL MODIFY SENDER_FIRST_NAME VARCHAR2(40 CHAR)
/
ALTER TABLE RPT_AWARDMEDIA_DETAIL MODIFY HIERARCHY_PATH VARCHAR2(1000 CHAR)
/
ALTER TABLE RPT_AWARDMEDIA_DETAIL MODIFY JOURNAL_ID NUMBER(12)
/
ALTER TABLE RPT_AWARDMEDIA_DETAIL
ADD AWARD_PAYOUT_TYPE VARCHAR2(40 CHAR)
/
ALTER TABLE RPT_AWARDMEDIA_DETAIL
ADD USER_CURRENCY VARCHAR2(8 CHAR)
/
ALTER TABLE RPT_AWARDMEDIA_DETAIL
ADD ASSET_KEY_LEVEL_NAME VARCHAR2(40 CHAR)
/
CREATE INDEX IDX_RPT_AWARDMEDIA_DTL_JOURNAL ON RPT_AWARDMEDIA_DETAIL
(JOURNAL_ID)
/
CREATE INDEX RPT_AWARDMEDIA_DETAIL_IDX1 ON RPT_AWARDMEDIA_DETAIL
(PROMOTION_ID)
/
CREATE INDEX IDX_RPT_AWARDMEDIA_DTL_NODE ON RPT_AWARDMEDIA_DETAIL
(NODE_ID)
/
ALTER TABLE RPT_AWARDMEDIA_SUMMARY MODIFY TOTAL_MEDIA_AMOUNT NUMBER(20,4)
/