ALTER TABLE RPT_CP_MANAGER_OVERRIDE MODIFY PROMOTION_NAME VARCHAR2(1000 CHAR)
/
ALTER TABLE RPT_CP_MANAGER_OVERRIDE MODIFY OVERRIDE_AMOUNT NUMBER(12,2)
/
ALTER TABLE RPT_CP_SELECTION_DETAIL MODIFY BASIC_AWARD_EARNED NUMBER(12)
/
ALTER TABLE RPT_CP_SELECTION_DETAIL MODIFY CURRENT_VALUE NUMBER(30,4)
/
ALTER TABLE RPT_CP_SELECTION_DETAIL MODIFY BASE_QUANTITY NUMBER(18,4)
/
ALTER TABLE RPT_CP_SELECTION_DETAIL MODIFY PROMOTION_NAME VARCHAR2(1000 CHAR)
/