CREATE SEQUENCE APPROVER_CRITERIA_PK_SQ START WITH 250 INCREMENT BY 1
/
CREATE TABLE APPROVER_CRITERIA 
  ( 
     APPROVER_CRITERIA_ID NUMBER(18, 0) NOT NULL, 
     APPROVER_OPTION_ID   NUMBER(18,0) NOT NULL,
     APPROVER_VALUE       VARCHAR2(100),
     MIN_VAL              NUMBER(10), 
     MAX_VAL              NUMBER(10), 
     CREATED_BY           NUMBER(18, 0) NOT NULL, 
     DATE_CREATED         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, 
     MODIFIED_BY          NUMBER(18, 0), 
     DATE_MODIFIED        TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
     VERSION              NUMBER(18, 0) DEFAULT 1 
  )
/
ALTER TABLE APPROVER_CRITERIA
ADD CONSTRAINT APPROVER_CRITERIA_PK PRIMARY KEY (APPROVER_CRITERIA_ID)
USING INDEX
/
ALTER TABLE APPROVER_CRITERIA
ADD CONSTRAINT APPROVER_OPTION_FK FOREIGN KEY (APPROVER_OPTION_ID)
REFERENCES APPROVER_OPTION (APPROVER_OPTION_ID)
/
