CREATE SEQUENCE NOMINATION_TIME_PERIOD_PK_SQ START WITH 250 INCREMENT BY 1
/
CREATE TABLE PROMO_NOMINATION_TIME_PERIOD (
	NOMINATION_TIME_PERIOD_ID			NUMBER(18,0) NOT NULL,
    PROMOTION_ID 						NUMBER(18,0) NOT NULL, 
	TIME_PERIOD_NAME 					VARCHAR2(50),
	TIME_PERIOD_NAME_ASSET_CODE    	    VARCHAR2(1000),
	TIME_PERIOD_START_DATE 				DATE, 
	TIME_PERIOD_END_DATE 				DATE,
	MAX_SUBMISSION_ALLOWED 		   		NUMBER(18,0),
	MAX_NOMINATIONS_ALLOWED				NUMBER(18,0),
	MAX_WINS_ALLOWED					NUMBER(18,0)
  )
/
ALTER TABLE PROMO_NOMINATION_TIME_PERIOD
ADD CONSTRAINT NOMINATION_TIME_PERI_PK PRIMARY KEY (NOMINATION_TIME_PERIOD_ID)
USING INDEX
/
ALTER TABLE PROMO_NOMINATION_TIME_PERIOD
ADD CONSTRAINT NOMINATION_TIME_PERI_FK FOREIGN KEY (PROMOTION_ID)
REFERENCES promotion (PROMOTION_ID)
/
CREATE INDEX NOMINATION_TIME_PERI_FK_idx ON PROMO_NOMINATION_TIME_PERIOD
  (PROMOTION_ID)
/