ALTER TABLE CLAIM_ITEM_APPROVER
ADD NOTIFICATION_DATE DATE
/
ALTER TABLE CLAIM_ITEM_APPROVER
ADD TIME_PERIOD_ID NUMBER(18)
/
ALTER TABLE CLAIM_ITEM_APPROVER
ADD APPROVER_COMMENTS VARCHAR2(4000)
/
create index claim_item_appr_claim_gpid_idx ON
CLAIM_item_approver(CLAIM_GROUP_ID)
/
COMMENT ON COLUMN CLAIM_ITEM_APPROVER.NOTIFICATION_DATE IS 'Notification date of the approval'
/
COMMENT ON COLUMN CLAIM_ITEM_APPROVER.TIME_PERIOD_ID IS 'Time period id when the winner is picked for a time period'
/