ALTER TABLE RPT_THROWDOWN_ACTIVITY MODIFY LOGIN_ID VARCHAR2(40)
/
ALTER TABLE RPT_THROWDOWN_ACTIVITY MODIFY OUTCOME VARCHAR2(80)
/
ALTER TABLE RPT_THROWDOWN_ACTIVITY MODIFY PAYOUT NUMBER(12)
/
ALTER TABLE RPT_THROWDOWN_ACTIVITY MODIFY ACTIVITY_ID NUMBER(12)
/
ALTER TABLE RPT_THROWDOWN_ACTIVITY MODIFY COUNTRY_ID NUMBER(12)
/