ALTER TABLE RPT_BUDGET_PROMOTION MODIFY DISTRIBUTION_TYPE VARCHAR2(10 CHAR)
/
ALTER TABLE RPT_BUDGET_TRANS_DETAIL MODIFY BUDGET_STATUS VARCHAR2(30)
/
ALTER TABLE RPT_BUDGET_TRANS_DETAIL MODIFY JOURNAL_ID NUMBER(12,0)
/
ALTER TABLE RPT_BUDGET_TRANS_DETAIL MODIFY TRANS_AMOUNT NUMBER(20,8)
/
ALTER TABLE RPT_BUDGET_TRANS_DETAIL MODIFY PROMOTION_NAME VARCHAR2(1000)
/
ALTER TABLE RPT_BUDGET_USAGE_DETAIL MODIFY BUDGET_TYPE VARCHAR2(30)
/
ALTER TABLE RPT_BUDGET_USAGE_DETAIL MODIFY IS_ACTIVE NUMBER(1)
/
ALTER TABLE RPT_BUDGET_USAGE_DETAIL MODIFY MULTI_PROMOTION VARCHAR2(10 CHAR)
/
CREATE INDEX RPT_BUDGET_USAGE_DETAIL_IDX1 ON RPT_BUDGET_USAGE_DETAIL
(BUDGET_ID, BUDGET_STATUS,START_DATE,END_DATE)
/
CREATE INDEX RPT_BUDGET_TRANS_DETAIL_IDX1 ON RPT_BUDGET_TRANS_DETAIL
(BUDGET_ID, TRANS_DATE, BUDGET_STATUS)
/