ALTER TABLE RPT_BUDGET_TRANS_DETAIL
ADD (recipient_first_name  VARCHAR2(40 CHAR))
/
ALTER TABLE RPT_BUDGET_TRANS_DETAIL
ADD (recipient_last_name  VARCHAR2(40 CHAR))
/
ALTER TABLE RPT_CASH_BUDGET_TRANS_DETAIL
ADD (recipient_first_name  VARCHAR2(40 CHAR))
/
ALTER TABLE RPT_CASH_BUDGET_TRANS_DETAIL
ADD (recipient_last_name  VARCHAR2(40 CHAR))
/