--liquibase formatted sql

--changeset gorantla:1
--comment ADD NOT NULL constraint 
--preconditions onFail:MARK_RAN onError:MARK_RAN
--precondition-sql-check expectedResult:0 SELECT DECODE(NULLABLE,'Y',0,1) FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'APPLICATION_USER' AND COLUMN_NAME = 'ROSTER_USER_ID'
ALTER TABLE APPLICATION_USER MODIFY ROSTER_USER_ID NOT NULL;
--rollback ALTER TABLE APPLICATION_USER MODIFY ROSTER_USER_ID NULL

--changeset gorantla:2
--comment ADD NOT NULL constraint
--preconditions onFail:MARK_RAN onError:MARK_RAN
--precondition-sql-check expectedResult:0 SELECT DECODE(NULLABLE,'Y',0,1) FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'HIERARCHY' AND COLUMN_NAME = 'ROSTER_HIERARCHY_ID'
ALTER TABLE HIERARCHY MODIFY ROSTER_HIERARCHY_ID NOT NULL;
--rollback ALTER TABLE HIERARCHY MODIFY ROSTER_HIERARCHY_ID NULL

--changeset gorantla:3
--comment ADD NOT NULL constraint
--preconditions onFail:MARK_RAN onError:MARK_RAN
--precondition-sql-check expectedResult:0 SELECT DECODE(NULLABLE,'Y',0,1) FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'NODE' AND COLUMN_NAME = 'ROSTER_NODE_ID'
ALTER TABLE NODE MODIFY ROSTER_NODE_ID NOT NULL;
--rollback ALTER TABLE NODE MODIFY ROSTER_NODE_ID NULL

--changeset gorantla:4
--comment ADD NOT NULL constraint
--preconditions onFail:MARK_RAN onError:MARK_RAN
--precondition-sql-check expectedResult:0 SELECT DECODE(NULLABLE,'Y',0,1) FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'AUDIENCE' AND COLUMN_NAME = 'ROSTER_AUDIENCE_ID'
ALTER TABLE AUDIENCE MODIFY ROSTER_AUDIENCE_ID NOT NULL;
--rollback ALTER TABLE AUDIENCE MODIFY ROSTER_AUDIENCE_ID NULL

--changeset gorantla:5
--comment ADD NOT NULL constraint
--preconditions onFail:MARK_RAN onError:MARK_RAN
--precondition-sql-check expectedResult:0 SELECT DECODE(NULLABLE,'Y',0,1) FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'USER_PHONE' AND COLUMN_NAME = 'ROSTER_PHONE_ID'
ALTER TABLE USER_PHONE MODIFY ROSTER_PHONE_ID NOT NULL;
--rollback ALTER TABLE USER_PHONE MODIFY ROSTER_PHONE_ID NULL

--changeset gorantla:6
--comment ADD NOT NULL constraint
--preconditions onFail:MARK_RAN onError:MARK_RAN
--precondition-sql-check expectedResult:0 SELECT DECODE(NULLABLE,'Y',0,1) FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'USER_EMAIL_ADDRESS' AND COLUMN_NAME = 'ROSTER_EMAIL_ID'
ALTER TABLE USER_EMAIL_ADDRESS MODIFY ROSTER_EMAIL_ID NOT NULL;
--rollback ALTER TABLE USER_EMAIL_ADDRESS MODIFY ROSTER_EMAIL_ID NULL

--changeset gorantla:7
--comment ADD NOT NULL constraint
--preconditions onFail:MARK_RAN onError:MARK_RAN
--precondition-sql-check expectedResult:0 SELECT DECODE(NULLABLE,'Y',0,1) FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'USER_ADDRESS' AND COLUMN_NAME = 'ROSTER_ADDRESS_ID'
ALTER TABLE USER_ADDRESS MODIFY ROSTER_ADDRESS_ID NOT NULL;
--rollback ALTER TABLE USER_ADDRESS MODIFY ROSTER_ADDRESS_ID NULL

--changeset gorantla:8
--comment ADD NOT NULL constraint
--preconditions onFail:MARK_RAN onError:MARK_RAN
--precondition-sql-check expectedResult:0 SELECT DECODE(NULLABLE,'Y',0,1) FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'CHARACTERISTIC' AND COLUMN_NAME = 'ROSTER_CHARACTERISTIC_ID'
ALTER TABLE CHARACTERISTIC MODIFY ROSTER_CHARACTERISTIC_ID NOT NULL;
--rollback ALTER TABLE CHARACTERISTIC MODIFY ROSTER_CHARACTERISTIC_ID NULL

--changeset gorantla:9
--comment ADD NOT NULL constraint
--preconditions onFail:MARK_RAN onError:MARK_RAN
--precondition-sql-check expectedResult:0 SELECT DECODE(NULLABLE,'Y',0,1) FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'USER_DEVICE' AND COLUMN_NAME = 'ROSTER_DEVICE_ID'
ALTER TABLE USER_DEVICE MODIFY ROSTER_DEVICE_ID NOT NULL;
--rollback ALTER TABLE USER_DEVICE MODIFY ROSTER_DEVICE_ID NULL

--changeset gorantla:10
--comment ADD NOT NULL constraint
--preconditions onFail:MARK_RAN onError:MARK_RAN
--precondition-sql-check expectedResult:0 SELECT DECODE(NULLABLE,'Y',0,1) FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'USER_CHARACTERISTIC' AND COLUMN_NAME = 'ROSTER_USER_CHAR_ID'
ALTER TABLE USER_CHARACTERISTIC MODIFY ROSTER_USER_CHAR_ID NOT NULL;
--rollback ALTER TABLE USER_CHARACTERISTIC MODIFY ROSTER_USER_CHAR_ID NULL

--changeset gorantla:11
--comment ADD NOT NULL constraint
--preconditions onFail:MARK_RAN onError:MARK_RAN
--precondition-sql-check expectedResult:0 SELECT DECODE(NULLABLE,'Y',0,1) FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'NODE_CHARACTERISTIC' AND COLUMN_NAME = 'ROSTER_NODE_CHAR_ID'
ALTER TABLE NODE_CHARACTERISTIC MODIFY ROSTER_NODE_CHAR_ID NOT NULL;
--rollback ALTER TABLE NODE_CHARACTERISTIC MODIFY ROSTER_NODE_CHAR_ID NULL