--liquibase formatted sql

--changeset gorantla:1
--comment RENAME column
--preconditions onFail:MARK_RAN onError:MARK_RAN
--precondition-sql-check expectedResult:1 SELECT count(*) FROM  USER_TAB_COLUMNS WHERE TABLE_NAME = 'APPLICATION_USER'  AND COLUMN_NAME = 'ROSTERPERSONID'
ALTER TABLE APPLICATION_USER RENAME COLUMN ROSTERPERSONID TO ROSTER_USER_ID;
--rollback ALTER TABLE APPLICATION_USER RENAME COLUMN ROSTER_USER_ID TO ROSTERPERSONID

--changeset gorantla:2
--comment RENAME column
--preconditions onFail:MARK_RAN onError:MARK_RAN
--precondition-sql-check expectedResult:1 SELECT count(*) FROM  USER_TAB_COLUMNS WHERE TABLE_NAME = 'HIERARCHY'  AND COLUMN_NAME = 'HIERARCHY_UUID'
ALTER TABLE HIERARCHY RENAME COLUMN HIERARCHY_UUID TO ROSTER_HIERARCHY_ID;
--rollback ALTER TABLE HIERARCHY RENAME COLUMN ROSTER_HIERARCHY_ID TO HIERARCHY_UUID

--changeset gorantla:3
--comment RENAME column
--preconditions onFail:MARK_RAN onError:MARK_RAN
--precondition-sql-check expectedResult:1 SELECT count(*) FROM  USER_TAB_COLUMNS WHERE TABLE_NAME = 'NODE'  AND COLUMN_NAME = 'NODE_UUID'
ALTER TABLE NODE RENAME COLUMN NODE_UUID TO ROSTER_NODE_ID;
--rollback ALTER TABLE NODE RENAME COLUMN ROSTER_NODE_ID TO NODE_UUID

--changeset gorantla:4
--comment RENAME column
--preconditions onFail:MARK_RAN onError:MARK_RAN
--precondition-sql-check expectedResult:1 SELECT count(*) FROM  USER_TAB_COLUMNS WHERE TABLE_NAME = 'AUDIENCE'  AND COLUMN_NAME = 'AUDIENCE_UUID'
ALTER TABLE AUDIENCE RENAME COLUMN AUDIENCE_UUID TO ROSTER_AUDIENCE_ID;
--rollback ALTER TABLE AUDIENCE RENAME COLUMN ROSTER_AUDIENCE_ID TO AUDIENCE_UUID

--changeset gorantla:5
--comment ADD column
--preconditions onFail:MARK_RAN onError:MARK_RAN
--precondition-sql-check expectedResult:0 SELECT count(*) FROM  USER_TAB_COLUMNS WHERE TABLE_NAME = 'USER_PHONE'  AND COLUMN_NAME = 'ROSTER_PHONE_ID'
ALTER TABLE USER_PHONE ADD ROSTER_PHONE_ID VARCHAR2(50) UNIQUE;
--rollback ALTER TABLE USER_PHONE DROP COLUMN ROSTER_PHONE_ID

--changeset gorantla:6
--comment ADD column
--preconditions onFail:MARK_RAN onError:MARK_RAN
--precondition-sql-check expectedResult:0 SELECT count(*) FROM  USER_TAB_COLUMNS WHERE TABLE_NAME = 'USER_EMAIL_ADDRESS'  AND COLUMN_NAME = 'ROSTER_EMAIL_ID'
ALTER TABLE USER_EMAIL_ADDRESS ADD ROSTER_EMAIL_ID VARCHAR2(50) UNIQUE;
--rollback ALTER TABLE USER_EMAIL_ADDRESS DROP COLUMN ROSTER_EMAIL_ID

--changeset gorantla:7
--comment ADD column
--preconditions onFail:MARK_RAN onError:MARK_RAN
--precondition-sql-check expectedResult:0 SELECT count(*) FROM  USER_TAB_COLUMNS WHERE TABLE_NAME = 'USER_ADDRESS'  AND COLUMN_NAME = 'ROSTER_ADDRESS_ID'
ALTER TABLE USER_ADDRESS ADD ROSTER_ADDRESS_ID VARCHAR2(50) UNIQUE;
--rollback ALTER TABLE USER_ADDRESS DROP COLUMN ROSTER_ADDRESS_ID

--changeset gorantla:8
--comment ADD column
--preconditions onFail:MARK_RAN onError:MARK_RAN
--precondition-sql-check expectedResult:0 SELECT count(*) FROM  USER_TAB_COLUMNS WHERE TABLE_NAME = 'CHARACTERISTIC'  AND COLUMN_NAME = 'ROSTER_CHARACTERISTIC_ID'
ALTER TABLE CHARACTERISTIC ADD ROSTER_CHARACTERISTIC_ID VARCHAR2(50) UNIQUE;
--rollback ALTER TABLE CHARACTERISTIC DROP COLUMN ROSTER_CHARACTERISTIC_ID

--changeset gorantla:9
--comment ADD column
--preconditions onFail:MARK_RAN onError:MARK_RAN
--precondition-sql-check expectedResult:0 SELECT count(*) FROM  USER_TAB_COLUMNS WHERE TABLE_NAME = 'USER_DEVICE'  AND COLUMN_NAME = 'ROSTER_DEVICE_ID'
ALTER TABLE USER_DEVICE ADD ROSTER_DEVICE_ID VARCHAR2(50) UNIQUE;
--rollback ALTER TABLE USER_DEVICE DROP COLUMN ROSTER_DEVICE_ID

--changeset gorantla:10
--comment ADD column
--preconditions onFail:MARK_RAN onError:MARK_RAN
--precondition-sql-check expectedResult:0 SELECT count(*) FROM  USER_TAB_COLUMNS WHERE TABLE_NAME = 'USER_CHARACTERISTIC'  AND COLUMN_NAME = 'ROSTER_USER_CHAR_ID'
ALTER TABLE USER_CHARACTERISTIC ADD ROSTER_USER_CHAR_ID VARCHAR2(50) UNIQUE;
--rollback ALTER TABLE USER_CHARACTERISTIC DROP COLUMN ROSTER_USER_CHAR_ID

--changeset gorantla:11
--comment ADD column
--preconditions onFail:MARK_RAN onError:MARK_RAN
--precondition-sql-check expectedResult:0 SELECT count(*) FROM  USER_TAB_COLUMNS WHERE TABLE_NAME = 'NODE_CHARACTERISTIC'  AND COLUMN_NAME = 'ROSTER_NODE_CHAR_ID'
ALTER TABLE NODE_CHARACTERISTIC ADD ROSTER_NODE_CHAR_ID VARCHAR2(50) UNIQUE;
--rollback ALTER TABLE NODE_CHARACTERISTIC DROP COLUMN ROSTER_NODE_CHAR_ID